/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getArrayDecoder,
  getArrayEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Account,
  type Address,
  type EncodedAccount,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from "@solana/kit";
import { getBarDecoder, getBarEncoder, type Bar, type BarArgs } from "../types";

export const BARS_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([
  35, 183, 0, 217, 23, 243, 155, 5,
]);

export function getBarsDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(BARS_DISCRIMINATOR);
}

export type Bars = {
  discriminator: ReadonlyUint8Array;
  market: number;
  pad: ReadonlyUint8Array;
  /** The latest second posted, ms. */
  last: bigint;
  ring: Array<Bar>;
};

export type BarsArgs = {
  market: number;
  pad: ReadonlyUint8Array;
  /** The latest second posted, ms. */
  last: number | bigint;
  ring: Array<BarArgs>;
};

/** Gets the encoder for {@link BarsArgs} account data. */
export function getBarsEncoder(): FixedSizeEncoder<BarsArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["market", getU8Encoder()],
      ["pad", fixEncoderSize(getBytesEncoder(), 7)],
      ["last", getI64Encoder()],
      ["ring", getArrayEncoder(getBarEncoder(), { size: 240 })],
    ]),
    (value) => ({ ...value, discriminator: BARS_DISCRIMINATOR }),
  );
}

/** Gets the decoder for {@link Bars} account data. */
export function getBarsDecoder(): FixedSizeDecoder<Bars> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["market", getU8Decoder()],
    ["pad", fixDecoderSize(getBytesDecoder(), 7)],
    ["last", getI64Decoder()],
    ["ring", getArrayDecoder(getBarDecoder(), { size: 240 })],
  ]);
}

/** Gets the codec for {@link Bars} account data. */
export function getBarsCodec(): FixedSizeCodec<BarsArgs, Bars> {
  return combineCodec(getBarsEncoder(), getBarsDecoder());
}

export function decodeBars<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>,
): Account<Bars, TAddress>;
export function decodeBars<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>,
): MaybeAccount<Bars, TAddress>;
export function decodeBars<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>,
): Account<Bars, TAddress> | MaybeAccount<Bars, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getBarsDecoder(),
  );
}

export async function fetchBars<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<Account<Bars, TAddress>> {
  const maybeAccount = await fetchMaybeBars(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeBars<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<MaybeAccount<Bars, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeBars(maybeAccount);
}

export async function fetchAllBars(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<Account<Bars>[]> {
  const maybeAccounts = await fetchAllMaybeBars(rpc, addresses, config);
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeBars(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<MaybeAccount<Bars>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodeBars(maybeAccount));
}

export function getBarsSize(): number {
  return 9624;
}
