/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU128Decoder,
  getU128Encoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Account,
  type Address,
  type EncodedAccount,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from "@solana/kit";

export const HOLDER_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([
  37, 121, 1, 40, 55, 46, 199, 157,
]);

export function getHolderDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(HOLDER_DISCRIMINATOR);
}

export type Holder = {
  discriminator: ReadonlyUint8Array;
  player: Address;
  /** SKT, millionths. */
  skt: bigint;
  /** `Rewards::acc` when what this balance had earned was last counted into `unclaimed`. */
  accAt: bigint;
  /** USDC e6 earned and not yet claimed. */
  unclaimed: bigint;
  claimed: bigint;
  /** Lifetime net result, USDC e6: what settling credited them (paid and owed) less the stakes it decided. */
  net: bigint;
  /** The deepest net loss they have ever been at (`-net` at its lowest): SKT mints only past it. */
  worst: bigint;
  bump: number;
  reserved: ReadonlyUint8Array;
};

export type HolderArgs = {
  player: Address;
  /** SKT, millionths. */
  skt: number | bigint;
  /** `Rewards::acc` when what this balance had earned was last counted into `unclaimed`. */
  accAt: number | bigint;
  /** USDC e6 earned and not yet claimed. */
  unclaimed: number | bigint;
  claimed: number | bigint;
  /** Lifetime net result, USDC e6: what settling credited them (paid and owed) less the stakes it decided. */
  net: number | bigint;
  /** The deepest net loss they have ever been at (`-net` at its lowest): SKT mints only past it. */
  worst: number | bigint;
  bump: number;
  reserved: ReadonlyUint8Array;
};

/** Gets the encoder for {@link HolderArgs} account data. */
export function getHolderEncoder(): FixedSizeEncoder<HolderArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["player", getAddressEncoder()],
      ["skt", getU64Encoder()],
      ["accAt", getU128Encoder()],
      ["unclaimed", getU64Encoder()],
      ["claimed", getU64Encoder()],
      ["net", getI64Encoder()],
      ["worst", getU64Encoder()],
      ["bump", getU8Encoder()],
      ["reserved", fixEncoderSize(getBytesEncoder(), 32)],
    ]),
    (value) => ({ ...value, discriminator: HOLDER_DISCRIMINATOR }),
  );
}

/** Gets the decoder for {@link Holder} account data. */
export function getHolderDecoder(): FixedSizeDecoder<Holder> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["player", getAddressDecoder()],
    ["skt", getU64Decoder()],
    ["accAt", getU128Decoder()],
    ["unclaimed", getU64Decoder()],
    ["claimed", getU64Decoder()],
    ["net", getI64Decoder()],
    ["worst", getU64Decoder()],
    ["bump", getU8Decoder()],
    ["reserved", fixDecoderSize(getBytesDecoder(), 32)],
  ]);
}

/** Gets the codec for {@link Holder} account data. */
export function getHolderCodec(): FixedSizeCodec<HolderArgs, Holder> {
  return combineCodec(getHolderEncoder(), getHolderDecoder());
}

export function decodeHolder<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>,
): Account<Holder, TAddress>;
export function decodeHolder<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>,
): MaybeAccount<Holder, TAddress>;
export function decodeHolder<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>,
): Account<Holder, TAddress> | MaybeAccount<Holder, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getHolderDecoder(),
  );
}

export async function fetchHolder<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<Account<Holder, TAddress>> {
  const maybeAccount = await fetchMaybeHolder(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeHolder<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<MaybeAccount<Holder, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeHolder(maybeAccount);
}

export async function fetchAllHolder(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<Account<Holder>[]> {
  const maybeAccounts = await fetchAllMaybeHolder(rpc, addresses, config);
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeHolder(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<MaybeAccount<Holder>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodeHolder(maybeAccount));
}

export function getHolderSize(): number {
  return 129;
}
