/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU128Decoder,
  getU128Encoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Account,
  type Address,
  type EncodedAccount,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from "@solana/kit";

export const POOL_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([
  241, 154, 109, 4, 17, 177, 109, 188,
]);

export function getPoolDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(POOL_DISCRIMINATOR);
}

export type Pool = {
  discriminator: ReadonlyUint8Array;
  /** USDC backing live stakes and paying hits, e6. */
  pool: bigint;
  /** Fees taken and not yet collected, e6. */
  fees: bigint;
  /** An IOU share's value at `iou_time_at`, x1e18, rising by `iou_rate` every second. */
  iouIndexAt: bigint;
  iouRate: bigint;
  iouTimeAt: bigint;
  /** Every share outstanding, the house's included. */
  iouShares: bigint;
  /**
   * What the house was owed in fees the pool could not pay at once. No longer added to: the house's cut is taken
   * only from what the pool has left. Kept, for what an earlier version issued, and for the account's layout.
   */
  houseShares: bigint;
  houseBasis: bigint;
  bump: number;
};

export type PoolArgs = {
  /** USDC backing live stakes and paying hits, e6. */
  pool: number | bigint;
  /** Fees taken and not yet collected, e6. */
  fees: number | bigint;
  /** An IOU share's value at `iou_time_at`, x1e18, rising by `iou_rate` every second. */
  iouIndexAt: number | bigint;
  iouRate: number | bigint;
  iouTimeAt: number | bigint;
  /** Every share outstanding, the house's included. */
  iouShares: number | bigint;
  /**
   * What the house was owed in fees the pool could not pay at once. No longer added to: the house's cut is taken
   * only from what the pool has left. Kept, for what an earlier version issued, and for the account's layout.
   */
  houseShares: number | bigint;
  houseBasis: number | bigint;
  bump: number;
};

/** Gets the encoder for {@link PoolArgs} account data. */
export function getPoolEncoder(): FixedSizeEncoder<PoolArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["pool", getU64Encoder()],
      ["fees", getU64Encoder()],
      ["iouIndexAt", getU128Encoder()],
      ["iouRate", getU64Encoder()],
      ["iouTimeAt", getI64Encoder()],
      ["iouShares", getU128Encoder()],
      ["houseShares", getU128Encoder()],
      ["houseBasis", getU64Encoder()],
      ["bump", getU8Encoder()],
    ]),
    (value) => ({ ...value, discriminator: POOL_DISCRIMINATOR }),
  );
}

/** Gets the decoder for {@link Pool} account data. */
export function getPoolDecoder(): FixedSizeDecoder<Pool> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["pool", getU64Decoder()],
    ["fees", getU64Decoder()],
    ["iouIndexAt", getU128Decoder()],
    ["iouRate", getU64Decoder()],
    ["iouTimeAt", getI64Decoder()],
    ["iouShares", getU128Decoder()],
    ["houseShares", getU128Decoder()],
    ["houseBasis", getU64Decoder()],
    ["bump", getU8Decoder()],
  ]);
}

/** Gets the codec for {@link Pool} account data. */
export function getPoolCodec(): FixedSizeCodec<PoolArgs, Pool> {
  return combineCodec(getPoolEncoder(), getPoolDecoder());
}

export function decodePool<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>,
): Account<Pool, TAddress>;
export function decodePool<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>,
): MaybeAccount<Pool, TAddress>;
export function decodePool<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>,
): Account<Pool, TAddress> | MaybeAccount<Pool, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getPoolDecoder(),
  );
}

export async function fetchPool<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<Account<Pool, TAddress>> {
  const maybeAccount = await fetchMaybePool(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybePool<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<MaybeAccount<Pool, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodePool(maybeAccount);
}

export async function fetchAllPool(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<Account<Pool>[]> {
  const maybeAccounts = await fetchAllMaybePool(rpc, addresses, config);
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybePool(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<MaybeAccount<Pool>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodePool(maybeAccount));
}

export function getPoolSize(): number {
  return 97;
}
