/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getArrayDecoder,
  getArrayEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU128Decoder,
  getU128Encoder,
  getU32Decoder,
  getU32Encoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Account,
  type Address,
  type EncodedAccount,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from "@solana/kit";
import {
  getRewardsConfigDecoder,
  getRewardsConfigEncoder,
  type RewardsConfig,
  type RewardsConfigArgs,
} from "../types";

export const REWARDS_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([
  12, 223, 68, 101, 63, 33, 38, 101,
]);

export function getRewardsDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(REWARDS_DISCRIMINATOR);
}

export type Rewards = {
  discriminator: ReadonlyUint8Array;
  config: RewardsConfig;
  /** SKT minted, ever, as each mint was worth when it was minted (millionths): the record, not what is held now. */
  supply: bigint;
  /** Every holder's shares, in this era's units: each SKT minted at time t adds 2^((t − era start) / half-life). */
  totalShares: bigint;
  /** USDC e6 each share has earned this era, times `ACC_SCALE`. Back to 0 at each era's start. */
  acc: bigint;
  /** USDC e6 in the vault that is the holders': accrued and not yet claimed, the accumulator's rounding dust with it. */
  holderFunds: bigint;
  /** Every holder share ever accrued, and every claim paid out: `holder_funds` is the one less the other. */
  accruedTotal: bigint;
  claimedTotal: bigint;
  /**
   * The tracked gain, USDC e6: every basis SKT has been minted on since it began, which is what players have lost
   * to the game in expectation. The mint curve reads it.
   */
  gain: bigint;
  /** The era: shares and `acc` are in its units. */
  era: number;
  /** `acc` at the end of each of the last ERAS_KEPT eras, at era % ERAS_KEPT. */
  eraEnds: Array<bigint>;
  /** A share's weight at `anchor_time`, as its log2 times 2^32: under ERA_HALVINGS · 2^32 once caught up. */
  anchorLog2: bigint;
  anchorTime: bigint;
  /**
   * The most every live bet placed since SKT started could pay, gross, every band hitting: what the pool keeps,
   * with the reserve, before any surplus is shared.
   */
  liability: bigint;
  /** Pool surplus shared with holders, ever. */
  sweptTotal: bigint;
  /**
   * When SKT started: no surplus is shared until every bet placed before then, whose liability is not counted, is
   * decided or given back.
   */
  startedAt: bigint;
  bump: number;
  /** Room for what comes later, without a realloc. */
  reserved: ReadonlyUint8Array;
};

export type RewardsArgs = {
  config: RewardsConfigArgs;
  /** SKT minted, ever, as each mint was worth when it was minted (millionths): the record, not what is held now. */
  supply: number | bigint;
  /** Every holder's shares, in this era's units: each SKT minted at time t adds 2^((t − era start) / half-life). */
  totalShares: number | bigint;
  /** USDC e6 each share has earned this era, times `ACC_SCALE`. Back to 0 at each era's start. */
  acc: number | bigint;
  /** USDC e6 in the vault that is the holders': accrued and not yet claimed, the accumulator's rounding dust with it. */
  holderFunds: number | bigint;
  /** Every holder share ever accrued, and every claim paid out: `holder_funds` is the one less the other. */
  accruedTotal: number | bigint;
  claimedTotal: number | bigint;
  /**
   * The tracked gain, USDC e6: every basis SKT has been minted on since it began, which is what players have lost
   * to the game in expectation. The mint curve reads it.
   */
  gain: number | bigint;
  /** The era: shares and `acc` are in its units. */
  era: number;
  /** `acc` at the end of each of the last ERAS_KEPT eras, at era % ERAS_KEPT. */
  eraEnds: Array<number | bigint>;
  /** A share's weight at `anchor_time`, as its log2 times 2^32: under ERA_HALVINGS · 2^32 once caught up. */
  anchorLog2: number | bigint;
  anchorTime: number | bigint;
  /**
   * The most every live bet placed since SKT started could pay, gross, every band hitting: what the pool keeps,
   * with the reserve, before any surplus is shared.
   */
  liability: number | bigint;
  /** Pool surplus shared with holders, ever. */
  sweptTotal: number | bigint;
  /**
   * When SKT started: no surplus is shared until every bet placed before then, whose liability is not counted, is
   * decided or given back.
   */
  startedAt: number | bigint;
  bump: number;
  /** Room for what comes later, without a realloc. */
  reserved: ReadonlyUint8Array;
};

/** Gets the encoder for {@link RewardsArgs} account data. */
export function getRewardsEncoder(): FixedSizeEncoder<RewardsArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["config", getRewardsConfigEncoder()],
      ["supply", getU64Encoder()],
      ["totalShares", getU128Encoder()],
      ["acc", getU128Encoder()],
      ["holderFunds", getU64Encoder()],
      ["accruedTotal", getU64Encoder()],
      ["claimedTotal", getU64Encoder()],
      ["gain", getU64Encoder()],
      ["era", getU32Encoder()],
      ["eraEnds", getArrayEncoder(getU128Encoder(), { size: 8 })],
      ["anchorLog2", getU64Encoder()],
      ["anchorTime", getI64Encoder()],
      ["liability", getU64Encoder()],
      ["sweptTotal", getU64Encoder()],
      ["startedAt", getI64Encoder()],
      ["bump", getU8Encoder()],
      ["reserved", fixEncoderSize(getBytesEncoder(), 32)],
    ]),
    (value) => ({ ...value, discriminator: REWARDS_DISCRIMINATOR }),
  );
}

/** Gets the decoder for {@link Rewards} account data. */
export function getRewardsDecoder(): FixedSizeDecoder<Rewards> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["config", getRewardsConfigDecoder()],
    ["supply", getU64Decoder()],
    ["totalShares", getU128Decoder()],
    ["acc", getU128Decoder()],
    ["holderFunds", getU64Decoder()],
    ["accruedTotal", getU64Decoder()],
    ["claimedTotal", getU64Decoder()],
    ["gain", getU64Decoder()],
    ["era", getU32Decoder()],
    ["eraEnds", getArrayDecoder(getU128Decoder(), { size: 8 })],
    ["anchorLog2", getU64Decoder()],
    ["anchorTime", getI64Decoder()],
    ["liability", getU64Decoder()],
    ["sweptTotal", getU64Decoder()],
    ["startedAt", getI64Decoder()],
    ["bump", getU8Decoder()],
    ["reserved", fixDecoderSize(getBytesDecoder(), 32)],
  ]);
}

/** Gets the codec for {@link Rewards} account data. */
export function getRewardsCodec(): FixedSizeCodec<RewardsArgs, Rewards> {
  return combineCodec(getRewardsEncoder(), getRewardsDecoder());
}

export function decodeRewards<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>,
): Account<Rewards, TAddress>;
export function decodeRewards<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>,
): MaybeAccount<Rewards, TAddress>;
export function decodeRewards<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>,
): Account<Rewards, TAddress> | MaybeAccount<Rewards, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getRewardsDecoder(),
  );
}

export async function fetchRewards<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<Account<Rewards, TAddress>> {
  const maybeAccount = await fetchMaybeRewards(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeRewards<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<MaybeAccount<Rewards, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeRewards(maybeAccount);
}

export async function fetchAllRewards(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<Account<Rewards>[]> {
  const maybeAccounts = await fetchAllMaybeRewards(rpc, addresses, config);
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeRewards(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<MaybeAccount<Rewards>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodeRewards(maybeAccount));
}

export function getRewardsSize(): number {
  return 319;
}
