// SPDX-License-Identifier: MIT
// Generated by packages/contracts/conformance/generate.ts from vectors.json. Do not edit.
pragma solidity ^0.8.24;

import {ConformanceRunner} from "./Conformance.t.sol";

contract ConformanceCases is ConformanceRunner {
    /// a hit, then a miss, and the bet is done
    function test_case_0() public {
        begin(51, 200, 1000, 8300000000000, 20000000, 10000000, 5000000, 0, 0);
        // "p"
        clearPiece();
        addSection(1, 415000, 5, 50000, 500000000);
        addSection(2, 416000, 5, 50000, 500000000);
        place("p", 0, 100000, 51, 0, -400, 100);
        clearExpected();
        expectBand(1, 8300000000000, 8300100000000, 50000, 150);
        expectBand(2, 8320000000000, 8320100000000, 50000, 150);
        checkPlaced("p", 0, 100000, 2000);
        checkState(9900000, 0, 4900000, 0, 98000, 2000, 0, 0, 0);
        barAt(1, 8300000000000, 8300050000000, 8299980000000, 8300010000000);
        expectSettled("p", 1, 0, 72500, 0);
        settleAdd("p");
        settle();
        checkState(9972500, 0, 4900000, 0, 23000, 4500, 0, 0, 0);
        barAt(2, 8300010000000, 8300020000000, 8299900000000, 8300000000000);
        expectSettled("p", 0, 2, 0, 0);
        settleAdd("p");
        settle();
        checkState(9972500, 0, 4900000, 0, 23000, 4500, 0, 0, 0);
    }

    /// the ladder across difficulties and chances
    function test_case_1() public {
        begin(0, 200, 1000, 8300000000000, 20000000, 10000000, 5000000, 0, 0);
        // "p"
        clearPiece();
        addSection(1, 415000, 5, 10000, 1000000000);
        addSection(2, 415000, 5, 10000, 900000000);
        addSection(3, 415000, 5, 10000, 333333333);
        addSection(4, 415000, 5, 10000, 50000000);
        addSection(5, 415000, 5, 10000, 7812500);
        addSection(6, 415000, 5, 10000, 1000000);
        place("p", 0, 1000000, 0, 0, -400, 100);
        clearExpected();
        expectBand(1, 8300000000000, 8300100000000, 10000, 110);
        expectBand(2, 8300000000000, 8300100000000, 10000, 110);
        expectBand(3, 8300000000000, 8300100000000, 10000, 300);
        expectBand(4, 8300000000000, 8300100000000, 10000, 2400);
        expectBand(5, 8300000000000, 8300100000000, 10000, 12800);
        expectBand(6, 8300000000000, 8300100000000, 10000, 12800);
        checkPlaced("p", 0, 60000, 1200);
        checkState(9940000, 0, 4940000, 0, 58800, 1200, 0, 0, 0);
    }

    /// difficulty 100: the floor eases to 1x
    function test_case_2() public {
        begin(100, 200, 1000, 8300000000000, 20000000, 10000000, 5000000, 0, 0);
        // "p"
        clearPiece();
        addSection(1, 415000, 5, 20000, 950000000);
        addSection(2, 415000, 5, 20000, 20000000);
        place("p", 0, 100000, 100, 0, -400, 100);
        clearExpected();
        expectBand(1, 8300000000000, 8300100000000, 20000, 100);
        expectBand(2, 8300000000000, 8300100000000, 20000, 3200);
        checkPlaced("p", 0, 40000, 800);
        checkState(9960000, 0, 4960000, 0, 39200, 800, 0, 0, 0);
    }

    /// momentum takes its margin off the side the price moved toward only
    function test_case_3() public {
        begin(51, 200, 1000, 8300000000000, 20000000, 10000000, 5000000, 0, 0);
        // "p"
        clearPiece();
        addSection(3, 415040, 5, 20000, 123700000);
        addSection(3, 414955, 5, 20000, 123700000);
        place("p", 0, 100000, 51, 1500000, -400, 100);
        clearExpected();
        expectBand(3, 8300800000000, 8300900000000, 20000, 600);
        expectBand(3, 8299100000000, 8299200000000, 20000, 800);
        checkPlaced("p", 0, 40000, 800);
        checkState(9960000, 0, 4960000, 0, 39200, 800, 0, 0, 0);
        // "q"
        clearPiece();
        addSection(3, 414955, 5, 20000, 123700000);
        addSection(3, 415040, 5, 20000, 123700000);
        place("q", 0, 100000, 51, -3000000, -400, 100);
        clearExpected();
        expectBand(3, 8299100000000, 8299200000000, 20000, 600);
        expectBand(3, 8300800000000, 8300900000000, 20000, 800);
        checkPlaced("q", 0, 40000, 800);
        checkState(9920000, 0, 4920000, 0, 78400, 1600, 0, 0, 0);
    }

    /// a big band stakes only what 256 dots pay for; the rest is refunded
    function test_case_4() public {
        begin(51, 200, 1000, 8300000000000, 20000000, 10000000, 5000000, 0, 0);
        // "p"
        clearPiece();
        addSection(1, 415000, 5, 4000000, 10000000);
        place("p", 0, 10000, 51, 0, -400, 100);
        clearExpected();
        expectBand(1, 8300000000000, 8300100000000, 26666, 9600);
        checkPlaced("p", 0, 26666, 533);
        checkState(9973334, 0, 4973334, 0, 26133, 533, 0, 0, 0);
    }

    /// a band with no chance is not offered; the rest goes in
    function test_case_5() public {
        begin(51, 200, 1000, 8300000000000, 20000000, 10000000, 5000000, 0, 0);
        // "p"
        clearPiece();
        addSection(1, 415000, 5, 50000, 0);
        addSection(2, 415000, 5, 50000, 400000000);
        place("p", 0, 100000, 51, 0, -400, 100);
        clearExpected();
        expectBand(2, 8300000000000, 8300100000000, 50000, 200);
        checkPlaced("p", 0, 50000, 1000);
        checkState(9950000, 0, 4950000, 0, 49000, 1000, 0, 0, 0);
        // "q"
        clearPiece();
        addSection(1, 415000, 5, 50000, 0);
        place("q", 0, 100000, 51, 0, -400, 100);
        checkRefused("NotOffered");
        checkState(9950000, 0, 4950000, 0, 49000, 1000, 0, 0, 0);
    }

    /// a band whose second is already posted is not offered
    function test_case_6() public {
        begin(51, 200, 1000, 8300000000000, 20000000, 10000000, 5000000, 0, 0);
        barAt(1, 8300000000000, 8300000000000, 8300000000000, 8300000000000);
        settle();
        checkState(10000000, 0, 5000000, 0, 0, 0, 0, 0, 0);
        // "p"
        clearPiece();
        addSection(1, 415000, 5, 50000, 500000000);
        addSection(2, 415000, 5, 50000, 500000000);
        place("p", 0, 100000, 51, 0, -400, 100);
        clearExpected();
        expectBand(2, 8300000000000, 8300100000000, 50000, 150);
        checkPlaced("p", 0, 50000, 1000);
        checkState(9950000, 0, 4950000, 0, 49000, 1000, 0, 0, 0);
    }

    /// bands are judged one unit wider each way, inclusive
    function test_case_7() public {
        begin(51, 200, 1000, 8300000000000, 20000000, 10000000, 5000000, 0, 0);
        // "p"
        clearPiece();
        addSection(1, 415010, 5, 30000, 200000000);
        addSection(1, 415012, 5, 30000, 200000000);
        addSection(1, 414985, 5, 30000, 200000000);
        addSection(1, 414983, 5, 30000, 200000000);
        place("p", 0, 100000, 51, 0, -400, 100);
        clearExpected();
        expectBand(1, 8300200000000, 8300300000000, 30000, 400);
        expectBand(1, 8300240000000, 8300340000000, 30000, 400);
        expectBand(1, 8299700000000, 8299800000000, 30000, 400);
        expectBand(1, 8299660000000, 8299760000000, 30000, 400);
        checkPlaced("p", 0, 120000, 2400);
        checkState(9880000, 0, 4880000, 0, 117600, 2400, 0, 0, 0);
        barAt(1, 8300000000000, 8300180000000, 8299820000000, 8300000000000);
        expectSettled("p", 5, 10, 117600, 104400);
        settleAdd("p");
        settle();
        checkState(9997600, 0, 4880000, 0, 0, 2400, 104400, 0, 18000);
    }

    /// the previous close counts: a jump across the ink crosses it
    function test_case_8() public {
        begin(51, 200, 1000, 8300000000000, 20000000, 10000000, 5000000, 0, 0);
        // "p"
        clearPiece();
        addSection(2, 415020, 5, 40000, 150000000);
        place("p", 0, 100000, 51, 0, -400, 100);
        clearExpected();
        expectBand(2, 8300400000000, 8300500000000, 40000, 600);
        checkPlaced("p", 0, 40000, 800);
        checkState(9960000, 0, 4960000, 0, 39200, 800, 0, 0, 0);
        barAt(1, 8300600000000, 8300600000000, 8300600000000, 8300600000000);
        settle();
        checkState(9960000, 0, 4960000, 0, 39200, 800, 0, 0, 0);
        barAt(2, 8300600000000, 8299900000000, 8299800000000, 8299800000000);
        expectSettled("p", 1, 0, 39200, 180800);
        settleAdd("p");
        settle();
        checkState(9999200, 0, 4960000, 0, 0, 800, 180800, 0, 20000);
    }

    /// a win the pool cannot pay is owed, and so is the house's cut
    function test_case_9() public {
        begin(51, 200, 1000, 8300000000000, 20000000, 10000000, 5000000, 0, 0);
        // "p"
        clearPiece();
        addSection(1, 415000, 5, 50000, 10000000);
        place("p", 0, 100000, 51, 0, -400, 100);
        clearExpected();
        expectBand(1, 8300000000000, 8300100000000, 50000, 9600);
        checkPlaced("p", 0, 50000, 1000);
        checkState(9950000, 0, 4950000, 0, 49000, 1000, 0, 0, 0);
        barAt(1, 8300000000000, 8300050000000, 8300000000000, 8300000000000);
        expectSettled("p", 1, 0, 49000, 4276000);
        settleAdd("p");
        settle();
        checkState(9999000, 0, 4950000, 0, 0, 1000, 4276000, 0, 475000);
    }

    /// another player's losses are what pays a winner
    function test_case_10() public {
        begin(51, 200, 1000, 8300000000000, 20000000, 10000000, 5000000, 30000000, 25000000);
        // "loser"
        clearPiece();
        addSection(1, 420000, 5, 20000000, 900000000);
        place("loser", 1, 1000000, 51, 0, -400, 100);
        clearExpected();
        expectBand(1, 8400000000000, 8400100000000, 20000000, 110);
        checkPlaced("loser", 1, 20000000, 400000);
        checkState(10000000, 10000000, 5000000, 5000000, 19600000, 400000, 0, 0, 0);
        // "winner"
        clearPiece();
        addSection(1, 415000, 5, 50000, 10000000);
        place("winner", 0, 100000, 51, 0, -400, 100);
        clearExpected();
        expectBand(1, 8300000000000, 8300100000000, 50000, 9600);
        checkPlaced("winner", 0, 50000, 1000);
        checkState(9950000, 10000000, 4950000, 5000000, 19649000, 401000, 0, 0, 0);
        barAt(1, 8300000000000, 8300050000000, 8300000000000, 8300000000000);
        expectSettled("loser", 0, 1, 0, 0);
        expectSettled("winner", 1, 0, 4325000, 0);
        settleAdd("loser");
        settleAdd("winner");
        settle();
        checkState(14275000, 10000000, 4950000, 5000000, 14849000, 876000, 0, 0, 0);
    }

    /// fees at their bounds
    function test_case_11() public {
        begin(51, 2000, 5000, 8300000000000, 20000000, 10000000, 5000000, 0, 0);
        // "p"
        clearPiece();
        addSection(1, 415000, 5, 99999, 250000000);
        place("p", 0, 100000, 51, 0, -400, 100);
        clearExpected();
        expectBand(1, 8300000000000, 8300100000000, 99999, 300);
        checkPlaced("p", 0, 99999, 19999);
        checkState(9900001, 0, 4900001, 0, 80000, 19999, 0, 0, 0);
        barAt(1, 8300000000000, 8300030000000, 8300000000000, 8300000000000);
        expectSettled("p", 1, 0, 80000, 119998);
        settleAdd("p");
        settle();
        checkState(9980001, 0, 4900001, 0, 0, 19999, 119998, 0, 99999);
    }

    /// refusals, and nothing moves for them
    function test_case_12() public {
        begin(51, 200, 1000, 8300000000000, 20000000, 10000000, 5000000, 0, 0);
        // "difficulty"
        clearPiece();
        addSection(1, 415000, 5, 50000, 500000000);
        place("difficulty", 0, 100000, 60, 0, -400, 100);
        checkRefused("Difficulty");
        checkState(10000000, 0, 5000000, 0, 0, 0, 0, 0, 0);
        // "late"
        clearPiece();
        addSection(1, 415000, 5, 50000, 500000000);
        place("late", 0, 100000, 51, 0, 201, 100);
        checkRefused("Late");
        checkState(10000000, 0, 5000000, 0, 0, 0, 0, 0, 0);
        // "stale"
        clearPiece();
        addSection(1, 415000, 5, 50000, 500000000);
        place("stale", 0, 100000, 51, 0, -400, 15001);
        checkRefused("StalePrice");
        checkState(10000000, 0, 5000000, 0, 0, 0, 0, 0, 0);
        // "horizon"
        clearPiece();
        addSection(31, 415000, 5, 50000, 500000000);
        place("horizon", 0, 100000, 51, 0, -400, 100);
        checkRefused("Sections");
        checkState(10000000, 0, 5000000, 0, 0, 0, 0, 0, 0);
        // "perdot"
        clearPiece();
        addSection(1, 415000, 5, 50000, 500000000);
        place("perdot", 0, 5000, 51, 0, -400, 100);
        checkRefused("PerDot");
        checkState(10000000, 0, 5000000, 0, 0, 0, 0, 0, 0);
        // "allowance"
        clearPiece();
        addSection(1, 415000, 5, 5000001, 500000000);
        place("allowance", 0, 1000000, 51, 0, -400, 100);
        checkRefused("Allowance");
        checkState(10000000, 0, 5000000, 0, 0, 0, 0, 0, 0);
        // "ok"
        clearPiece();
        addSection(1, 415000, 5, 50000, 500000000);
        place("ok", 0, 100000, 51, 0, -400, 100);
        clearExpected();
        expectBand(1, 8300000000000, 8300100000000, 50000, 150);
        checkPlaced("ok", 0, 50000, 1000);
        checkState(9950000, 0, 4950000, 0, 49000, 1000, 0, 0, 0);
        // "ok"
        clearPiece();
        addSection(1, 415000, 5, 50000, 500000000);
        place("ok", 0, 100000, 51, 0, -400, 100);
        checkRefused("Replay");
        checkState(9950000, 0, 4950000, 0, 49000, 1000, 0, 0, 0);
    }

    /// more than the balance is refused
    function test_case_13() public {
        begin(51, 200, 1000, 8300000000000, 20000000, 40000, 5000000, 0, 0);
        // "p"
        clearPiece();
        addSection(1, 415000, 5, 50000, 500000000);
        place("p", 0, 100000, 51, 0, -400, 100);
        checkRefused("Balance");
        checkState(40000, 0, 5000000, 0, 0, 0, 0, 0, 0);
    }

}
