/**
 * Writes what every conformance case must do, step by step, to `vectors.json`, from the reference model; and the
 * Solidity that replays it against SkechGame (`evm/test/ConformanceCases.sol`), so both chains run the same file.
 *
 *   bun packages/contracts/conformance/generate.ts          (from the repo root)
 *   bun packages/contracts/conformance/generate.ts --check  (fails if either file is out of date)
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { CASES } from "./cases";
import { DEFAULT_PER_DOT, LATE_MS, MAX_PER_DOT, MAX_PIECE_STAKE, MAX_PRICE_AGE_MS, MIN_PER_DOT, run } from "./reference";

const here = import.meta.dir;
const vectors = {
  about: "Generated by packages/contracts/conformance/generate.ts from cases.ts and reference.ts. Do not edit.",
  config: { lateMs: LATE_MS, maxPriceAgeMs: MAX_PRICE_AGE_MS, minPerDot: MIN_PER_DOT, maxPerDot: MAX_PER_DOT, maxPieceStake: MAX_PIECE_STAKE, defaultPerDot: DEFAULT_PER_DOT },
  cases: CASES.map((c) => ({ ...c, expect: run(c) })),
};
const json = JSON.stringify(vectors, null, 2) + "\n";

/* ---- the Solidity: one test per case, every step and every expected number as literals ---- */

const u = (n: number) => String(n);
const lines: string[] = [];
lines.push("// SPDX-License-Identifier: MIT");
lines.push("// Generated by packages/contracts/conformance/generate.ts from vectors.json. Do not edit.");
lines.push("pragma solidity ^0.8.24;");
lines.push("");
lines.push('import {ConformanceRunner} from "./Conformance.t.sol";');
lines.push("");
lines.push("contract ConformanceCases is ConformanceRunner {");
vectors.cases.forEach((c, ci) => {
  lines.push(`    /// ${c.name}`);
  lines.push(`    function test_case_${ci}() public {`);
  const b = c.players.b;
  lines.push(`        begin(${c.difficulty}, ${c.feeBps}, ${c.profitFeeBps}, ${u(c.price)}, ${u(c.unit)}, ${c.players.a.deposit}, ${c.players.a.allowance}, ${b ? b.deposit : 0}, ${b ? b.allowance : 0});`);
  c.steps.forEach((step, si) => {
    const e = c.expect[si];
    if ("difficulty" in step) {
      lines.push(`        setDifficulty(${step.difficulty}, ${e.difficulty!.ok});`);
    } else if ("place" in step) {
      const s = step.place;
      lines.push(`        // ${JSON.stringify(s.id)}`);
      lines.push(`        clearPiece();`);
      for (const x of s.sections) lines.push(`        addSection(${x.second}, ${x.lo}, ${x.width}, ${x.stake}, ${x.chance});`);
      const p = e.place!;
      lines.push(`        place("${s.id}", ${s.player === "b" ? 1 : 0}, ${s.perDot ?? DEFAULT_PER_DOT}, ${s.difficulty ?? c.difficulty}, ${s.momentum ?? 0}, ${s.received ?? -400}, ${s.priceAge ?? 100});`);
      if (p.ok) {
        lines.push(`        clearExpected();`);
        for (const x of p.sections) lines.push(`        expectBand(${x.second}, ${u(x.lo)}, ${u(x.hi)}, ${x.stake}, ${x.rung});`);
        lines.push(`        checkPlaced("${s.id}", ${s.player === "b" ? 1 : 0}, ${p.staked}, ${p.fee});`);
      } else lines.push(`        checkRefused("${p.refused}");`);
    } else {
      const bar = step.bar;
      lines.push(`        barAt(${bar.second}, ${u(bar.prevClose)}, ${u(bar.high)}, ${u(bar.low)}, ${u(bar.close)});`);
      for (const s of e.settled ?? []) lines.push(`        expectSettled("${s.id}", ${s.hitMask}, ${s.missMask}, ${s.paid}, ${s.owed});`);
      for (const id of bar.settle) lines.push(`        settleAdd("${id}");`);
      lines.push(`        settle();`);
    }
    const st = e.state;
    lines.push(`        checkState(${st.balance.a}, ${st.balance.b ?? 0}, ${st.allowance.a}, ${st.allowance.b ?? 0}, ${st.pool}, ${st.fees}, ${st.owed.a}, ${st.owed.b ?? 0}, ${st.houseOwed});`);
  });
  lines.push("    }");
  lines.push("");
});
lines.push("}");
const sol = lines.join("\n") + "\n";

const files: [string, string][] = [
  [join(here, "vectors.json"), json],
  [join(here, "..", "evm", "test", "ConformanceCases.sol"), sol],
];
if (process.argv.includes("--check")) {
  const stale = files.filter(([p, body]) => {
    try {
      return readFileSync(p, "utf8") !== body;
    } catch {
      return true;
    }
  });
  if (stale.length) {
    console.error(`out of date: ${stale.map(([p]) => p).join(", ")}; run bun packages/contracts/conformance/generate.ts`);
    process.exit(1);
  }
  console.log("conformance vectors are up to date");
} else {
  for (const [p, body] of files) writeFileSync(p, body);
  console.log(`${vectors.cases.length} cases, ${vectors.cases.reduce((n, c) => n + c.steps.length, 0)} steps`);
}
