[toolchain]
anchor_version = "0.32.1"
package_manager = "bun"

[features]
resolution = true
skip-lint = false

[programs.localnet]
skech = "2k9WY5YR357AGVVoBW6ouFHijEypTj8953fzSdD7HfRV"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
