/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type WritableAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  getAddressFromResolvedInstructionAccount,
  type InstructionAccountInput,
  type InstructionAccountInputAddress,
  type InstructionSignerInput,
  type ResolvedInstructionAccount,
  type ResolvedInstructionAccountMeta,
} from "@solana/kit/program-client-core";
import {
  findGamePda,
  findHolderPda,
  findPlayerPda,
  findRewardsPda,
} from "../pdas";
import { SKECH_PROGRAM_ADDRESS } from "../programs";

export const CLAIM_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([
  62, 198, 214, 193, 213, 159, 108, 210,
]);

export function getClaimDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(CLAIM_DISCRIMINATOR);
}

export type ClaimInstruction<
  TProgram extends string = typeof SKECH_PROGRAM_ADDRESS,
  TAccountAuthority extends string | AccountMeta<string> = string,
  TAccountGame extends string | AccountMeta<string> = string,
  TAccountRewards extends string | AccountMeta<string> = string,
  TAccountPlayer extends string | AccountMeta<string> = string,
  TAccountHolder extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountAuthority extends string
        ? ReadonlySignerAccount<TAccountAuthority> &
            AccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      TAccountGame extends string
        ? ReadonlyAccount<TAccountGame>
        : TAccountGame,
      TAccountRewards extends string
        ? WritableAccount<TAccountRewards>
        : TAccountRewards,
      TAccountPlayer extends string
        ? WritableAccount<TAccountPlayer>
        : TAccountPlayer,
      TAccountHolder extends string
        ? WritableAccount<TAccountHolder>
        : TAccountHolder,
      ...TRemainingAccounts,
    ]
  >;

export type ClaimInstructionData = { discriminator: ReadonlyUint8Array };

export type ClaimInstructionDataArgs = {};

export function getClaimInstructionDataEncoder(): FixedSizeEncoder<ClaimInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([["discriminator", fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({ ...value, discriminator: CLAIM_DISCRIMINATOR }),
  );
}

export function getClaimInstructionDataDecoder(): FixedSizeDecoder<ClaimInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getClaimInstructionDataCodec(): FixedSizeCodec<
  ClaimInstructionDataArgs,
  ClaimInstructionData
> {
  return combineCodec(
    getClaimInstructionDataEncoder(),
    getClaimInstructionDataDecoder(),
  );
}

export type ClaimAsyncInput<
  TAccountAuthority extends InstructionSignerInput = InstructionSignerInput,
  TAccountGame extends InstructionAccountInput = InstructionAccountInput,
  TAccountRewards extends InstructionAccountInput = InstructionAccountInput,
  TAccountPlayer extends InstructionAccountInput = InstructionAccountInput,
  TAccountHolder extends InstructionAccountInput = InstructionAccountInput,
> = {
  authority: TAccountAuthority;
  game?: TAccountGame;
  rewards?: TAccountRewards;
  player?: TAccountPlayer;
  holder?: TAccountHolder;
};

export async function getClaimInstructionAsync<
  TAccountAuthority extends InstructionSignerInput,
  TAccountGame extends InstructionAccountInput,
  TAccountRewards extends InstructionAccountInput,
  TAccountPlayer extends InstructionAccountInput,
  TAccountHolder extends InstructionAccountInput,
  TProgramAddress extends Address = typeof SKECH_PROGRAM_ADDRESS,
>(
  input: ClaimAsyncInput<
    TAccountAuthority,
    TAccountGame,
    TAccountRewards,
    TAccountPlayer,
    TAccountHolder
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  ClaimInstruction<
    TProgramAddress,
    ResolvedInstructionAccountMeta<
      TAccountAuthority,
      InstructionAccountInputAddress<TAccountAuthority>
    >,
    ResolvedInstructionAccountMeta<
      TAccountGame,
      InstructionAccountInputAddress<TAccountGame>
    >,
    ResolvedInstructionAccountMeta<
      TAccountRewards,
      InstructionAccountInputAddress<TAccountRewards>
    >,
    ResolvedInstructionAccountMeta<
      TAccountPlayer,
      InstructionAccountInputAddress<TAccountPlayer>
    >,
    ResolvedInstructionAccountMeta<
      TAccountHolder,
      InstructionAccountInputAddress<TAccountHolder>
    >
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? SKECH_PROGRAM_ADDRESS;

  // Account meta helper.
  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");

  // Original accounts.
  const originalAccounts = {
    authority: {
      value: input.authority ?? null,
      isSigner: true,
      isWritable: false,
    },
    game: { value: input.game ?? null, isSigner: false, isWritable: false },
    rewards: {
      value: input.rewards ?? null,
      isSigner: false,
      isWritable: true,
    },
    player: { value: input.player ?? null, isSigner: false, isWritable: true },
    holder: { value: input.holder ?? null, isSigner: false, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Resolve default values.
  if (!accounts.game.value) {
    accounts.game.value = await findGamePda({ programAddress });
  }
  if (!accounts.rewards.value) {
    accounts.rewards.value = await findRewardsPda({ programAddress });
  }
  if (!accounts.player.value) {
    accounts.player.value = await findPlayerPda(
      {
        authority: getAddressFromResolvedInstructionAccount(
          "authority",
          accounts.authority.value,
        ),
      },
      { programAddress },
    );
  }
  if (!accounts.holder.value) {
    accounts.holder.value = await findHolderPda(
      {
        authority: getAddressFromResolvedInstructionAccount(
          "authority",
          accounts.authority.value,
        ),
      },
      { programAddress },
    );
  }

  return Object.freeze({
    accounts: [
      getAccountMeta("authority", accounts.authority),
      getAccountMeta("game", accounts.game),
      getAccountMeta("rewards", accounts.rewards),
      getAccountMeta("player", accounts.player),
      getAccountMeta("holder", accounts.holder),
    ],
    data: getClaimInstructionDataEncoder().encode({}),
    programAddress,
  } as ClaimInstruction<
    TProgramAddress,
    ResolvedInstructionAccountMeta<
      TAccountAuthority,
      InstructionAccountInputAddress<TAccountAuthority>
    >,
    ResolvedInstructionAccountMeta<
      TAccountGame,
      InstructionAccountInputAddress<TAccountGame>
    >,
    ResolvedInstructionAccountMeta<
      TAccountRewards,
      InstructionAccountInputAddress<TAccountRewards>
    >,
    ResolvedInstructionAccountMeta<
      TAccountPlayer,
      InstructionAccountInputAddress<TAccountPlayer>
    >,
    ResolvedInstructionAccountMeta<
      TAccountHolder,
      InstructionAccountInputAddress<TAccountHolder>
    >
  >);
}

export type ClaimInput<
  TAccountAuthority extends InstructionSignerInput = InstructionSignerInput,
  TAccountGame extends InstructionAccountInput = InstructionAccountInput,
  TAccountRewards extends InstructionAccountInput = InstructionAccountInput,
  TAccountPlayer extends InstructionAccountInput = InstructionAccountInput,
  TAccountHolder extends InstructionAccountInput = InstructionAccountInput,
> = {
  authority: TAccountAuthority;
  game: TAccountGame;
  rewards: TAccountRewards;
  player: TAccountPlayer;
  holder: TAccountHolder;
};

export function getClaimInstruction<
  TAccountAuthority extends InstructionSignerInput,
  TAccountGame extends InstructionAccountInput,
  TAccountRewards extends InstructionAccountInput,
  TAccountPlayer extends InstructionAccountInput,
  TAccountHolder extends InstructionAccountInput,
  TProgramAddress extends Address = typeof SKECH_PROGRAM_ADDRESS,
>(
  input: ClaimInput<
    TAccountAuthority,
    TAccountGame,
    TAccountRewards,
    TAccountPlayer,
    TAccountHolder
  >,
  config?: { programAddress?: TProgramAddress },
): ClaimInstruction<
  TProgramAddress,
  ResolvedInstructionAccountMeta<
    TAccountAuthority,
    InstructionAccountInputAddress<TAccountAuthority>
  >,
  ResolvedInstructionAccountMeta<
    TAccountGame,
    InstructionAccountInputAddress<TAccountGame>
  >,
  ResolvedInstructionAccountMeta<
    TAccountRewards,
    InstructionAccountInputAddress<TAccountRewards>
  >,
  ResolvedInstructionAccountMeta<
    TAccountPlayer,
    InstructionAccountInputAddress<TAccountPlayer>
  >,
  ResolvedInstructionAccountMeta<
    TAccountHolder,
    InstructionAccountInputAddress<TAccountHolder>
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? SKECH_PROGRAM_ADDRESS;

  // Account meta helper.
  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");

  // Original accounts.
  const originalAccounts = {
    authority: {
      value: input.authority ?? null,
      isSigner: true,
      isWritable: false,
    },
    game: { value: input.game ?? null, isSigner: false, isWritable: false },
    rewards: {
      value: input.rewards ?? null,
      isSigner: false,
      isWritable: true,
    },
    player: { value: input.player ?? null, isSigner: false, isWritable: true },
    holder: { value: input.holder ?? null, isSigner: false, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  return Object.freeze({
    accounts: [
      getAccountMeta("authority", accounts.authority),
      getAccountMeta("game", accounts.game),
      getAccountMeta("rewards", accounts.rewards),
      getAccountMeta("player", accounts.player),
      getAccountMeta("holder", accounts.holder),
    ],
    data: getClaimInstructionDataEncoder().encode({}),
    programAddress,
  } as ClaimInstruction<
    TProgramAddress,
    ResolvedInstructionAccountMeta<
      TAccountAuthority,
      InstructionAccountInputAddress<TAccountAuthority>
    >,
    ResolvedInstructionAccountMeta<
      TAccountGame,
      InstructionAccountInputAddress<TAccountGame>
    >,
    ResolvedInstructionAccountMeta<
      TAccountRewards,
      InstructionAccountInputAddress<TAccountRewards>
    >,
    ResolvedInstructionAccountMeta<
      TAccountPlayer,
      InstructionAccountInputAddress<TAccountPlayer>
    >,
    ResolvedInstructionAccountMeta<
      TAccountHolder,
      InstructionAccountInputAddress<TAccountHolder>
    >
  >);
}

export type ParsedClaimInstruction<
  TProgram extends string = typeof SKECH_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    authority: TAccountMetas[0];
    game: TAccountMetas[1];
    rewards: TAccountMetas[2];
    player: TAccountMetas[3];
    holder: TAccountMetas[4];
  };
  data: ClaimInstructionData;
};

export function parseClaimInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedClaimInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 5) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 5,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      authority: getNextAccount(),
      game: getNextAccount(),
      rewards: getNextAccount(),
      player: getNextAccount(),
      holder: getNextAccount(),
    },
    data: getClaimInstructionDataDecoder().decode(instruction.data),
  };
}
