/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  getAddressFromResolvedInstructionAccount,
  type InstructionAccountInput,
  type InstructionAccountInputAddress,
  type InstructionSignerInput,
  type ResolvedInstructionAccount,
  type ResolvedInstructionAccountMeta,
} from "@solana/kit/program-client-core";
import { findGamePda, findPlayerPda } from "../pdas";
import { SKECH_PROGRAM_ADDRESS } from "../programs";

export const DEPOSIT_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([
  242, 35, 198, 137, 82, 225, 242, 182,
]);

export function getDepositDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(DEPOSIT_DISCRIMINATOR);
}

export type DepositInstruction<
  TProgram extends string = typeof SKECH_PROGRAM_ADDRESS,
  TAccountPayer extends string | AccountMeta<string> = string,
  TAccountAuthority extends string | AccountMeta<string> = string,
  TAccountGame extends string | AccountMeta<string> = string,
  TAccountPlayer extends string | AccountMeta<string> = string,
  TAccountFrom extends string | AccountMeta<string> = string,
  TAccountVault extends string | AccountMeta<string> = string,
  TAccountUsdcMint extends string | AccountMeta<string> = string,
  TAccountTokenProgram extends string | AccountMeta<string> =
    "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountPayer extends string
        ? WritableSignerAccount<TAccountPayer> &
            AccountSignerMeta<TAccountPayer>
        : TAccountPayer,
      TAccountAuthority extends string
        ? ReadonlySignerAccount<TAccountAuthority> &
            AccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      TAccountGame extends string
        ? ReadonlyAccount<TAccountGame>
        : TAccountGame,
      TAccountPlayer extends string
        ? WritableAccount<TAccountPlayer>
        : TAccountPlayer,
      TAccountFrom extends string
        ? WritableAccount<TAccountFrom>
        : TAccountFrom,
      TAccountVault extends string
        ? WritableAccount<TAccountVault>
        : TAccountVault,
      TAccountUsdcMint extends string
        ? ReadonlyAccount<TAccountUsdcMint>
        : TAccountUsdcMint,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type DepositInstructionData = {
  discriminator: ReadonlyUint8Array;
  amount: bigint;
};

export type DepositInstructionDataArgs = { amount: number | bigint };

export function getDepositInstructionDataEncoder(): FixedSizeEncoder<DepositInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["amount", getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: DEPOSIT_DISCRIMINATOR }),
  );
}

export function getDepositInstructionDataDecoder(): FixedSizeDecoder<DepositInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["amount", getU64Decoder()],
  ]);
}

export function getDepositInstructionDataCodec(): FixedSizeCodec<
  DepositInstructionDataArgs,
  DepositInstructionData
> {
  return combineCodec(
    getDepositInstructionDataEncoder(),
    getDepositInstructionDataDecoder(),
  );
}

export type DepositAsyncInput<
  TAccountPayer extends InstructionSignerInput = InstructionSignerInput,
  TAccountAuthority extends InstructionSignerInput = InstructionSignerInput,
  TAccountGame extends InstructionAccountInput = InstructionAccountInput,
  TAccountPlayer extends InstructionAccountInput = InstructionAccountInput,
  TAccountFrom extends InstructionAccountInput = InstructionAccountInput,
  TAccountVault extends InstructionAccountInput = InstructionAccountInput,
  TAccountUsdcMint extends InstructionAccountInput = InstructionAccountInput,
  TAccountTokenProgram extends InstructionAccountInput =
    InstructionAccountInput,
  TAccountSystemProgram extends InstructionAccountInput =
    InstructionAccountInput,
> = {
  payer: TAccountPayer;
  authority: TAccountAuthority;
  game?: TAccountGame;
  player?: TAccountPlayer;
  from: TAccountFrom;
  vault: TAccountVault;
  usdcMint: TAccountUsdcMint;
  tokenProgram?: TAccountTokenProgram;
  systemProgram?: TAccountSystemProgram;
  amount: DepositInstructionDataArgs["amount"];
};

export async function getDepositInstructionAsync<
  TAccountPayer extends InstructionSignerInput,
  TAccountAuthority extends InstructionSignerInput,
  TAccountGame extends InstructionAccountInput,
  TAccountPlayer extends InstructionAccountInput,
  TAccountFrom extends InstructionAccountInput,
  TAccountVault extends InstructionAccountInput,
  TAccountUsdcMint extends InstructionAccountInput,
  TAccountTokenProgram extends InstructionAccountInput,
  TAccountSystemProgram extends InstructionAccountInput,
  TProgramAddress extends Address = typeof SKECH_PROGRAM_ADDRESS,
>(
  input: DepositAsyncInput<
    TAccountPayer,
    TAccountAuthority,
    TAccountGame,
    TAccountPlayer,
    TAccountFrom,
    TAccountVault,
    TAccountUsdcMint,
    TAccountTokenProgram,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  DepositInstruction<
    TProgramAddress,
    ResolvedInstructionAccountMeta<
      TAccountPayer,
      InstructionAccountInputAddress<TAccountPayer>
    >,
    ResolvedInstructionAccountMeta<
      TAccountAuthority,
      InstructionAccountInputAddress<TAccountAuthority>
    >,
    ResolvedInstructionAccountMeta<
      TAccountGame,
      InstructionAccountInputAddress<TAccountGame>
    >,
    ResolvedInstructionAccountMeta<
      TAccountPlayer,
      InstructionAccountInputAddress<TAccountPlayer>
    >,
    ResolvedInstructionAccountMeta<
      TAccountFrom,
      InstructionAccountInputAddress<TAccountFrom>
    >,
    ResolvedInstructionAccountMeta<
      TAccountVault,
      InstructionAccountInputAddress<TAccountVault>
    >,
    ResolvedInstructionAccountMeta<
      TAccountUsdcMint,
      InstructionAccountInputAddress<TAccountUsdcMint>
    >,
    ResolvedInstructionAccountMeta<
      TAccountTokenProgram,
      InstructionAccountInputAddress<TAccountTokenProgram>
    >,
    ResolvedInstructionAccountMeta<
      TAccountSystemProgram,
      InstructionAccountInputAddress<TAccountSystemProgram>
    >
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? SKECH_PROGRAM_ADDRESS;

  // Account meta helper.
  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");

  // Original accounts.
  const originalAccounts = {
    payer: { value: input.payer ?? null, isSigner: true, isWritable: true },
    authority: {
      value: input.authority ?? null,
      isSigner: true,
      isWritable: false,
    },
    game: { value: input.game ?? null, isSigner: false, isWritable: false },
    player: { value: input.player ?? null, isSigner: false, isWritable: true },
    from: { value: input.from ?? null, isSigner: false, isWritable: true },
    vault: { value: input.vault ?? null, isSigner: false, isWritable: true },
    usdcMint: {
      value: input.usdcMint ?? null,
      isSigner: false,
      isWritable: false,
    },
    tokenProgram: {
      value: input.tokenProgram ?? null,
      isSigner: false,
      isWritable: false,
    },
    systemProgram: {
      value: input.systemProgram ?? null,
      isSigner: false,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.game.value) {
    accounts.game.value = await findGamePda({ programAddress });
  }
  if (!accounts.player.value) {
    accounts.player.value = await findPlayerPda(
      {
        authority: getAddressFromResolvedInstructionAccount(
          "authority",
          accounts.authority.value,
        ),
      },
      { programAddress },
    );
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  return Object.freeze({
    accounts: [
      getAccountMeta("payer", accounts.payer),
      getAccountMeta("authority", accounts.authority),
      getAccountMeta("game", accounts.game),
      getAccountMeta("player", accounts.player),
      getAccountMeta("from", accounts.from),
      getAccountMeta("vault", accounts.vault),
      getAccountMeta("usdcMint", accounts.usdcMint),
      getAccountMeta("tokenProgram", accounts.tokenProgram),
      getAccountMeta("systemProgram", accounts.systemProgram),
    ],
    data: getDepositInstructionDataEncoder().encode(
      args as DepositInstructionDataArgs,
    ),
    programAddress,
  } as DepositInstruction<
    TProgramAddress,
    ResolvedInstructionAccountMeta<
      TAccountPayer,
      InstructionAccountInputAddress<TAccountPayer>
    >,
    ResolvedInstructionAccountMeta<
      TAccountAuthority,
      InstructionAccountInputAddress<TAccountAuthority>
    >,
    ResolvedInstructionAccountMeta<
      TAccountGame,
      InstructionAccountInputAddress<TAccountGame>
    >,
    ResolvedInstructionAccountMeta<
      TAccountPlayer,
      InstructionAccountInputAddress<TAccountPlayer>
    >,
    ResolvedInstructionAccountMeta<
      TAccountFrom,
      InstructionAccountInputAddress<TAccountFrom>
    >,
    ResolvedInstructionAccountMeta<
      TAccountVault,
      InstructionAccountInputAddress<TAccountVault>
    >,
    ResolvedInstructionAccountMeta<
      TAccountUsdcMint,
      InstructionAccountInputAddress<TAccountUsdcMint>
    >,
    ResolvedInstructionAccountMeta<
      TAccountTokenProgram,
      InstructionAccountInputAddress<TAccountTokenProgram>
    >,
    ResolvedInstructionAccountMeta<
      TAccountSystemProgram,
      InstructionAccountInputAddress<TAccountSystemProgram>
    >
  >);
}

export type DepositInput<
  TAccountPayer extends InstructionSignerInput = InstructionSignerInput,
  TAccountAuthority extends InstructionSignerInput = InstructionSignerInput,
  TAccountGame extends InstructionAccountInput = InstructionAccountInput,
  TAccountPlayer extends InstructionAccountInput = InstructionAccountInput,
  TAccountFrom extends InstructionAccountInput = InstructionAccountInput,
  TAccountVault extends InstructionAccountInput = InstructionAccountInput,
  TAccountUsdcMint extends InstructionAccountInput = InstructionAccountInput,
  TAccountTokenProgram extends InstructionAccountInput =
    InstructionAccountInput,
  TAccountSystemProgram extends InstructionAccountInput =
    InstructionAccountInput,
> = {
  payer: TAccountPayer;
  authority: TAccountAuthority;
  game: TAccountGame;
  player: TAccountPlayer;
  from: TAccountFrom;
  vault: TAccountVault;
  usdcMint: TAccountUsdcMint;
  tokenProgram?: TAccountTokenProgram;
  systemProgram?: TAccountSystemProgram;
  amount: DepositInstructionDataArgs["amount"];
};

export function getDepositInstruction<
  TAccountPayer extends InstructionSignerInput,
  TAccountAuthority extends InstructionSignerInput,
  TAccountGame extends InstructionAccountInput,
  TAccountPlayer extends InstructionAccountInput,
  TAccountFrom extends InstructionAccountInput,
  TAccountVault extends InstructionAccountInput,
  TAccountUsdcMint extends InstructionAccountInput,
  TAccountTokenProgram extends InstructionAccountInput,
  TAccountSystemProgram extends InstructionAccountInput,
  TProgramAddress extends Address = typeof SKECH_PROGRAM_ADDRESS,
>(
  input: DepositInput<
    TAccountPayer,
    TAccountAuthority,
    TAccountGame,
    TAccountPlayer,
    TAccountFrom,
    TAccountVault,
    TAccountUsdcMint,
    TAccountTokenProgram,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): DepositInstruction<
  TProgramAddress,
  ResolvedInstructionAccountMeta<
    TAccountPayer,
    InstructionAccountInputAddress<TAccountPayer>
  >,
  ResolvedInstructionAccountMeta<
    TAccountAuthority,
    InstructionAccountInputAddress<TAccountAuthority>
  >,
  ResolvedInstructionAccountMeta<
    TAccountGame,
    InstructionAccountInputAddress<TAccountGame>
  >,
  ResolvedInstructionAccountMeta<
    TAccountPlayer,
    InstructionAccountInputAddress<TAccountPlayer>
  >,
  ResolvedInstructionAccountMeta<
    TAccountFrom,
    InstructionAccountInputAddress<TAccountFrom>
  >,
  ResolvedInstructionAccountMeta<
    TAccountVault,
    InstructionAccountInputAddress<TAccountVault>
  >,
  ResolvedInstructionAccountMeta<
    TAccountUsdcMint,
    InstructionAccountInputAddress<TAccountUsdcMint>
  >,
  ResolvedInstructionAccountMeta<
    TAccountTokenProgram,
    InstructionAccountInputAddress<TAccountTokenProgram>
  >,
  ResolvedInstructionAccountMeta<
    TAccountSystemProgram,
    InstructionAccountInputAddress<TAccountSystemProgram>
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? SKECH_PROGRAM_ADDRESS;

  // Account meta helper.
  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");

  // Original accounts.
  const originalAccounts = {
    payer: { value: input.payer ?? null, isSigner: true, isWritable: true },
    authority: {
      value: input.authority ?? null,
      isSigner: true,
      isWritable: false,
    },
    game: { value: input.game ?? null, isSigner: false, isWritable: false },
    player: { value: input.player ?? null, isSigner: false, isWritable: true },
    from: { value: input.from ?? null, isSigner: false, isWritable: true },
    vault: { value: input.vault ?? null, isSigner: false, isWritable: true },
    usdcMint: {
      value: input.usdcMint ?? null,
      isSigner: false,
      isWritable: false,
    },
    tokenProgram: {
      value: input.tokenProgram ?? null,
      isSigner: false,
      isWritable: false,
    },
    systemProgram: {
      value: input.systemProgram ?? null,
      isSigner: false,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  return Object.freeze({
    accounts: [
      getAccountMeta("payer", accounts.payer),
      getAccountMeta("authority", accounts.authority),
      getAccountMeta("game", accounts.game),
      getAccountMeta("player", accounts.player),
      getAccountMeta("from", accounts.from),
      getAccountMeta("vault", accounts.vault),
      getAccountMeta("usdcMint", accounts.usdcMint),
      getAccountMeta("tokenProgram", accounts.tokenProgram),
      getAccountMeta("systemProgram", accounts.systemProgram),
    ],
    data: getDepositInstructionDataEncoder().encode(
      args as DepositInstructionDataArgs,
    ),
    programAddress,
  } as DepositInstruction<
    TProgramAddress,
    ResolvedInstructionAccountMeta<
      TAccountPayer,
      InstructionAccountInputAddress<TAccountPayer>
    >,
    ResolvedInstructionAccountMeta<
      TAccountAuthority,
      InstructionAccountInputAddress<TAccountAuthority>
    >,
    ResolvedInstructionAccountMeta<
      TAccountGame,
      InstructionAccountInputAddress<TAccountGame>
    >,
    ResolvedInstructionAccountMeta<
      TAccountPlayer,
      InstructionAccountInputAddress<TAccountPlayer>
    >,
    ResolvedInstructionAccountMeta<
      TAccountFrom,
      InstructionAccountInputAddress<TAccountFrom>
    >,
    ResolvedInstructionAccountMeta<
      TAccountVault,
      InstructionAccountInputAddress<TAccountVault>
    >,
    ResolvedInstructionAccountMeta<
      TAccountUsdcMint,
      InstructionAccountInputAddress<TAccountUsdcMint>
    >,
    ResolvedInstructionAccountMeta<
      TAccountTokenProgram,
      InstructionAccountInputAddress<TAccountTokenProgram>
    >,
    ResolvedInstructionAccountMeta<
      TAccountSystemProgram,
      InstructionAccountInputAddress<TAccountSystemProgram>
    >
  >);
}

export type ParsedDepositInstruction<
  TProgram extends string = typeof SKECH_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    payer: TAccountMetas[0];
    authority: TAccountMetas[1];
    game: TAccountMetas[2];
    player: TAccountMetas[3];
    from: TAccountMetas[4];
    vault: TAccountMetas[5];
    usdcMint: TAccountMetas[6];
    tokenProgram: TAccountMetas[7];
    systemProgram: TAccountMetas[8];
  };
  data: DepositInstructionData;
};

export function parseDepositInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedDepositInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 9) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 9,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      payer: getNextAccount(),
      authority: getNextAccount(),
      game: getNextAccount(),
      player: getNextAccount(),
      from: getNextAccount(),
      vault: getNextAccount(),
      usdcMint: getNextAccount(),
      tokenProgram: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getDepositInstructionDataDecoder().decode(instruction.data),
  };
}
