/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  type InstructionAccountInput,
  type InstructionAccountInputAddress,
  type InstructionSignerInput,
  type ResolvedInstructionAccount,
  type ResolvedInstructionAccountMeta,
} from "@solana/kit/program-client-core";
import { findGamePda, findRewardsPda } from "../pdas";
import { SKECH_PROGRAM_ADDRESS } from "../programs";
import {
  getConfigDecoder,
  getConfigEncoder,
  getRewardsConfigDecoder,
  getRewardsConfigEncoder,
  type Config,
  type ConfigArgs,
  type RewardsConfig,
  type RewardsConfigArgs,
} from "../types";

export const INIT_REWARDS_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([
  24, 217, 207, 96, 28, 211, 144, 146,
]);

export function getInitRewardsDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    INIT_REWARDS_DISCRIMINATOR,
  );
}

export type InitRewardsInstruction<
  TProgram extends string = typeof SKECH_PROGRAM_ADDRESS,
  TAccountAdmin extends string | AccountMeta<string> = string,
  TAccountGame extends string | AccountMeta<string> = string,
  TAccountRewards extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountAdmin extends string
        ? WritableSignerAccount<TAccountAdmin> &
            AccountSignerMeta<TAccountAdmin>
        : TAccountAdmin,
      TAccountGame extends string
        ? WritableAccount<TAccountGame>
        : TAccountGame,
      TAccountRewards extends string
        ? WritableAccount<TAccountRewards>
        : TAccountRewards,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type InitRewardsInstructionData = {
  discriminator: ReadonlyUint8Array;
  config: Config;
  rewardsConfig: RewardsConfig;
};

export type InitRewardsInstructionDataArgs = {
  config: ConfigArgs;
  rewardsConfig: RewardsConfigArgs;
};

export function getInitRewardsInstructionDataEncoder(): FixedSizeEncoder<InitRewardsInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["config", getConfigEncoder()],
      ["rewardsConfig", getRewardsConfigEncoder()],
    ]),
    (value) => ({ ...value, discriminator: INIT_REWARDS_DISCRIMINATOR }),
  );
}

export function getInitRewardsInstructionDataDecoder(): FixedSizeDecoder<InitRewardsInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["config", getConfigDecoder()],
    ["rewardsConfig", getRewardsConfigDecoder()],
  ]);
}

export function getInitRewardsInstructionDataCodec(): FixedSizeCodec<
  InitRewardsInstructionDataArgs,
  InitRewardsInstructionData
> {
  return combineCodec(
    getInitRewardsInstructionDataEncoder(),
    getInitRewardsInstructionDataDecoder(),
  );
}

export type InitRewardsAsyncInput<
  TAccountAdmin extends InstructionSignerInput = InstructionSignerInput,
  TAccountGame extends InstructionAccountInput = InstructionAccountInput,
  TAccountRewards extends InstructionAccountInput = InstructionAccountInput,
  TAccountSystemProgram extends InstructionAccountInput =
    InstructionAccountInput,
> = {
  admin: TAccountAdmin;
  game?: TAccountGame;
  rewards?: TAccountRewards;
  systemProgram?: TAccountSystemProgram;
  config: InitRewardsInstructionDataArgs["config"];
  rewardsConfig: InitRewardsInstructionDataArgs["rewardsConfig"];
};

export async function getInitRewardsInstructionAsync<
  TAccountAdmin extends InstructionSignerInput,
  TAccountGame extends InstructionAccountInput,
  TAccountRewards extends InstructionAccountInput,
  TAccountSystemProgram extends InstructionAccountInput,
  TProgramAddress extends Address = typeof SKECH_PROGRAM_ADDRESS,
>(
  input: InitRewardsAsyncInput<
    TAccountAdmin,
    TAccountGame,
    TAccountRewards,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  InitRewardsInstruction<
    TProgramAddress,
    ResolvedInstructionAccountMeta<
      TAccountAdmin,
      InstructionAccountInputAddress<TAccountAdmin>
    >,
    ResolvedInstructionAccountMeta<
      TAccountGame,
      InstructionAccountInputAddress<TAccountGame>
    >,
    ResolvedInstructionAccountMeta<
      TAccountRewards,
      InstructionAccountInputAddress<TAccountRewards>
    >,
    ResolvedInstructionAccountMeta<
      TAccountSystemProgram,
      InstructionAccountInputAddress<TAccountSystemProgram>
    >
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? SKECH_PROGRAM_ADDRESS;

  // Account meta helper.
  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");

  // Original accounts.
  const originalAccounts = {
    admin: { value: input.admin ?? null, isSigner: true, isWritable: true },
    game: { value: input.game ?? null, isSigner: false, isWritable: true },
    rewards: {
      value: input.rewards ?? null,
      isSigner: false,
      isWritable: true,
    },
    systemProgram: {
      value: input.systemProgram ?? null,
      isSigner: false,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.game.value) {
    accounts.game.value = await findGamePda({ programAddress });
  }
  if (!accounts.rewards.value) {
    accounts.rewards.value = await findRewardsPda({ programAddress });
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  return Object.freeze({
    accounts: [
      getAccountMeta("admin", accounts.admin),
      getAccountMeta("game", accounts.game),
      getAccountMeta("rewards", accounts.rewards),
      getAccountMeta("systemProgram", accounts.systemProgram),
    ],
    data: getInitRewardsInstructionDataEncoder().encode(
      args as InitRewardsInstructionDataArgs,
    ),
    programAddress,
  } as InitRewardsInstruction<
    TProgramAddress,
    ResolvedInstructionAccountMeta<
      TAccountAdmin,
      InstructionAccountInputAddress<TAccountAdmin>
    >,
    ResolvedInstructionAccountMeta<
      TAccountGame,
      InstructionAccountInputAddress<TAccountGame>
    >,
    ResolvedInstructionAccountMeta<
      TAccountRewards,
      InstructionAccountInputAddress<TAccountRewards>
    >,
    ResolvedInstructionAccountMeta<
      TAccountSystemProgram,
      InstructionAccountInputAddress<TAccountSystemProgram>
    >
  >);
}

export type InitRewardsInput<
  TAccountAdmin extends InstructionSignerInput = InstructionSignerInput,
  TAccountGame extends InstructionAccountInput = InstructionAccountInput,
  TAccountRewards extends InstructionAccountInput = InstructionAccountInput,
  TAccountSystemProgram extends InstructionAccountInput =
    InstructionAccountInput,
> = {
  admin: TAccountAdmin;
  game: TAccountGame;
  rewards: TAccountRewards;
  systemProgram?: TAccountSystemProgram;
  config: InitRewardsInstructionDataArgs["config"];
  rewardsConfig: InitRewardsInstructionDataArgs["rewardsConfig"];
};

export function getInitRewardsInstruction<
  TAccountAdmin extends InstructionSignerInput,
  TAccountGame extends InstructionAccountInput,
  TAccountRewards extends InstructionAccountInput,
  TAccountSystemProgram extends InstructionAccountInput,
  TProgramAddress extends Address = typeof SKECH_PROGRAM_ADDRESS,
>(
  input: InitRewardsInput<
    TAccountAdmin,
    TAccountGame,
    TAccountRewards,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): InitRewardsInstruction<
  TProgramAddress,
  ResolvedInstructionAccountMeta<
    TAccountAdmin,
    InstructionAccountInputAddress<TAccountAdmin>
  >,
  ResolvedInstructionAccountMeta<
    TAccountGame,
    InstructionAccountInputAddress<TAccountGame>
  >,
  ResolvedInstructionAccountMeta<
    TAccountRewards,
    InstructionAccountInputAddress<TAccountRewards>
  >,
  ResolvedInstructionAccountMeta<
    TAccountSystemProgram,
    InstructionAccountInputAddress<TAccountSystemProgram>
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? SKECH_PROGRAM_ADDRESS;

  // Account meta helper.
  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");

  // Original accounts.
  const originalAccounts = {
    admin: { value: input.admin ?? null, isSigner: true, isWritable: true },
    game: { value: input.game ?? null, isSigner: false, isWritable: true },
    rewards: {
      value: input.rewards ?? null,
      isSigner: false,
      isWritable: true,
    },
    systemProgram: {
      value: input.systemProgram ?? null,
      isSigner: false,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  return Object.freeze({
    accounts: [
      getAccountMeta("admin", accounts.admin),
      getAccountMeta("game", accounts.game),
      getAccountMeta("rewards", accounts.rewards),
      getAccountMeta("systemProgram", accounts.systemProgram),
    ],
    data: getInitRewardsInstructionDataEncoder().encode(
      args as InitRewardsInstructionDataArgs,
    ),
    programAddress,
  } as InitRewardsInstruction<
    TProgramAddress,
    ResolvedInstructionAccountMeta<
      TAccountAdmin,
      InstructionAccountInputAddress<TAccountAdmin>
    >,
    ResolvedInstructionAccountMeta<
      TAccountGame,
      InstructionAccountInputAddress<TAccountGame>
    >,
    ResolvedInstructionAccountMeta<
      TAccountRewards,
      InstructionAccountInputAddress<TAccountRewards>
    >,
    ResolvedInstructionAccountMeta<
      TAccountSystemProgram,
      InstructionAccountInputAddress<TAccountSystemProgram>
    >
  >);
}

export type ParsedInitRewardsInstruction<
  TProgram extends string = typeof SKECH_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    admin: TAccountMetas[0];
    game: TAccountMetas[1];
    rewards: TAccountMetas[2];
    systemProgram: TAccountMetas[3];
  };
  data: InitRewardsInstructionData;
};

export function parseInitRewardsInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedInitRewardsInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 4) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 4,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      admin: getNextAccount(),
      game: getNextAccount(),
      rewards: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getInitRewardsInstructionDataDecoder().decode(instruction.data),
  };
}
