/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  addDecoderSizePrefix,
  addEncoderSizePrefix,
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  getU8Decoder,
  getU8Encoder,
  getUtf8Decoder,
  getUtf8Encoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  type InstructionAccountInput,
  type InstructionAccountInputAddress,
  type InstructionSignerInput,
  type ResolvedInstructionAccount,
  type ResolvedInstructionAccountMeta,
} from "@solana/kit/program-client-core";
import { findGamePda } from "../pdas";
import { SKECH_PROGRAM_ADDRESS } from "../programs";

export const INIT_MARKET_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([
  33, 253, 15, 116, 89, 25, 127, 236,
]);

export function getInitMarketDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(INIT_MARKET_DISCRIMINATOR);
}

export type InitMarketInstruction<
  TProgram extends string = typeof SKECH_PROGRAM_ADDRESS,
  TAccountAdmin extends string | AccountMeta<string> = string,
  TAccountGame extends string | AccountMeta<string> = string,
  TAccountMarket extends string | AccountMeta<string> = string,
  TAccountBars extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountAdmin extends string
        ? WritableSignerAccount<TAccountAdmin> &
            AccountSignerMeta<TAccountAdmin>
        : TAccountAdmin,
      TAccountGame extends string
        ? ReadonlyAccount<TAccountGame>
        : TAccountGame,
      TAccountMarket extends string
        ? WritableAccount<TAccountMarket>
        : TAccountMarket,
      TAccountBars extends string
        ? WritableAccount<TAccountBars>
        : TAccountBars,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type InitMarketInstructionData = {
  discriminator: ReadonlyUint8Array;
  id: number;
  name: string;
  difficulty: number;
};

export type InitMarketInstructionDataArgs = {
  id: number;
  name: string;
  difficulty: number;
};

export function getInitMarketInstructionDataEncoder(): Encoder<InitMarketInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["id", getU8Encoder()],
      ["name", addEncoderSizePrefix(getUtf8Encoder(), getU32Encoder())],
      ["difficulty", getU8Encoder()],
    ]),
    (value) => ({ ...value, discriminator: INIT_MARKET_DISCRIMINATOR }),
  );
}

export function getInitMarketInstructionDataDecoder(): Decoder<InitMarketInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["id", getU8Decoder()],
    ["name", addDecoderSizePrefix(getUtf8Decoder(), getU32Decoder())],
    ["difficulty", getU8Decoder()],
  ]);
}

export function getInitMarketInstructionDataCodec(): Codec<
  InitMarketInstructionDataArgs,
  InitMarketInstructionData
> {
  return combineCodec(
    getInitMarketInstructionDataEncoder(),
    getInitMarketInstructionDataDecoder(),
  );
}

export type InitMarketAsyncInput<
  TAccountAdmin extends InstructionSignerInput = InstructionSignerInput,
  TAccountGame extends InstructionAccountInput = InstructionAccountInput,
  TAccountMarket extends InstructionAccountInput = InstructionAccountInput,
  TAccountBars extends InstructionAccountInput = InstructionAccountInput,
  TAccountSystemProgram extends InstructionAccountInput =
    InstructionAccountInput,
> = {
  admin: TAccountAdmin;
  game?: TAccountGame;
  market: TAccountMarket;
  bars: TAccountBars;
  systemProgram?: TAccountSystemProgram;
  id: InitMarketInstructionDataArgs["id"];
  name: InitMarketInstructionDataArgs["name"];
  difficulty: InitMarketInstructionDataArgs["difficulty"];
};

export async function getInitMarketInstructionAsync<
  TAccountAdmin extends InstructionSignerInput,
  TAccountGame extends InstructionAccountInput,
  TAccountMarket extends InstructionAccountInput,
  TAccountBars extends InstructionAccountInput,
  TAccountSystemProgram extends InstructionAccountInput,
  TProgramAddress extends Address = typeof SKECH_PROGRAM_ADDRESS,
>(
  input: InitMarketAsyncInput<
    TAccountAdmin,
    TAccountGame,
    TAccountMarket,
    TAccountBars,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  InitMarketInstruction<
    TProgramAddress,
    ResolvedInstructionAccountMeta<
      TAccountAdmin,
      InstructionAccountInputAddress<TAccountAdmin>
    >,
    ResolvedInstructionAccountMeta<
      TAccountGame,
      InstructionAccountInputAddress<TAccountGame>
    >,
    ResolvedInstructionAccountMeta<
      TAccountMarket,
      InstructionAccountInputAddress<TAccountMarket>
    >,
    ResolvedInstructionAccountMeta<
      TAccountBars,
      InstructionAccountInputAddress<TAccountBars>
    >,
    ResolvedInstructionAccountMeta<
      TAccountSystemProgram,
      InstructionAccountInputAddress<TAccountSystemProgram>
    >
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? SKECH_PROGRAM_ADDRESS;

  // Account meta helper.
  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");

  // Original accounts.
  const originalAccounts = {
    admin: { value: input.admin ?? null, isSigner: true, isWritable: true },
    game: { value: input.game ?? null, isSigner: false, isWritable: false },
    market: { value: input.market ?? null, isSigner: false, isWritable: true },
    bars: { value: input.bars ?? null, isSigner: false, isWritable: true },
    systemProgram: {
      value: input.systemProgram ?? null,
      isSigner: false,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.game.value) {
    accounts.game.value = await findGamePda({ programAddress });
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  return Object.freeze({
    accounts: [
      getAccountMeta("admin", accounts.admin),
      getAccountMeta("game", accounts.game),
      getAccountMeta("market", accounts.market),
      getAccountMeta("bars", accounts.bars),
      getAccountMeta("systemProgram", accounts.systemProgram),
    ],
    data: getInitMarketInstructionDataEncoder().encode(
      args as InitMarketInstructionDataArgs,
    ),
    programAddress,
  } as InitMarketInstruction<
    TProgramAddress,
    ResolvedInstructionAccountMeta<
      TAccountAdmin,
      InstructionAccountInputAddress<TAccountAdmin>
    >,
    ResolvedInstructionAccountMeta<
      TAccountGame,
      InstructionAccountInputAddress<TAccountGame>
    >,
    ResolvedInstructionAccountMeta<
      TAccountMarket,
      InstructionAccountInputAddress<TAccountMarket>
    >,
    ResolvedInstructionAccountMeta<
      TAccountBars,
      InstructionAccountInputAddress<TAccountBars>
    >,
    ResolvedInstructionAccountMeta<
      TAccountSystemProgram,
      InstructionAccountInputAddress<TAccountSystemProgram>
    >
  >);
}

export type InitMarketInput<
  TAccountAdmin extends InstructionSignerInput = InstructionSignerInput,
  TAccountGame extends InstructionAccountInput = InstructionAccountInput,
  TAccountMarket extends InstructionAccountInput = InstructionAccountInput,
  TAccountBars extends InstructionAccountInput = InstructionAccountInput,
  TAccountSystemProgram extends InstructionAccountInput =
    InstructionAccountInput,
> = {
  admin: TAccountAdmin;
  game: TAccountGame;
  market: TAccountMarket;
  bars: TAccountBars;
  systemProgram?: TAccountSystemProgram;
  id: InitMarketInstructionDataArgs["id"];
  name: InitMarketInstructionDataArgs["name"];
  difficulty: InitMarketInstructionDataArgs["difficulty"];
};

export function getInitMarketInstruction<
  TAccountAdmin extends InstructionSignerInput,
  TAccountGame extends InstructionAccountInput,
  TAccountMarket extends InstructionAccountInput,
  TAccountBars extends InstructionAccountInput,
  TAccountSystemProgram extends InstructionAccountInput,
  TProgramAddress extends Address = typeof SKECH_PROGRAM_ADDRESS,
>(
  input: InitMarketInput<
    TAccountAdmin,
    TAccountGame,
    TAccountMarket,
    TAccountBars,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): InitMarketInstruction<
  TProgramAddress,
  ResolvedInstructionAccountMeta<
    TAccountAdmin,
    InstructionAccountInputAddress<TAccountAdmin>
  >,
  ResolvedInstructionAccountMeta<
    TAccountGame,
    InstructionAccountInputAddress<TAccountGame>
  >,
  ResolvedInstructionAccountMeta<
    TAccountMarket,
    InstructionAccountInputAddress<TAccountMarket>
  >,
  ResolvedInstructionAccountMeta<
    TAccountBars,
    InstructionAccountInputAddress<TAccountBars>
  >,
  ResolvedInstructionAccountMeta<
    TAccountSystemProgram,
    InstructionAccountInputAddress<TAccountSystemProgram>
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? SKECH_PROGRAM_ADDRESS;

  // Account meta helper.
  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");

  // Original accounts.
  const originalAccounts = {
    admin: { value: input.admin ?? null, isSigner: true, isWritable: true },
    game: { value: input.game ?? null, isSigner: false, isWritable: false },
    market: { value: input.market ?? null, isSigner: false, isWritable: true },
    bars: { value: input.bars ?? null, isSigner: false, isWritable: true },
    systemProgram: {
      value: input.systemProgram ?? null,
      isSigner: false,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  return Object.freeze({
    accounts: [
      getAccountMeta("admin", accounts.admin),
      getAccountMeta("game", accounts.game),
      getAccountMeta("market", accounts.market),
      getAccountMeta("bars", accounts.bars),
      getAccountMeta("systemProgram", accounts.systemProgram),
    ],
    data: getInitMarketInstructionDataEncoder().encode(
      args as InitMarketInstructionDataArgs,
    ),
    programAddress,
  } as InitMarketInstruction<
    TProgramAddress,
    ResolvedInstructionAccountMeta<
      TAccountAdmin,
      InstructionAccountInputAddress<TAccountAdmin>
    >,
    ResolvedInstructionAccountMeta<
      TAccountGame,
      InstructionAccountInputAddress<TAccountGame>
    >,
    ResolvedInstructionAccountMeta<
      TAccountMarket,
      InstructionAccountInputAddress<TAccountMarket>
    >,
    ResolvedInstructionAccountMeta<
      TAccountBars,
      InstructionAccountInputAddress<TAccountBars>
    >,
    ResolvedInstructionAccountMeta<
      TAccountSystemProgram,
      InstructionAccountInputAddress<TAccountSystemProgram>
    >
  >);
}

export type ParsedInitMarketInstruction<
  TProgram extends string = typeof SKECH_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    admin: TAccountMetas[0];
    game: TAccountMetas[1];
    market: TAccountMetas[2];
    bars: TAccountMetas[3];
    systemProgram: TAccountMetas[4];
  };
  data: InitMarketInstructionData;
};

export function parseInitMarketInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedInitMarketInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 5) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 5,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      admin: getNextAccount(),
      game: getNextAccount(),
      market: getNextAccount(),
      bars: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getInitMarketInstructionDataDecoder().decode(instruction.data),
  };
}
