/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getArrayDecoder,
  getArrayEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  type InstructionAccountInput,
  type InstructionAccountInputAddress,
  type InstructionSignerInput,
  type ResolvedInstructionAccount,
  type ResolvedInstructionAccountMeta,
} from "@solana/kit/program-client-core";
import { findGamePda, findPoolPda } from "../pdas";
import { SKECH_PROGRAM_ADDRESS } from "../programs";
import {
  getSectionArgDecoder,
  getSectionArgEncoder,
  type SectionArg,
  type SectionArgArgs,
} from "../types";

export const PLACE_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([
  143, 53, 56, 40, 41, 16, 5, 75,
]);

export function getPlaceDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(PLACE_DISCRIMINATOR);
}

export type PlaceInstruction<
  TProgram extends string = typeof SKECH_PROGRAM_ADDRESS,
  TAccountPayer extends string | AccountMeta<string> = string,
  TAccountOracle extends string | AccountMeta<string> = string,
  TAccountGame extends string | AccountMeta<string> = string,
  TAccountMarket extends string | AccountMeta<string> = string,
  TAccountBars extends string | AccountMeta<string> = string,
  TAccountPool extends string | AccountMeta<string> = string,
  TAccountPlayer extends string | AccountMeta<string> = string,
  TAccountBet extends string | AccountMeta<string> = string,
  TAccountInstructions extends string | AccountMeta<string> =
    "Sysvar1nstructions1111111111111111111111111",
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountPayer extends string
        ? WritableSignerAccount<TAccountPayer> &
            AccountSignerMeta<TAccountPayer>
        : TAccountPayer,
      TAccountOracle extends string
        ? ReadonlySignerAccount<TAccountOracle> &
            AccountSignerMeta<TAccountOracle>
        : TAccountOracle,
      TAccountGame extends string
        ? ReadonlyAccount<TAccountGame>
        : TAccountGame,
      TAccountMarket extends string
        ? ReadonlyAccount<TAccountMarket>
        : TAccountMarket,
      TAccountBars extends string
        ? ReadonlyAccount<TAccountBars>
        : TAccountBars,
      TAccountPool extends string
        ? WritableAccount<TAccountPool>
        : TAccountPool,
      TAccountPlayer extends string
        ? WritableAccount<TAccountPlayer>
        : TAccountPlayer,
      TAccountBet extends string ? WritableAccount<TAccountBet> : TAccountBet,
      TAccountInstructions extends string
        ? ReadonlyAccount<TAccountInstructions>
        : TAccountInstructions,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type PlaceInstructionData = {
  discriminator: ReadonlyUint8Array;
  /** `Game.domain`: this deployment on this cluster. */
  domain: ReadonlyUint8Array;
  /** The player's wallet. */
  player: Address;
  /** The drawing this piece is part of, and its number within it: together they name the bet. */
  drawing: bigint;
  index: number;
  market: number;
  /** The difficulty the player was shown. If the market's has changed since, the piece is refused. */
  difficulty: number;
  /** The second it opens on, ms. Its bands are 1 to 30 seconds after it. */
  openAt: bigint;
  /** What one dot costs, USDC e6. */
  perDot: number;
  /** The price grid the bands sit on, 8 decimals: bands are judged one unit wider each way. */
  unit: bigint;
  /** The price on the player's screen when they drew, and its time, as the engine signed it (checked by the oracle). */
  priceSeen: bigint;
  priceTime: bigint;
  /** sha256 of the stroke's points. The stroke itself stays with the relayer: it is too big for a transaction. */
  strokeHash: ReadonlyUint8Array;
  sections: Array<SectionArg>;
  /** The price the second before `open_at` closed at, 8 decimals. */
  price: bigint;
  /** The last three seconds' move in volatilities, x1e6. */
  momentum: bigint;
  /** When the oracle received the piece, ms. */
  receivedAt: bigint;
  /** Each band's chance, in billionths, in the piece's order. */
  chances: Array<number>;
};

export type PlaceInstructionDataArgs = {
  /** `Game.domain`: this deployment on this cluster. */
  domain: ReadonlyUint8Array;
  /** The player's wallet. */
  player: Address;
  /** The drawing this piece is part of, and its number within it: together they name the bet. */
  drawing: number | bigint;
  index: number;
  market: number;
  /** The difficulty the player was shown. If the market's has changed since, the piece is refused. */
  difficulty: number;
  /** The second it opens on, ms. Its bands are 1 to 30 seconds after it. */
  openAt: number | bigint;
  /** What one dot costs, USDC e6. */
  perDot: number;
  /** The price grid the bands sit on, 8 decimals: bands are judged one unit wider each way. */
  unit: number | bigint;
  /** The price on the player's screen when they drew, and its time, as the engine signed it (checked by the oracle). */
  priceSeen: number | bigint;
  priceTime: number | bigint;
  /** sha256 of the stroke's points. The stroke itself stays with the relayer: it is too big for a transaction. */
  strokeHash: ReadonlyUint8Array;
  sections: Array<SectionArgArgs>;
  /** The price the second before `open_at` closed at, 8 decimals. */
  price: number | bigint;
  /** The last three seconds' move in volatilities, x1e6. */
  momentum: number | bigint;
  /** When the oracle received the piece, ms. */
  receivedAt: number | bigint;
  /** Each band's chance, in billionths, in the piece's order. */
  chances: Array<number>;
};

export function getPlaceInstructionDataEncoder(): Encoder<PlaceInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["domain", fixEncoderSize(getBytesEncoder(), 32)],
      ["player", getAddressEncoder()],
      ["drawing", getU64Encoder()],
      ["index", getU32Encoder()],
      ["market", getU8Encoder()],
      ["difficulty", getU8Encoder()],
      ["openAt", getI64Encoder()],
      ["perDot", getU32Encoder()],
      ["unit", getU64Encoder()],
      ["priceSeen", getU64Encoder()],
      ["priceTime", getI64Encoder()],
      ["strokeHash", fixEncoderSize(getBytesEncoder(), 32)],
      ["sections", getArrayEncoder(getSectionArgEncoder())],
      ["price", getU64Encoder()],
      ["momentum", getI64Encoder()],
      ["receivedAt", getI64Encoder()],
      ["chances", getArrayEncoder(getU32Encoder())],
    ]),
    (value) => ({ ...value, discriminator: PLACE_DISCRIMINATOR }),
  );
}

export function getPlaceInstructionDataDecoder(): Decoder<PlaceInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["domain", fixDecoderSize(getBytesDecoder(), 32)],
    ["player", getAddressDecoder()],
    ["drawing", getU64Decoder()],
    ["index", getU32Decoder()],
    ["market", getU8Decoder()],
    ["difficulty", getU8Decoder()],
    ["openAt", getI64Decoder()],
    ["perDot", getU32Decoder()],
    ["unit", getU64Decoder()],
    ["priceSeen", getU64Decoder()],
    ["priceTime", getI64Decoder()],
    ["strokeHash", fixDecoderSize(getBytesDecoder(), 32)],
    ["sections", getArrayDecoder(getSectionArgDecoder())],
    ["price", getU64Decoder()],
    ["momentum", getI64Decoder()],
    ["receivedAt", getI64Decoder()],
    ["chances", getArrayDecoder(getU32Decoder())],
  ]);
}

export function getPlaceInstructionDataCodec(): Codec<
  PlaceInstructionDataArgs,
  PlaceInstructionData
> {
  return combineCodec(
    getPlaceInstructionDataEncoder(),
    getPlaceInstructionDataDecoder(),
  );
}

export type PlaceAsyncInput<
  TAccountPayer extends InstructionSignerInput = InstructionSignerInput,
  TAccountOracle extends InstructionSignerInput = InstructionSignerInput,
  TAccountGame extends InstructionAccountInput = InstructionAccountInput,
  TAccountMarket extends InstructionAccountInput = InstructionAccountInput,
  TAccountBars extends InstructionAccountInput = InstructionAccountInput,
  TAccountPool extends InstructionAccountInput = InstructionAccountInput,
  TAccountPlayer extends InstructionAccountInput = InstructionAccountInput,
  TAccountBet extends InstructionAccountInput = InstructionAccountInput,
  TAccountInstructions extends InstructionAccountInput =
    InstructionAccountInput,
  TAccountSystemProgram extends InstructionAccountInput =
    InstructionAccountInput,
> = {
  /** Pays the transaction and the bet's rent, and gets the rent back when the bet is closed. */
  payer: TAccountPayer;
  /** Attests the quote by signing. Usually the payer too. */
  oracle: TAccountOracle;
  game?: TAccountGame;
  market: TAccountMarket;
  bars: TAccountBars;
  pool?: TAccountPool;
  player: TAccountPlayer;
  /** The new bet, at seeds [BET_SEED, player, drawing, index]: created here only if the piece goes in. */
  bet: TAccountBet;
  instructions?: TAccountInstructions;
  systemProgram?: TAccountSystemProgram;
  domain: PlaceInstructionDataArgs["domain"];
  playerArg: PlaceInstructionDataArgs["player"];
  drawing: PlaceInstructionDataArgs["drawing"];
  index: PlaceInstructionDataArgs["index"];
  marketArg: PlaceInstructionDataArgs["market"];
  difficulty: PlaceInstructionDataArgs["difficulty"];
  openAt: PlaceInstructionDataArgs["openAt"];
  perDot: PlaceInstructionDataArgs["perDot"];
  unit: PlaceInstructionDataArgs["unit"];
  priceSeen: PlaceInstructionDataArgs["priceSeen"];
  priceTime: PlaceInstructionDataArgs["priceTime"];
  strokeHash: PlaceInstructionDataArgs["strokeHash"];
  sections: PlaceInstructionDataArgs["sections"];
  price: PlaceInstructionDataArgs["price"];
  momentum: PlaceInstructionDataArgs["momentum"];
  receivedAt: PlaceInstructionDataArgs["receivedAt"];
  chances: PlaceInstructionDataArgs["chances"];
};

export async function getPlaceInstructionAsync<
  TAccountPayer extends InstructionSignerInput,
  TAccountOracle extends InstructionSignerInput,
  TAccountGame extends InstructionAccountInput,
  TAccountMarket extends InstructionAccountInput,
  TAccountBars extends InstructionAccountInput,
  TAccountPool extends InstructionAccountInput,
  TAccountPlayer extends InstructionAccountInput,
  TAccountBet extends InstructionAccountInput,
  TAccountInstructions extends InstructionAccountInput,
  TAccountSystemProgram extends InstructionAccountInput,
  TProgramAddress extends Address = typeof SKECH_PROGRAM_ADDRESS,
>(
  input: PlaceAsyncInput<
    TAccountPayer,
    TAccountOracle,
    TAccountGame,
    TAccountMarket,
    TAccountBars,
    TAccountPool,
    TAccountPlayer,
    TAccountBet,
    TAccountInstructions,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  PlaceInstruction<
    TProgramAddress,
    ResolvedInstructionAccountMeta<
      TAccountPayer,
      InstructionAccountInputAddress<TAccountPayer>
    >,
    ResolvedInstructionAccountMeta<
      TAccountOracle,
      InstructionAccountInputAddress<TAccountOracle>
    >,
    ResolvedInstructionAccountMeta<
      TAccountGame,
      InstructionAccountInputAddress<TAccountGame>
    >,
    ResolvedInstructionAccountMeta<
      TAccountMarket,
      InstructionAccountInputAddress<TAccountMarket>
    >,
    ResolvedInstructionAccountMeta<
      TAccountBars,
      InstructionAccountInputAddress<TAccountBars>
    >,
    ResolvedInstructionAccountMeta<
      TAccountPool,
      InstructionAccountInputAddress<TAccountPool>
    >,
    ResolvedInstructionAccountMeta<
      TAccountPlayer,
      InstructionAccountInputAddress<TAccountPlayer>
    >,
    ResolvedInstructionAccountMeta<
      TAccountBet,
      InstructionAccountInputAddress<TAccountBet>
    >,
    ResolvedInstructionAccountMeta<
      TAccountInstructions,
      InstructionAccountInputAddress<TAccountInstructions>
    >,
    ResolvedInstructionAccountMeta<
      TAccountSystemProgram,
      InstructionAccountInputAddress<TAccountSystemProgram>
    >
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? SKECH_PROGRAM_ADDRESS;

  // Account meta helper.
  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");

  // Original accounts.
  const originalAccounts = {
    payer: { value: input.payer ?? null, isSigner: true, isWritable: true },
    oracle: { value: input.oracle ?? null, isSigner: true, isWritable: false },
    game: { value: input.game ?? null, isSigner: false, isWritable: false },
    market: { value: input.market ?? null, isSigner: false, isWritable: false },
    bars: { value: input.bars ?? null, isSigner: false, isWritable: false },
    pool: { value: input.pool ?? null, isSigner: false, isWritable: true },
    player: { value: input.player ?? null, isSigner: false, isWritable: true },
    bet: { value: input.bet ?? null, isSigner: false, isWritable: true },
    instructions: {
      value: input.instructions ?? null,
      isSigner: false,
      isWritable: false,
    },
    systemProgram: {
      value: input.systemProgram ?? null,
      isSigner: false,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input, player: input.playerArg, market: input.marketArg };

  // Resolve default values.
  if (!accounts.game.value) {
    accounts.game.value = await findGamePda({ programAddress });
  }
  if (!accounts.pool.value) {
    accounts.pool.value = await findPoolPda({ programAddress });
  }
  if (!accounts.instructions.value) {
    accounts.instructions.value =
      "Sysvar1nstructions1111111111111111111111111" as Address<"Sysvar1nstructions1111111111111111111111111">;
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  return Object.freeze({
    accounts: [
      getAccountMeta("payer", accounts.payer),
      getAccountMeta("oracle", accounts.oracle),
      getAccountMeta("game", accounts.game),
      getAccountMeta("market", accounts.market),
      getAccountMeta("bars", accounts.bars),
      getAccountMeta("pool", accounts.pool),
      getAccountMeta("player", accounts.player),
      getAccountMeta("bet", accounts.bet),
      getAccountMeta("instructions", accounts.instructions),
      getAccountMeta("systemProgram", accounts.systemProgram),
    ],
    data: getPlaceInstructionDataEncoder().encode(
      args as PlaceInstructionDataArgs,
    ),
    programAddress,
  } as PlaceInstruction<
    TProgramAddress,
    ResolvedInstructionAccountMeta<
      TAccountPayer,
      InstructionAccountInputAddress<TAccountPayer>
    >,
    ResolvedInstructionAccountMeta<
      TAccountOracle,
      InstructionAccountInputAddress<TAccountOracle>
    >,
    ResolvedInstructionAccountMeta<
      TAccountGame,
      InstructionAccountInputAddress<TAccountGame>
    >,
    ResolvedInstructionAccountMeta<
      TAccountMarket,
      InstructionAccountInputAddress<TAccountMarket>
    >,
    ResolvedInstructionAccountMeta<
      TAccountBars,
      InstructionAccountInputAddress<TAccountBars>
    >,
    ResolvedInstructionAccountMeta<
      TAccountPool,
      InstructionAccountInputAddress<TAccountPool>
    >,
    ResolvedInstructionAccountMeta<
      TAccountPlayer,
      InstructionAccountInputAddress<TAccountPlayer>
    >,
    ResolvedInstructionAccountMeta<
      TAccountBet,
      InstructionAccountInputAddress<TAccountBet>
    >,
    ResolvedInstructionAccountMeta<
      TAccountInstructions,
      InstructionAccountInputAddress<TAccountInstructions>
    >,
    ResolvedInstructionAccountMeta<
      TAccountSystemProgram,
      InstructionAccountInputAddress<TAccountSystemProgram>
    >
  >);
}

export type PlaceInput<
  TAccountPayer extends InstructionSignerInput = InstructionSignerInput,
  TAccountOracle extends InstructionSignerInput = InstructionSignerInput,
  TAccountGame extends InstructionAccountInput = InstructionAccountInput,
  TAccountMarket extends InstructionAccountInput = InstructionAccountInput,
  TAccountBars extends InstructionAccountInput = InstructionAccountInput,
  TAccountPool extends InstructionAccountInput = InstructionAccountInput,
  TAccountPlayer extends InstructionAccountInput = InstructionAccountInput,
  TAccountBet extends InstructionAccountInput = InstructionAccountInput,
  TAccountInstructions extends InstructionAccountInput =
    InstructionAccountInput,
  TAccountSystemProgram extends InstructionAccountInput =
    InstructionAccountInput,
> = {
  /** Pays the transaction and the bet's rent, and gets the rent back when the bet is closed. */
  payer: TAccountPayer;
  /** Attests the quote by signing. Usually the payer too. */
  oracle: TAccountOracle;
  game: TAccountGame;
  market: TAccountMarket;
  bars: TAccountBars;
  pool: TAccountPool;
  player: TAccountPlayer;
  /** The new bet, at seeds [BET_SEED, player, drawing, index]: created here only if the piece goes in. */
  bet: TAccountBet;
  instructions?: TAccountInstructions;
  systemProgram?: TAccountSystemProgram;
  domain: PlaceInstructionDataArgs["domain"];
  playerArg: PlaceInstructionDataArgs["player"];
  drawing: PlaceInstructionDataArgs["drawing"];
  index: PlaceInstructionDataArgs["index"];
  marketArg: PlaceInstructionDataArgs["market"];
  difficulty: PlaceInstructionDataArgs["difficulty"];
  openAt: PlaceInstructionDataArgs["openAt"];
  perDot: PlaceInstructionDataArgs["perDot"];
  unit: PlaceInstructionDataArgs["unit"];
  priceSeen: PlaceInstructionDataArgs["priceSeen"];
  priceTime: PlaceInstructionDataArgs["priceTime"];
  strokeHash: PlaceInstructionDataArgs["strokeHash"];
  sections: PlaceInstructionDataArgs["sections"];
  price: PlaceInstructionDataArgs["price"];
  momentum: PlaceInstructionDataArgs["momentum"];
  receivedAt: PlaceInstructionDataArgs["receivedAt"];
  chances: PlaceInstructionDataArgs["chances"];
};

export function getPlaceInstruction<
  TAccountPayer extends InstructionSignerInput,
  TAccountOracle extends InstructionSignerInput,
  TAccountGame extends InstructionAccountInput,
  TAccountMarket extends InstructionAccountInput,
  TAccountBars extends InstructionAccountInput,
  TAccountPool extends InstructionAccountInput,
  TAccountPlayer extends InstructionAccountInput,
  TAccountBet extends InstructionAccountInput,
  TAccountInstructions extends InstructionAccountInput,
  TAccountSystemProgram extends InstructionAccountInput,
  TProgramAddress extends Address = typeof SKECH_PROGRAM_ADDRESS,
>(
  input: PlaceInput<
    TAccountPayer,
    TAccountOracle,
    TAccountGame,
    TAccountMarket,
    TAccountBars,
    TAccountPool,
    TAccountPlayer,
    TAccountBet,
    TAccountInstructions,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): PlaceInstruction<
  TProgramAddress,
  ResolvedInstructionAccountMeta<
    TAccountPayer,
    InstructionAccountInputAddress<TAccountPayer>
  >,
  ResolvedInstructionAccountMeta<
    TAccountOracle,
    InstructionAccountInputAddress<TAccountOracle>
  >,
  ResolvedInstructionAccountMeta<
    TAccountGame,
    InstructionAccountInputAddress<TAccountGame>
  >,
  ResolvedInstructionAccountMeta<
    TAccountMarket,
    InstructionAccountInputAddress<TAccountMarket>
  >,
  ResolvedInstructionAccountMeta<
    TAccountBars,
    InstructionAccountInputAddress<TAccountBars>
  >,
  ResolvedInstructionAccountMeta<
    TAccountPool,
    InstructionAccountInputAddress<TAccountPool>
  >,
  ResolvedInstructionAccountMeta<
    TAccountPlayer,
    InstructionAccountInputAddress<TAccountPlayer>
  >,
  ResolvedInstructionAccountMeta<
    TAccountBet,
    InstructionAccountInputAddress<TAccountBet>
  >,
  ResolvedInstructionAccountMeta<
    TAccountInstructions,
    InstructionAccountInputAddress<TAccountInstructions>
  >,
  ResolvedInstructionAccountMeta<
    TAccountSystemProgram,
    InstructionAccountInputAddress<TAccountSystemProgram>
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? SKECH_PROGRAM_ADDRESS;

  // Account meta helper.
  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");

  // Original accounts.
  const originalAccounts = {
    payer: { value: input.payer ?? null, isSigner: true, isWritable: true },
    oracle: { value: input.oracle ?? null, isSigner: true, isWritable: false },
    game: { value: input.game ?? null, isSigner: false, isWritable: false },
    market: { value: input.market ?? null, isSigner: false, isWritable: false },
    bars: { value: input.bars ?? null, isSigner: false, isWritable: false },
    pool: { value: input.pool ?? null, isSigner: false, isWritable: true },
    player: { value: input.player ?? null, isSigner: false, isWritable: true },
    bet: { value: input.bet ?? null, isSigner: false, isWritable: true },
    instructions: {
      value: input.instructions ?? null,
      isSigner: false,
      isWritable: false,
    },
    systemProgram: {
      value: input.systemProgram ?? null,
      isSigner: false,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input, player: input.playerArg, market: input.marketArg };

  // Resolve default values.
  if (!accounts.instructions.value) {
    accounts.instructions.value =
      "Sysvar1nstructions1111111111111111111111111" as Address<"Sysvar1nstructions1111111111111111111111111">;
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  return Object.freeze({
    accounts: [
      getAccountMeta("payer", accounts.payer),
      getAccountMeta("oracle", accounts.oracle),
      getAccountMeta("game", accounts.game),
      getAccountMeta("market", accounts.market),
      getAccountMeta("bars", accounts.bars),
      getAccountMeta("pool", accounts.pool),
      getAccountMeta("player", accounts.player),
      getAccountMeta("bet", accounts.bet),
      getAccountMeta("instructions", accounts.instructions),
      getAccountMeta("systemProgram", accounts.systemProgram),
    ],
    data: getPlaceInstructionDataEncoder().encode(
      args as PlaceInstructionDataArgs,
    ),
    programAddress,
  } as PlaceInstruction<
    TProgramAddress,
    ResolvedInstructionAccountMeta<
      TAccountPayer,
      InstructionAccountInputAddress<TAccountPayer>
    >,
    ResolvedInstructionAccountMeta<
      TAccountOracle,
      InstructionAccountInputAddress<TAccountOracle>
    >,
    ResolvedInstructionAccountMeta<
      TAccountGame,
      InstructionAccountInputAddress<TAccountGame>
    >,
    ResolvedInstructionAccountMeta<
      TAccountMarket,
      InstructionAccountInputAddress<TAccountMarket>
    >,
    ResolvedInstructionAccountMeta<
      TAccountBars,
      InstructionAccountInputAddress<TAccountBars>
    >,
    ResolvedInstructionAccountMeta<
      TAccountPool,
      InstructionAccountInputAddress<TAccountPool>
    >,
    ResolvedInstructionAccountMeta<
      TAccountPlayer,
      InstructionAccountInputAddress<TAccountPlayer>
    >,
    ResolvedInstructionAccountMeta<
      TAccountBet,
      InstructionAccountInputAddress<TAccountBet>
    >,
    ResolvedInstructionAccountMeta<
      TAccountInstructions,
      InstructionAccountInputAddress<TAccountInstructions>
    >,
    ResolvedInstructionAccountMeta<
      TAccountSystemProgram,
      InstructionAccountInputAddress<TAccountSystemProgram>
    >
  >);
}

export type ParsedPlaceInstruction<
  TProgram extends string = typeof SKECH_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Pays the transaction and the bet's rent, and gets the rent back when the bet is closed. */
    payer: TAccountMetas[0];
    /** Attests the quote by signing. Usually the payer too. */
    oracle: TAccountMetas[1];
    game: TAccountMetas[2];
    market: TAccountMetas[3];
    bars: TAccountMetas[4];
    pool: TAccountMetas[5];
    player: TAccountMetas[6];
    /** The new bet, at seeds [BET_SEED, player, drawing, index]: created here only if the piece goes in. */
    bet: TAccountMetas[7];
    instructions: TAccountMetas[8];
    systemProgram: TAccountMetas[9];
  };
  data: PlaceInstructionData;
};

export function parsePlaceInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedPlaceInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 10) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 10,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      payer: getNextAccount(),
      oracle: getNextAccount(),
      game: getNextAccount(),
      market: getNextAccount(),
      bars: getNextAccount(),
      pool: getNextAccount(),
      player: getNextAccount(),
      bet: getNextAccount(),
      instructions: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getPlaceInstructionDataDecoder().decode(instruction.data),
  };
}
