/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type WritableAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  type InstructionAccountInput,
  type InstructionAccountInputAddress,
  type InstructionSignerInput,
  type ResolvedInstructionAccount,
  type ResolvedInstructionAccountMeta,
} from "@solana/kit/program-client-core";
import { findGamePda } from "../pdas";
import { SKECH_PROGRAM_ADDRESS } from "../programs";
import {
  getBarInputDecoder,
  getBarInputEncoder,
  type BarInput,
  type BarInputArgs,
} from "../types";

export const POST_BAR_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([
  126, 226, 63, 169, 86, 216, 167, 210,
]);

export function getPostBarDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(POST_BAR_DISCRIMINATOR);
}

export type PostBarInstruction<
  TProgram extends string = typeof SKECH_PROGRAM_ADDRESS,
  TAccountOracle extends string | AccountMeta<string> = string,
  TAccountGame extends string | AccountMeta<string> = string,
  TAccountMarketAccount extends string | AccountMeta<string> = string,
  TAccountBars extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountOracle extends string
        ? ReadonlySignerAccount<TAccountOracle> &
            AccountSignerMeta<TAccountOracle>
        : TAccountOracle,
      TAccountGame extends string
        ? ReadonlyAccount<TAccountGame>
        : TAccountGame,
      TAccountMarketAccount extends string
        ? ReadonlyAccount<TAccountMarketAccount>
        : TAccountMarketAccount,
      TAccountBars extends string
        ? WritableAccount<TAccountBars>
        : TAccountBars,
      ...TRemainingAccounts,
    ]
  >;

export type PostBarInstructionData = {
  discriminator: ReadonlyUint8Array;
  market: number;
  bar: BarInput;
};

export type PostBarInstructionDataArgs = { market: number; bar: BarInputArgs };

export function getPostBarInstructionDataEncoder(): FixedSizeEncoder<PostBarInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["market", getU8Encoder()],
      ["bar", getBarInputEncoder()],
    ]),
    (value) => ({ ...value, discriminator: POST_BAR_DISCRIMINATOR }),
  );
}

export function getPostBarInstructionDataDecoder(): FixedSizeDecoder<PostBarInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["market", getU8Decoder()],
    ["bar", getBarInputDecoder()],
  ]);
}

export function getPostBarInstructionDataCodec(): FixedSizeCodec<
  PostBarInstructionDataArgs,
  PostBarInstructionData
> {
  return combineCodec(
    getPostBarInstructionDataEncoder(),
    getPostBarInstructionDataDecoder(),
  );
}

export type PostBarAsyncInput<
  TAccountOracle extends InstructionSignerInput = InstructionSignerInput,
  TAccountGame extends InstructionAccountInput = InstructionAccountInput,
  TAccountMarketAccount extends InstructionAccountInput =
    InstructionAccountInput,
  TAccountBars extends InstructionAccountInput = InstructionAccountInput,
> = {
  oracle: TAccountOracle;
  game?: TAccountGame;
  marketAccount: TAccountMarketAccount;
  bars: TAccountBars;
  market: PostBarInstructionDataArgs["market"];
  bar: PostBarInstructionDataArgs["bar"];
};

export async function getPostBarInstructionAsync<
  TAccountOracle extends InstructionSignerInput,
  TAccountGame extends InstructionAccountInput,
  TAccountMarketAccount extends InstructionAccountInput,
  TAccountBars extends InstructionAccountInput,
  TProgramAddress extends Address = typeof SKECH_PROGRAM_ADDRESS,
>(
  input: PostBarAsyncInput<
    TAccountOracle,
    TAccountGame,
    TAccountMarketAccount,
    TAccountBars
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  PostBarInstruction<
    TProgramAddress,
    ResolvedInstructionAccountMeta<
      TAccountOracle,
      InstructionAccountInputAddress<TAccountOracle>
    >,
    ResolvedInstructionAccountMeta<
      TAccountGame,
      InstructionAccountInputAddress<TAccountGame>
    >,
    ResolvedInstructionAccountMeta<
      TAccountMarketAccount,
      InstructionAccountInputAddress<TAccountMarketAccount>
    >,
    ResolvedInstructionAccountMeta<
      TAccountBars,
      InstructionAccountInputAddress<TAccountBars>
    >
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? SKECH_PROGRAM_ADDRESS;

  // Account meta helper.
  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");

  // Original accounts.
  const originalAccounts = {
    oracle: { value: input.oracle ?? null, isSigner: true, isWritable: false },
    game: { value: input.game ?? null, isSigner: false, isWritable: false },
    marketAccount: {
      value: input.marketAccount ?? null,
      isSigner: false,
      isWritable: false,
    },
    bars: { value: input.bars ?? null, isSigner: false, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.game.value) {
    accounts.game.value = await findGamePda({ programAddress });
  }

  return Object.freeze({
    accounts: [
      getAccountMeta("oracle", accounts.oracle),
      getAccountMeta("game", accounts.game),
      getAccountMeta("marketAccount", accounts.marketAccount),
      getAccountMeta("bars", accounts.bars),
    ],
    data: getPostBarInstructionDataEncoder().encode(
      args as PostBarInstructionDataArgs,
    ),
    programAddress,
  } as PostBarInstruction<
    TProgramAddress,
    ResolvedInstructionAccountMeta<
      TAccountOracle,
      InstructionAccountInputAddress<TAccountOracle>
    >,
    ResolvedInstructionAccountMeta<
      TAccountGame,
      InstructionAccountInputAddress<TAccountGame>
    >,
    ResolvedInstructionAccountMeta<
      TAccountMarketAccount,
      InstructionAccountInputAddress<TAccountMarketAccount>
    >,
    ResolvedInstructionAccountMeta<
      TAccountBars,
      InstructionAccountInputAddress<TAccountBars>
    >
  >);
}

export type PostBarInput<
  TAccountOracle extends InstructionSignerInput = InstructionSignerInput,
  TAccountGame extends InstructionAccountInput = InstructionAccountInput,
  TAccountMarketAccount extends InstructionAccountInput =
    InstructionAccountInput,
  TAccountBars extends InstructionAccountInput = InstructionAccountInput,
> = {
  oracle: TAccountOracle;
  game: TAccountGame;
  marketAccount: TAccountMarketAccount;
  bars: TAccountBars;
  market: PostBarInstructionDataArgs["market"];
  bar: PostBarInstructionDataArgs["bar"];
};

export function getPostBarInstruction<
  TAccountOracle extends InstructionSignerInput,
  TAccountGame extends InstructionAccountInput,
  TAccountMarketAccount extends InstructionAccountInput,
  TAccountBars extends InstructionAccountInput,
  TProgramAddress extends Address = typeof SKECH_PROGRAM_ADDRESS,
>(
  input: PostBarInput<
    TAccountOracle,
    TAccountGame,
    TAccountMarketAccount,
    TAccountBars
  >,
  config?: { programAddress?: TProgramAddress },
): PostBarInstruction<
  TProgramAddress,
  ResolvedInstructionAccountMeta<
    TAccountOracle,
    InstructionAccountInputAddress<TAccountOracle>
  >,
  ResolvedInstructionAccountMeta<
    TAccountGame,
    InstructionAccountInputAddress<TAccountGame>
  >,
  ResolvedInstructionAccountMeta<
    TAccountMarketAccount,
    InstructionAccountInputAddress<TAccountMarketAccount>
  >,
  ResolvedInstructionAccountMeta<
    TAccountBars,
    InstructionAccountInputAddress<TAccountBars>
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? SKECH_PROGRAM_ADDRESS;

  // Account meta helper.
  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");

  // Original accounts.
  const originalAccounts = {
    oracle: { value: input.oracle ?? null, isSigner: true, isWritable: false },
    game: { value: input.game ?? null, isSigner: false, isWritable: false },
    marketAccount: {
      value: input.marketAccount ?? null,
      isSigner: false,
      isWritable: false,
    },
    bars: { value: input.bars ?? null, isSigner: false, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  return Object.freeze({
    accounts: [
      getAccountMeta("oracle", accounts.oracle),
      getAccountMeta("game", accounts.game),
      getAccountMeta("marketAccount", accounts.marketAccount),
      getAccountMeta("bars", accounts.bars),
    ],
    data: getPostBarInstructionDataEncoder().encode(
      args as PostBarInstructionDataArgs,
    ),
    programAddress,
  } as PostBarInstruction<
    TProgramAddress,
    ResolvedInstructionAccountMeta<
      TAccountOracle,
      InstructionAccountInputAddress<TAccountOracle>
    >,
    ResolvedInstructionAccountMeta<
      TAccountGame,
      InstructionAccountInputAddress<TAccountGame>
    >,
    ResolvedInstructionAccountMeta<
      TAccountMarketAccount,
      InstructionAccountInputAddress<TAccountMarketAccount>
    >,
    ResolvedInstructionAccountMeta<
      TAccountBars,
      InstructionAccountInputAddress<TAccountBars>
    >
  >);
}

export type ParsedPostBarInstruction<
  TProgram extends string = typeof SKECH_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    oracle: TAccountMetas[0];
    game: TAccountMetas[1];
    marketAccount: TAccountMetas[2];
    bars: TAccountMetas[3];
  };
  data: PostBarInstructionData;
};

export function parsePostBarInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedPostBarInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 4) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 4,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      oracle: getNextAccount(),
      game: getNextAccount(),
      marketAccount: getNextAccount(),
      bars: getNextAccount(),
    },
    data: getPostBarInstructionDataDecoder().decode(instruction.data),
  };
}
