/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type WritableAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  type InstructionAccountInput,
  type InstructionAccountInputAddress,
  type ResolvedInstructionAccount,
  type ResolvedInstructionAccountMeta,
} from "@solana/kit/program-client-core";
import { findGamePda, findPoolPda } from "../pdas";
import { SKECH_PROGRAM_ADDRESS } from "../programs";

export const REDEEM_HOUSE_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([
  143, 146, 67, 5, 57, 3, 254, 31,
]);

export function getRedeemHouseDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    REDEEM_HOUSE_DISCRIMINATOR,
  );
}

export type RedeemHouseInstruction<
  TProgram extends string = typeof SKECH_PROGRAM_ADDRESS,
  TAccountGame extends string | AccountMeta<string> = string,
  TAccountPool extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountGame extends string
        ? ReadonlyAccount<TAccountGame>
        : TAccountGame,
      TAccountPool extends string
        ? WritableAccount<TAccountPool>
        : TAccountPool,
      ...TRemainingAccounts,
    ]
  >;

export type RedeemHouseInstructionData = { discriminator: ReadonlyUint8Array };

export type RedeemHouseInstructionDataArgs = {};

export function getRedeemHouseInstructionDataEncoder(): FixedSizeEncoder<RedeemHouseInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([["discriminator", fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({ ...value, discriminator: REDEEM_HOUSE_DISCRIMINATOR }),
  );
}

export function getRedeemHouseInstructionDataDecoder(): FixedSizeDecoder<RedeemHouseInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getRedeemHouseInstructionDataCodec(): FixedSizeCodec<
  RedeemHouseInstructionDataArgs,
  RedeemHouseInstructionData
> {
  return combineCodec(
    getRedeemHouseInstructionDataEncoder(),
    getRedeemHouseInstructionDataDecoder(),
  );
}

export type RedeemHouseAsyncInput<
  TAccountGame extends InstructionAccountInput = InstructionAccountInput,
  TAccountPool extends InstructionAccountInput = InstructionAccountInput,
> = {
  game?: TAccountGame;
  pool?: TAccountPool;
};

export async function getRedeemHouseInstructionAsync<
  TAccountGame extends InstructionAccountInput,
  TAccountPool extends InstructionAccountInput,
  TProgramAddress extends Address = typeof SKECH_PROGRAM_ADDRESS,
>(
  input: RedeemHouseAsyncInput<TAccountGame, TAccountPool>,
  config?: { programAddress?: TProgramAddress },
): Promise<
  RedeemHouseInstruction<
    TProgramAddress,
    ResolvedInstructionAccountMeta<
      TAccountGame,
      InstructionAccountInputAddress<TAccountGame>
    >,
    ResolvedInstructionAccountMeta<
      TAccountPool,
      InstructionAccountInputAddress<TAccountPool>
    >
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? SKECH_PROGRAM_ADDRESS;

  // Account meta helper.
  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");

  // Original accounts.
  const originalAccounts = {
    game: { value: input.game ?? null, isSigner: false, isWritable: false },
    pool: { value: input.pool ?? null, isSigner: false, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Resolve default values.
  if (!accounts.game.value) {
    accounts.game.value = await findGamePda({ programAddress });
  }
  if (!accounts.pool.value) {
    accounts.pool.value = await findPoolPda({ programAddress });
  }

  return Object.freeze({
    accounts: [
      getAccountMeta("game", accounts.game),
      getAccountMeta("pool", accounts.pool),
    ],
    data: getRedeemHouseInstructionDataEncoder().encode({}),
    programAddress,
  } as RedeemHouseInstruction<
    TProgramAddress,
    ResolvedInstructionAccountMeta<
      TAccountGame,
      InstructionAccountInputAddress<TAccountGame>
    >,
    ResolvedInstructionAccountMeta<
      TAccountPool,
      InstructionAccountInputAddress<TAccountPool>
    >
  >);
}

export type RedeemHouseInput<
  TAccountGame extends InstructionAccountInput = InstructionAccountInput,
  TAccountPool extends InstructionAccountInput = InstructionAccountInput,
> = {
  game: TAccountGame;
  pool: TAccountPool;
};

export function getRedeemHouseInstruction<
  TAccountGame extends InstructionAccountInput,
  TAccountPool extends InstructionAccountInput,
  TProgramAddress extends Address = typeof SKECH_PROGRAM_ADDRESS,
>(
  input: RedeemHouseInput<TAccountGame, TAccountPool>,
  config?: { programAddress?: TProgramAddress },
): RedeemHouseInstruction<
  TProgramAddress,
  ResolvedInstructionAccountMeta<
    TAccountGame,
    InstructionAccountInputAddress<TAccountGame>
  >,
  ResolvedInstructionAccountMeta<
    TAccountPool,
    InstructionAccountInputAddress<TAccountPool>
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? SKECH_PROGRAM_ADDRESS;

  // Account meta helper.
  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");

  // Original accounts.
  const originalAccounts = {
    game: { value: input.game ?? null, isSigner: false, isWritable: false },
    pool: { value: input.pool ?? null, isSigner: false, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  return Object.freeze({
    accounts: [
      getAccountMeta("game", accounts.game),
      getAccountMeta("pool", accounts.pool),
    ],
    data: getRedeemHouseInstructionDataEncoder().encode({}),
    programAddress,
  } as RedeemHouseInstruction<
    TProgramAddress,
    ResolvedInstructionAccountMeta<
      TAccountGame,
      InstructionAccountInputAddress<TAccountGame>
    >,
    ResolvedInstructionAccountMeta<
      TAccountPool,
      InstructionAccountInputAddress<TAccountPool>
    >
  >);
}

export type ParsedRedeemHouseInstruction<
  TProgram extends string = typeof SKECH_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    game: TAccountMetas[0];
    pool: TAccountMetas[1];
  };
  data: RedeemHouseInstructionData;
};

export function parseRedeemHouseInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedRedeemHouseInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 2) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 2,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: { game: getNextAccount(), pool: getNextAccount() },
    data: getRedeemHouseInstructionDataDecoder().decode(instruction.data),
  };
}
