/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU128Decoder,
  getU128Encoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type WritableAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  type InstructionAccountInput,
  type InstructionAccountInputAddress,
  type InstructionSignerInput,
  type ResolvedInstructionAccount,
  type ResolvedInstructionAccountMeta,
} from "@solana/kit/program-client-core";
import { findGamePda, findPoolPda } from "../pdas";
import { SKECH_PROGRAM_ADDRESS } from "../programs";

export const REDEEM_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([
  184, 12, 86, 149, 70, 196, 97, 225,
]);

export function getRedeemDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(REDEEM_DISCRIMINATOR);
}

export type RedeemInstruction<
  TProgram extends string = typeof SKECH_PROGRAM_ADDRESS,
  TAccountCaller extends string | AccountMeta<string> = string,
  TAccountGame extends string | AccountMeta<string> = string,
  TAccountPool extends string | AccountMeta<string> = string,
  TAccountHolder extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountCaller extends string
        ? ReadonlySignerAccount<TAccountCaller> &
            AccountSignerMeta<TAccountCaller>
        : TAccountCaller,
      TAccountGame extends string
        ? ReadonlyAccount<TAccountGame>
        : TAccountGame,
      TAccountPool extends string
        ? WritableAccount<TAccountPool>
        : TAccountPool,
      TAccountHolder extends string
        ? WritableAccount<TAccountHolder>
        : TAccountHolder,
      ...TRemainingAccounts,
    ]
  >;

export type RedeemInstructionData = {
  discriminator: ReadonlyUint8Array;
  shares: bigint;
};

export type RedeemInstructionDataArgs = { shares: number | bigint };

export function getRedeemInstructionDataEncoder(): FixedSizeEncoder<RedeemInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["shares", getU128Encoder()],
    ]),
    (value) => ({ ...value, discriminator: REDEEM_DISCRIMINATOR }),
  );
}

export function getRedeemInstructionDataDecoder(): FixedSizeDecoder<RedeemInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["shares", getU128Decoder()],
  ]);
}

export function getRedeemInstructionDataCodec(): FixedSizeCodec<
  RedeemInstructionDataArgs,
  RedeemInstructionData
> {
  return combineCodec(
    getRedeemInstructionDataEncoder(),
    getRedeemInstructionDataDecoder(),
  );
}

export type RedeemAsyncInput<
  TAccountCaller extends InstructionSignerInput = InstructionSignerInput,
  TAccountGame extends InstructionAccountInput = InstructionAccountInput,
  TAccountPool extends InstructionAccountInput = InstructionAccountInput,
  TAccountHolder extends InstructionAccountInput = InstructionAccountInput,
> = {
  /** Whoever sends it. If it is not the holder, they earn the house a cut of the growth. */
  caller: TAccountCaller;
  game?: TAccountGame;
  pool?: TAccountPool;
  holder: TAccountHolder;
  shares: RedeemInstructionDataArgs["shares"];
};

export async function getRedeemInstructionAsync<
  TAccountCaller extends InstructionSignerInput,
  TAccountGame extends InstructionAccountInput,
  TAccountPool extends InstructionAccountInput,
  TAccountHolder extends InstructionAccountInput,
  TProgramAddress extends Address = typeof SKECH_PROGRAM_ADDRESS,
>(
  input: RedeemAsyncInput<
    TAccountCaller,
    TAccountGame,
    TAccountPool,
    TAccountHolder
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  RedeemInstruction<
    TProgramAddress,
    ResolvedInstructionAccountMeta<
      TAccountCaller,
      InstructionAccountInputAddress<TAccountCaller>
    >,
    ResolvedInstructionAccountMeta<
      TAccountGame,
      InstructionAccountInputAddress<TAccountGame>
    >,
    ResolvedInstructionAccountMeta<
      TAccountPool,
      InstructionAccountInputAddress<TAccountPool>
    >,
    ResolvedInstructionAccountMeta<
      TAccountHolder,
      InstructionAccountInputAddress<TAccountHolder>
    >
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? SKECH_PROGRAM_ADDRESS;

  // Account meta helper.
  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");

  // Original accounts.
  const originalAccounts = {
    caller: { value: input.caller ?? null, isSigner: true, isWritable: false },
    game: { value: input.game ?? null, isSigner: false, isWritable: false },
    pool: { value: input.pool ?? null, isSigner: false, isWritable: true },
    holder: { value: input.holder ?? null, isSigner: false, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.game.value) {
    accounts.game.value = await findGamePda({ programAddress });
  }
  if (!accounts.pool.value) {
    accounts.pool.value = await findPoolPda({ programAddress });
  }

  return Object.freeze({
    accounts: [
      getAccountMeta("caller", accounts.caller),
      getAccountMeta("game", accounts.game),
      getAccountMeta("pool", accounts.pool),
      getAccountMeta("holder", accounts.holder),
    ],
    data: getRedeemInstructionDataEncoder().encode(
      args as RedeemInstructionDataArgs,
    ),
    programAddress,
  } as RedeemInstruction<
    TProgramAddress,
    ResolvedInstructionAccountMeta<
      TAccountCaller,
      InstructionAccountInputAddress<TAccountCaller>
    >,
    ResolvedInstructionAccountMeta<
      TAccountGame,
      InstructionAccountInputAddress<TAccountGame>
    >,
    ResolvedInstructionAccountMeta<
      TAccountPool,
      InstructionAccountInputAddress<TAccountPool>
    >,
    ResolvedInstructionAccountMeta<
      TAccountHolder,
      InstructionAccountInputAddress<TAccountHolder>
    >
  >);
}

export type RedeemInput<
  TAccountCaller extends InstructionSignerInput = InstructionSignerInput,
  TAccountGame extends InstructionAccountInput = InstructionAccountInput,
  TAccountPool extends InstructionAccountInput = InstructionAccountInput,
  TAccountHolder extends InstructionAccountInput = InstructionAccountInput,
> = {
  /** Whoever sends it. If it is not the holder, they earn the house a cut of the growth. */
  caller: TAccountCaller;
  game: TAccountGame;
  pool: TAccountPool;
  holder: TAccountHolder;
  shares: RedeemInstructionDataArgs["shares"];
};

export function getRedeemInstruction<
  TAccountCaller extends InstructionSignerInput,
  TAccountGame extends InstructionAccountInput,
  TAccountPool extends InstructionAccountInput,
  TAccountHolder extends InstructionAccountInput,
  TProgramAddress extends Address = typeof SKECH_PROGRAM_ADDRESS,
>(
  input: RedeemInput<
    TAccountCaller,
    TAccountGame,
    TAccountPool,
    TAccountHolder
  >,
  config?: { programAddress?: TProgramAddress },
): RedeemInstruction<
  TProgramAddress,
  ResolvedInstructionAccountMeta<
    TAccountCaller,
    InstructionAccountInputAddress<TAccountCaller>
  >,
  ResolvedInstructionAccountMeta<
    TAccountGame,
    InstructionAccountInputAddress<TAccountGame>
  >,
  ResolvedInstructionAccountMeta<
    TAccountPool,
    InstructionAccountInputAddress<TAccountPool>
  >,
  ResolvedInstructionAccountMeta<
    TAccountHolder,
    InstructionAccountInputAddress<TAccountHolder>
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? SKECH_PROGRAM_ADDRESS;

  // Account meta helper.
  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");

  // Original accounts.
  const originalAccounts = {
    caller: { value: input.caller ?? null, isSigner: true, isWritable: false },
    game: { value: input.game ?? null, isSigner: false, isWritable: false },
    pool: { value: input.pool ?? null, isSigner: false, isWritable: true },
    holder: { value: input.holder ?? null, isSigner: false, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  return Object.freeze({
    accounts: [
      getAccountMeta("caller", accounts.caller),
      getAccountMeta("game", accounts.game),
      getAccountMeta("pool", accounts.pool),
      getAccountMeta("holder", accounts.holder),
    ],
    data: getRedeemInstructionDataEncoder().encode(
      args as RedeemInstructionDataArgs,
    ),
    programAddress,
  } as RedeemInstruction<
    TProgramAddress,
    ResolvedInstructionAccountMeta<
      TAccountCaller,
      InstructionAccountInputAddress<TAccountCaller>
    >,
    ResolvedInstructionAccountMeta<
      TAccountGame,
      InstructionAccountInputAddress<TAccountGame>
    >,
    ResolvedInstructionAccountMeta<
      TAccountPool,
      InstructionAccountInputAddress<TAccountPool>
    >,
    ResolvedInstructionAccountMeta<
      TAccountHolder,
      InstructionAccountInputAddress<TAccountHolder>
    >
  >);
}

export type ParsedRedeemInstruction<
  TProgram extends string = typeof SKECH_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Whoever sends it. If it is not the holder, they earn the house a cut of the growth. */
    caller: TAccountMetas[0];
    game: TAccountMetas[1];
    pool: TAccountMetas[2];
    holder: TAccountMetas[3];
  };
  data: RedeemInstructionData;
};

export function parseRedeemInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedRedeemInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 4) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 4,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      caller: getNextAccount(),
      game: getNextAccount(),
      pool: getNextAccount(),
      holder: getNextAccount(),
    },
    data: getRedeemInstructionDataDecoder().decode(instruction.data),
  };
}
