/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type WritableAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  getAddressFromResolvedInstructionAccount,
  type InstructionAccountInput,
  type InstructionAccountInputAddress,
  type InstructionSignerInput,
  type ResolvedInstructionAccount,
  type ResolvedInstructionAccountMeta,
} from "@solana/kit/program-client-core";
import { findPlayerPda } from "../pdas";
import { SKECH_PROGRAM_ADDRESS } from "../programs";

export const REVOKE_SESSION_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([
  86, 92, 198, 120, 144, 2, 7, 194,
]);

export function getRevokeSessionDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    REVOKE_SESSION_DISCRIMINATOR,
  );
}

export type RevokeSessionInstruction<
  TProgram extends string = typeof SKECH_PROGRAM_ADDRESS,
  TAccountAuthority extends string | AccountMeta<string> = string,
  TAccountPlayer extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountAuthority extends string
        ? ReadonlySignerAccount<TAccountAuthority> &
            AccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      TAccountPlayer extends string
        ? WritableAccount<TAccountPlayer>
        : TAccountPlayer,
      ...TRemainingAccounts,
    ]
  >;

export type RevokeSessionInstructionData = {
  discriminator: ReadonlyUint8Array;
};

export type RevokeSessionInstructionDataArgs = {};

export function getRevokeSessionInstructionDataEncoder(): FixedSizeEncoder<RevokeSessionInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([["discriminator", fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({ ...value, discriminator: REVOKE_SESSION_DISCRIMINATOR }),
  );
}

export function getRevokeSessionInstructionDataDecoder(): FixedSizeDecoder<RevokeSessionInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getRevokeSessionInstructionDataCodec(): FixedSizeCodec<
  RevokeSessionInstructionDataArgs,
  RevokeSessionInstructionData
> {
  return combineCodec(
    getRevokeSessionInstructionDataEncoder(),
    getRevokeSessionInstructionDataDecoder(),
  );
}

export type RevokeSessionAsyncInput<
  TAccountAuthority extends InstructionSignerInput = InstructionSignerInput,
  TAccountPlayer extends InstructionAccountInput = InstructionAccountInput,
> = {
  authority: TAccountAuthority;
  player?: TAccountPlayer;
};

export async function getRevokeSessionInstructionAsync<
  TAccountAuthority extends InstructionSignerInput,
  TAccountPlayer extends InstructionAccountInput,
  TProgramAddress extends Address = typeof SKECH_PROGRAM_ADDRESS,
>(
  input: RevokeSessionAsyncInput<TAccountAuthority, TAccountPlayer>,
  config?: { programAddress?: TProgramAddress },
): Promise<
  RevokeSessionInstruction<
    TProgramAddress,
    ResolvedInstructionAccountMeta<
      TAccountAuthority,
      InstructionAccountInputAddress<TAccountAuthority>
    >,
    ResolvedInstructionAccountMeta<
      TAccountPlayer,
      InstructionAccountInputAddress<TAccountPlayer>
    >
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? SKECH_PROGRAM_ADDRESS;

  // Account meta helper.
  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");

  // Original accounts.
  const originalAccounts = {
    authority: {
      value: input.authority ?? null,
      isSigner: true,
      isWritable: false,
    },
    player: { value: input.player ?? null, isSigner: false, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Resolve default values.
  if (!accounts.player.value) {
    accounts.player.value = await findPlayerPda(
      {
        authority: getAddressFromResolvedInstructionAccount(
          "authority",
          accounts.authority.value,
        ),
      },
      { programAddress },
    );
  }

  return Object.freeze({
    accounts: [
      getAccountMeta("authority", accounts.authority),
      getAccountMeta("player", accounts.player),
    ],
    data: getRevokeSessionInstructionDataEncoder().encode({}),
    programAddress,
  } as RevokeSessionInstruction<
    TProgramAddress,
    ResolvedInstructionAccountMeta<
      TAccountAuthority,
      InstructionAccountInputAddress<TAccountAuthority>
    >,
    ResolvedInstructionAccountMeta<
      TAccountPlayer,
      InstructionAccountInputAddress<TAccountPlayer>
    >
  >);
}

export type RevokeSessionInput<
  TAccountAuthority extends InstructionSignerInput = InstructionSignerInput,
  TAccountPlayer extends InstructionAccountInput = InstructionAccountInput,
> = {
  authority: TAccountAuthority;
  player: TAccountPlayer;
};

export function getRevokeSessionInstruction<
  TAccountAuthority extends InstructionSignerInput,
  TAccountPlayer extends InstructionAccountInput,
  TProgramAddress extends Address = typeof SKECH_PROGRAM_ADDRESS,
>(
  input: RevokeSessionInput<TAccountAuthority, TAccountPlayer>,
  config?: { programAddress?: TProgramAddress },
): RevokeSessionInstruction<
  TProgramAddress,
  ResolvedInstructionAccountMeta<
    TAccountAuthority,
    InstructionAccountInputAddress<TAccountAuthority>
  >,
  ResolvedInstructionAccountMeta<
    TAccountPlayer,
    InstructionAccountInputAddress<TAccountPlayer>
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? SKECH_PROGRAM_ADDRESS;

  // Account meta helper.
  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");

  // Original accounts.
  const originalAccounts = {
    authority: {
      value: input.authority ?? null,
      isSigner: true,
      isWritable: false,
    },
    player: { value: input.player ?? null, isSigner: false, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  return Object.freeze({
    accounts: [
      getAccountMeta("authority", accounts.authority),
      getAccountMeta("player", accounts.player),
    ],
    data: getRevokeSessionInstructionDataEncoder().encode({}),
    programAddress,
  } as RevokeSessionInstruction<
    TProgramAddress,
    ResolvedInstructionAccountMeta<
      TAccountAuthority,
      InstructionAccountInputAddress<TAccountAuthority>
    >,
    ResolvedInstructionAccountMeta<
      TAccountPlayer,
      InstructionAccountInputAddress<TAccountPlayer>
    >
  >);
}

export type ParsedRevokeSessionInstruction<
  TProgram extends string = typeof SKECH_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    authority: TAccountMetas[0];
    player: TAccountMetas[1];
  };
  data: RevokeSessionInstructionData;
};

export function parseRevokeSessionInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedRevokeSessionInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 2) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 2,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: { authority: getNextAccount(), player: getNextAccount() },
    data: getRevokeSessionInstructionDataDecoder().decode(instruction.data),
  };
}
