/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type WritableAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  type InstructionAccountInput,
  type InstructionAccountInputAddress,
  type InstructionSignerInput,
  type ResolvedInstructionAccount,
  type ResolvedInstructionAccountMeta,
} from "@solana/kit/program-client-core";
import { findGamePda, findPoolPda } from "../pdas";
import { SKECH_PROGRAM_ADDRESS } from "../programs";

export const SET_IOU_RATE_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([
  180, 95, 213, 183, 110, 69, 85, 189,
]);

export function getSetIouRateDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    SET_IOU_RATE_DISCRIMINATOR,
  );
}

export type SetIouRateInstruction<
  TProgram extends string = typeof SKECH_PROGRAM_ADDRESS,
  TAccountAdmin extends string | AccountMeta<string> = string,
  TAccountGame extends string | AccountMeta<string> = string,
  TAccountPool extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountAdmin extends string
        ? ReadonlySignerAccount<TAccountAdmin> &
            AccountSignerMeta<TAccountAdmin>
        : TAccountAdmin,
      TAccountGame extends string
        ? ReadonlyAccount<TAccountGame>
        : TAccountGame,
      TAccountPool extends string
        ? WritableAccount<TAccountPool>
        : TAccountPool,
      ...TRemainingAccounts,
    ]
  >;

export type SetIouRateInstructionData = {
  discriminator: ReadonlyUint8Array;
  rate: bigint;
};

export type SetIouRateInstructionDataArgs = { rate: number | bigint };

export function getSetIouRateInstructionDataEncoder(): FixedSizeEncoder<SetIouRateInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["rate", getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: SET_IOU_RATE_DISCRIMINATOR }),
  );
}

export function getSetIouRateInstructionDataDecoder(): FixedSizeDecoder<SetIouRateInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["rate", getU64Decoder()],
  ]);
}

export function getSetIouRateInstructionDataCodec(): FixedSizeCodec<
  SetIouRateInstructionDataArgs,
  SetIouRateInstructionData
> {
  return combineCodec(
    getSetIouRateInstructionDataEncoder(),
    getSetIouRateInstructionDataDecoder(),
  );
}

export type SetIouRateAsyncInput<
  TAccountAdmin extends InstructionSignerInput = InstructionSignerInput,
  TAccountGame extends InstructionAccountInput = InstructionAccountInput,
  TAccountPool extends InstructionAccountInput = InstructionAccountInput,
> = {
  admin: TAccountAdmin;
  game?: TAccountGame;
  pool?: TAccountPool;
  rate: SetIouRateInstructionDataArgs["rate"];
};

export async function getSetIouRateInstructionAsync<
  TAccountAdmin extends InstructionSignerInput,
  TAccountGame extends InstructionAccountInput,
  TAccountPool extends InstructionAccountInput,
  TProgramAddress extends Address = typeof SKECH_PROGRAM_ADDRESS,
>(
  input: SetIouRateAsyncInput<TAccountAdmin, TAccountGame, TAccountPool>,
  config?: { programAddress?: TProgramAddress },
): Promise<
  SetIouRateInstruction<
    TProgramAddress,
    ResolvedInstructionAccountMeta<
      TAccountAdmin,
      InstructionAccountInputAddress<TAccountAdmin>
    >,
    ResolvedInstructionAccountMeta<
      TAccountGame,
      InstructionAccountInputAddress<TAccountGame>
    >,
    ResolvedInstructionAccountMeta<
      TAccountPool,
      InstructionAccountInputAddress<TAccountPool>
    >
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? SKECH_PROGRAM_ADDRESS;

  // Account meta helper.
  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");

  // Original accounts.
  const originalAccounts = {
    admin: { value: input.admin ?? null, isSigner: true, isWritable: false },
    game: { value: input.game ?? null, isSigner: false, isWritable: false },
    pool: { value: input.pool ?? null, isSigner: false, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.game.value) {
    accounts.game.value = await findGamePda({ programAddress });
  }
  if (!accounts.pool.value) {
    accounts.pool.value = await findPoolPda({ programAddress });
  }

  return Object.freeze({
    accounts: [
      getAccountMeta("admin", accounts.admin),
      getAccountMeta("game", accounts.game),
      getAccountMeta("pool", accounts.pool),
    ],
    data: getSetIouRateInstructionDataEncoder().encode(
      args as SetIouRateInstructionDataArgs,
    ),
    programAddress,
  } as SetIouRateInstruction<
    TProgramAddress,
    ResolvedInstructionAccountMeta<
      TAccountAdmin,
      InstructionAccountInputAddress<TAccountAdmin>
    >,
    ResolvedInstructionAccountMeta<
      TAccountGame,
      InstructionAccountInputAddress<TAccountGame>
    >,
    ResolvedInstructionAccountMeta<
      TAccountPool,
      InstructionAccountInputAddress<TAccountPool>
    >
  >);
}

export type SetIouRateInput<
  TAccountAdmin extends InstructionSignerInput = InstructionSignerInput,
  TAccountGame extends InstructionAccountInput = InstructionAccountInput,
  TAccountPool extends InstructionAccountInput = InstructionAccountInput,
> = {
  admin: TAccountAdmin;
  game: TAccountGame;
  pool: TAccountPool;
  rate: SetIouRateInstructionDataArgs["rate"];
};

export function getSetIouRateInstruction<
  TAccountAdmin extends InstructionSignerInput,
  TAccountGame extends InstructionAccountInput,
  TAccountPool extends InstructionAccountInput,
  TProgramAddress extends Address = typeof SKECH_PROGRAM_ADDRESS,
>(
  input: SetIouRateInput<TAccountAdmin, TAccountGame, TAccountPool>,
  config?: { programAddress?: TProgramAddress },
): SetIouRateInstruction<
  TProgramAddress,
  ResolvedInstructionAccountMeta<
    TAccountAdmin,
    InstructionAccountInputAddress<TAccountAdmin>
  >,
  ResolvedInstructionAccountMeta<
    TAccountGame,
    InstructionAccountInputAddress<TAccountGame>
  >,
  ResolvedInstructionAccountMeta<
    TAccountPool,
    InstructionAccountInputAddress<TAccountPool>
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? SKECH_PROGRAM_ADDRESS;

  // Account meta helper.
  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");

  // Original accounts.
  const originalAccounts = {
    admin: { value: input.admin ?? null, isSigner: true, isWritable: false },
    game: { value: input.game ?? null, isSigner: false, isWritable: false },
    pool: { value: input.pool ?? null, isSigner: false, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  return Object.freeze({
    accounts: [
      getAccountMeta("admin", accounts.admin),
      getAccountMeta("game", accounts.game),
      getAccountMeta("pool", accounts.pool),
    ],
    data: getSetIouRateInstructionDataEncoder().encode(
      args as SetIouRateInstructionDataArgs,
    ),
    programAddress,
  } as SetIouRateInstruction<
    TProgramAddress,
    ResolvedInstructionAccountMeta<
      TAccountAdmin,
      InstructionAccountInputAddress<TAccountAdmin>
    >,
    ResolvedInstructionAccountMeta<
      TAccountGame,
      InstructionAccountInputAddress<TAccountGame>
    >,
    ResolvedInstructionAccountMeta<
      TAccountPool,
      InstructionAccountInputAddress<TAccountPool>
    >
  >);
}

export type ParsedSetIouRateInstruction<
  TProgram extends string = typeof SKECH_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    admin: TAccountMetas[0];
    game: TAccountMetas[1];
    pool: TAccountMetas[2];
  };
  data: SetIouRateInstructionData;
};

export function parseSetIouRateInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedSetIouRateInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 3) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 3,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      admin: getNextAccount(),
      game: getNextAccount(),
      pool: getNextAccount(),
    },
    data: getSetIouRateInstructionDataDecoder().decode(instruction.data),
  };
}
