/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBooleanDecoder,
  getBooleanEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type WritableAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  type InstructionAccountInput,
  type InstructionAccountInputAddress,
  type InstructionSignerInput,
  type ResolvedInstructionAccount,
  type ResolvedInstructionAccountMeta,
} from "@solana/kit/program-client-core";
import { findGamePda } from "../pdas";
import { SKECH_PROGRAM_ADDRESS } from "../programs";

export const SET_PAUSED_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([
  91, 60, 125, 192, 176, 225, 166, 218,
]);

export function getSetPausedDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(SET_PAUSED_DISCRIMINATOR);
}

export type SetPausedInstruction<
  TProgram extends string = typeof SKECH_PROGRAM_ADDRESS,
  TAccountAdmin extends string | AccountMeta<string> = string,
  TAccountGame extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountAdmin extends string
        ? ReadonlySignerAccount<TAccountAdmin> &
            AccountSignerMeta<TAccountAdmin>
        : TAccountAdmin,
      TAccountGame extends string
        ? WritableAccount<TAccountGame>
        : TAccountGame,
      ...TRemainingAccounts,
    ]
  >;

export type SetPausedInstructionData = {
  discriminator: ReadonlyUint8Array;
  paused: boolean;
};

export type SetPausedInstructionDataArgs = { paused: boolean };

export function getSetPausedInstructionDataEncoder(): FixedSizeEncoder<SetPausedInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["paused", getBooleanEncoder()],
    ]),
    (value) => ({ ...value, discriminator: SET_PAUSED_DISCRIMINATOR }),
  );
}

export function getSetPausedInstructionDataDecoder(): FixedSizeDecoder<SetPausedInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["paused", getBooleanDecoder()],
  ]);
}

export function getSetPausedInstructionDataCodec(): FixedSizeCodec<
  SetPausedInstructionDataArgs,
  SetPausedInstructionData
> {
  return combineCodec(
    getSetPausedInstructionDataEncoder(),
    getSetPausedInstructionDataDecoder(),
  );
}

export type SetPausedAsyncInput<
  TAccountAdmin extends InstructionSignerInput = InstructionSignerInput,
  TAccountGame extends InstructionAccountInput = InstructionAccountInput,
> = {
  admin: TAccountAdmin;
  game?: TAccountGame;
  paused: SetPausedInstructionDataArgs["paused"];
};

export async function getSetPausedInstructionAsync<
  TAccountAdmin extends InstructionSignerInput,
  TAccountGame extends InstructionAccountInput,
  TProgramAddress extends Address = typeof SKECH_PROGRAM_ADDRESS,
>(
  input: SetPausedAsyncInput<TAccountAdmin, TAccountGame>,
  config?: { programAddress?: TProgramAddress },
): Promise<
  SetPausedInstruction<
    TProgramAddress,
    ResolvedInstructionAccountMeta<
      TAccountAdmin,
      InstructionAccountInputAddress<TAccountAdmin>
    >,
    ResolvedInstructionAccountMeta<
      TAccountGame,
      InstructionAccountInputAddress<TAccountGame>
    >
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? SKECH_PROGRAM_ADDRESS;

  // Account meta helper.
  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");

  // Original accounts.
  const originalAccounts = {
    admin: { value: input.admin ?? null, isSigner: true, isWritable: false },
    game: { value: input.game ?? null, isSigner: false, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.game.value) {
    accounts.game.value = await findGamePda({ programAddress });
  }

  return Object.freeze({
    accounts: [
      getAccountMeta("admin", accounts.admin),
      getAccountMeta("game", accounts.game),
    ],
    data: getSetPausedInstructionDataEncoder().encode(
      args as SetPausedInstructionDataArgs,
    ),
    programAddress,
  } as SetPausedInstruction<
    TProgramAddress,
    ResolvedInstructionAccountMeta<
      TAccountAdmin,
      InstructionAccountInputAddress<TAccountAdmin>
    >,
    ResolvedInstructionAccountMeta<
      TAccountGame,
      InstructionAccountInputAddress<TAccountGame>
    >
  >);
}

export type SetPausedInput<
  TAccountAdmin extends InstructionSignerInput = InstructionSignerInput,
  TAccountGame extends InstructionAccountInput = InstructionAccountInput,
> = {
  admin: TAccountAdmin;
  game: TAccountGame;
  paused: SetPausedInstructionDataArgs["paused"];
};

export function getSetPausedInstruction<
  TAccountAdmin extends InstructionSignerInput,
  TAccountGame extends InstructionAccountInput,
  TProgramAddress extends Address = typeof SKECH_PROGRAM_ADDRESS,
>(
  input: SetPausedInput<TAccountAdmin, TAccountGame>,
  config?: { programAddress?: TProgramAddress },
): SetPausedInstruction<
  TProgramAddress,
  ResolvedInstructionAccountMeta<
    TAccountAdmin,
    InstructionAccountInputAddress<TAccountAdmin>
  >,
  ResolvedInstructionAccountMeta<
    TAccountGame,
    InstructionAccountInputAddress<TAccountGame>
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? SKECH_PROGRAM_ADDRESS;

  // Account meta helper.
  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");

  // Original accounts.
  const originalAccounts = {
    admin: { value: input.admin ?? null, isSigner: true, isWritable: false },
    game: { value: input.game ?? null, isSigner: false, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  return Object.freeze({
    accounts: [
      getAccountMeta("admin", accounts.admin),
      getAccountMeta("game", accounts.game),
    ],
    data: getSetPausedInstructionDataEncoder().encode(
      args as SetPausedInstructionDataArgs,
    ),
    programAddress,
  } as SetPausedInstruction<
    TProgramAddress,
    ResolvedInstructionAccountMeta<
      TAccountAdmin,
      InstructionAccountInputAddress<TAccountAdmin>
    >,
    ResolvedInstructionAccountMeta<
      TAccountGame,
      InstructionAccountInputAddress<TAccountGame>
    >
  >);
}

export type ParsedSetPausedInstruction<
  TProgram extends string = typeof SKECH_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    admin: TAccountMetas[0];
    game: TAccountMetas[1];
  };
  data: SetPausedInstructionData;
};

export function parseSetPausedInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedSetPausedInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 2) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 2,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: { admin: getNextAccount(), game: getNextAccount() },
    data: getSetPausedInstructionDataDecoder().decode(instruction.data),
  };
}
