/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type WritableAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  type InstructionAccountInput,
  type InstructionAccountInputAddress,
  type InstructionSignerInput,
  type ResolvedInstructionAccount,
  type ResolvedInstructionAccountMeta,
} from "@solana/kit/program-client-core";
import { findGamePda } from "../pdas";
import { SKECH_PROGRAM_ADDRESS } from "../programs";
import {
  getRewardsConfigDecoder,
  getRewardsConfigEncoder,
  type RewardsConfig,
  type RewardsConfigArgs,
} from "../types";

export const SET_REWARDS_CONFIG_DISCRIMINATOR: ReadonlyUint8Array =
  new Uint8Array([113, 29, 223, 218, 217, 111, 85, 139]);

export function getSetRewardsConfigDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    SET_REWARDS_CONFIG_DISCRIMINATOR,
  );
}

export type SetRewardsConfigInstruction<
  TProgram extends string = typeof SKECH_PROGRAM_ADDRESS,
  TAccountAdmin extends string | AccountMeta<string> = string,
  TAccountGame extends string | AccountMeta<string> = string,
  TAccountRewards extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountAdmin extends string
        ? ReadonlySignerAccount<TAccountAdmin> &
            AccountSignerMeta<TAccountAdmin>
        : TAccountAdmin,
      TAccountGame extends string
        ? ReadonlyAccount<TAccountGame>
        : TAccountGame,
      TAccountRewards extends string
        ? WritableAccount<TAccountRewards>
        : TAccountRewards,
      ...TRemainingAccounts,
    ]
  >;

export type SetRewardsConfigInstructionData = {
  discriminator: ReadonlyUint8Array;
  rewardsConfig: RewardsConfig;
};

export type SetRewardsConfigInstructionDataArgs = {
  rewardsConfig: RewardsConfigArgs;
};

export function getSetRewardsConfigInstructionDataEncoder(): FixedSizeEncoder<SetRewardsConfigInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["rewardsConfig", getRewardsConfigEncoder()],
    ]),
    (value) => ({ ...value, discriminator: SET_REWARDS_CONFIG_DISCRIMINATOR }),
  );
}

export function getSetRewardsConfigInstructionDataDecoder(): FixedSizeDecoder<SetRewardsConfigInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["rewardsConfig", getRewardsConfigDecoder()],
  ]);
}

export function getSetRewardsConfigInstructionDataCodec(): FixedSizeCodec<
  SetRewardsConfigInstructionDataArgs,
  SetRewardsConfigInstructionData
> {
  return combineCodec(
    getSetRewardsConfigInstructionDataEncoder(),
    getSetRewardsConfigInstructionDataDecoder(),
  );
}

export type SetRewardsConfigAsyncInput<
  TAccountAdmin extends InstructionSignerInput = InstructionSignerInput,
  TAccountGame extends InstructionAccountInput = InstructionAccountInput,
  TAccountRewards extends InstructionAccountInput = InstructionAccountInput,
> = {
  admin: TAccountAdmin;
  game?: TAccountGame;
  /** The one `Rewards`, by its owner and discriminator (see `Place`). */
  rewards: TAccountRewards;
  rewardsConfig: SetRewardsConfigInstructionDataArgs["rewardsConfig"];
};

export async function getSetRewardsConfigInstructionAsync<
  TAccountAdmin extends InstructionSignerInput,
  TAccountGame extends InstructionAccountInput,
  TAccountRewards extends InstructionAccountInput,
  TProgramAddress extends Address = typeof SKECH_PROGRAM_ADDRESS,
>(
  input: SetRewardsConfigAsyncInput<
    TAccountAdmin,
    TAccountGame,
    TAccountRewards
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  SetRewardsConfigInstruction<
    TProgramAddress,
    ResolvedInstructionAccountMeta<
      TAccountAdmin,
      InstructionAccountInputAddress<TAccountAdmin>
    >,
    ResolvedInstructionAccountMeta<
      TAccountGame,
      InstructionAccountInputAddress<TAccountGame>
    >,
    ResolvedInstructionAccountMeta<
      TAccountRewards,
      InstructionAccountInputAddress<TAccountRewards>
    >
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? SKECH_PROGRAM_ADDRESS;

  // Account meta helper.
  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");

  // Original accounts.
  const originalAccounts = {
    admin: { value: input.admin ?? null, isSigner: true, isWritable: false },
    game: { value: input.game ?? null, isSigner: false, isWritable: false },
    rewards: {
      value: input.rewards ?? null,
      isSigner: false,
      isWritable: true,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.game.value) {
    accounts.game.value = await findGamePda({ programAddress });
  }

  return Object.freeze({
    accounts: [
      getAccountMeta("admin", accounts.admin),
      getAccountMeta("game", accounts.game),
      getAccountMeta("rewards", accounts.rewards),
    ],
    data: getSetRewardsConfigInstructionDataEncoder().encode(
      args as SetRewardsConfigInstructionDataArgs,
    ),
    programAddress,
  } as SetRewardsConfigInstruction<
    TProgramAddress,
    ResolvedInstructionAccountMeta<
      TAccountAdmin,
      InstructionAccountInputAddress<TAccountAdmin>
    >,
    ResolvedInstructionAccountMeta<
      TAccountGame,
      InstructionAccountInputAddress<TAccountGame>
    >,
    ResolvedInstructionAccountMeta<
      TAccountRewards,
      InstructionAccountInputAddress<TAccountRewards>
    >
  >);
}

export type SetRewardsConfigInput<
  TAccountAdmin extends InstructionSignerInput = InstructionSignerInput,
  TAccountGame extends InstructionAccountInput = InstructionAccountInput,
  TAccountRewards extends InstructionAccountInput = InstructionAccountInput,
> = {
  admin: TAccountAdmin;
  game: TAccountGame;
  /** The one `Rewards`, by its owner and discriminator (see `Place`). */
  rewards: TAccountRewards;
  rewardsConfig: SetRewardsConfigInstructionDataArgs["rewardsConfig"];
};

export function getSetRewardsConfigInstruction<
  TAccountAdmin extends InstructionSignerInput,
  TAccountGame extends InstructionAccountInput,
  TAccountRewards extends InstructionAccountInput,
  TProgramAddress extends Address = typeof SKECH_PROGRAM_ADDRESS,
>(
  input: SetRewardsConfigInput<TAccountAdmin, TAccountGame, TAccountRewards>,
  config?: { programAddress?: TProgramAddress },
): SetRewardsConfigInstruction<
  TProgramAddress,
  ResolvedInstructionAccountMeta<
    TAccountAdmin,
    InstructionAccountInputAddress<TAccountAdmin>
  >,
  ResolvedInstructionAccountMeta<
    TAccountGame,
    InstructionAccountInputAddress<TAccountGame>
  >,
  ResolvedInstructionAccountMeta<
    TAccountRewards,
    InstructionAccountInputAddress<TAccountRewards>
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? SKECH_PROGRAM_ADDRESS;

  // Account meta helper.
  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");

  // Original accounts.
  const originalAccounts = {
    admin: { value: input.admin ?? null, isSigner: true, isWritable: false },
    game: { value: input.game ?? null, isSigner: false, isWritable: false },
    rewards: {
      value: input.rewards ?? null,
      isSigner: false,
      isWritable: true,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  return Object.freeze({
    accounts: [
      getAccountMeta("admin", accounts.admin),
      getAccountMeta("game", accounts.game),
      getAccountMeta("rewards", accounts.rewards),
    ],
    data: getSetRewardsConfigInstructionDataEncoder().encode(
      args as SetRewardsConfigInstructionDataArgs,
    ),
    programAddress,
  } as SetRewardsConfigInstruction<
    TProgramAddress,
    ResolvedInstructionAccountMeta<
      TAccountAdmin,
      InstructionAccountInputAddress<TAccountAdmin>
    >,
    ResolvedInstructionAccountMeta<
      TAccountGame,
      InstructionAccountInputAddress<TAccountGame>
    >,
    ResolvedInstructionAccountMeta<
      TAccountRewards,
      InstructionAccountInputAddress<TAccountRewards>
    >
  >);
}

export type ParsedSetRewardsConfigInstruction<
  TProgram extends string = typeof SKECH_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    admin: TAccountMetas[0];
    game: TAccountMetas[1];
    /** The one `Rewards`, by its owner and discriminator (see `Place`). */
    rewards: TAccountMetas[2];
  };
  data: SetRewardsConfigInstructionData;
};

export function parseSetRewardsConfigInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedSetRewardsConfigInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 3) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 3,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      admin: getNextAccount(),
      game: getNextAccount(),
      rewards: getNextAccount(),
    },
    data: getSetRewardsConfigInstructionDataDecoder().decode(instruction.data),
  };
}
