/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  getAddressFromResolvedInstructionAccount,
  type InstructionAccountInput,
  type InstructionAccountInputAddress,
  type InstructionSignerInput,
  type ResolvedInstructionAccount,
  type ResolvedInstructionAccountMeta,
} from "@solana/kit/program-client-core";
import { findGamePda, findPlayerPda } from "../pdas";
import { SKECH_PROGRAM_ADDRESS } from "../programs";

export const SET_SESSION_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([
  156, 135, 126, 111, 184, 206, 194, 141,
]);

export function getSetSessionDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(SET_SESSION_DISCRIMINATOR);
}

export type SetSessionInstruction<
  TProgram extends string = typeof SKECH_PROGRAM_ADDRESS,
  TAccountPayer extends string | AccountMeta<string> = string,
  TAccountAuthority extends string | AccountMeta<string> = string,
  TAccountGame extends string | AccountMeta<string> = string,
  TAccountPlayer extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountPayer extends string
        ? WritableSignerAccount<TAccountPayer> &
            AccountSignerMeta<TAccountPayer>
        : TAccountPayer,
      TAccountAuthority extends string
        ? ReadonlySignerAccount<TAccountAuthority> &
            AccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      TAccountGame extends string
        ? ReadonlyAccount<TAccountGame>
        : TAccountGame,
      TAccountPlayer extends string
        ? WritableAccount<TAccountPlayer>
        : TAccountPlayer,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type SetSessionInstructionData = {
  discriminator: ReadonlyUint8Array;
  key: Address;
  validUntil: bigint;
  allowance: bigint;
};

export type SetSessionInstructionDataArgs = {
  key: Address;
  validUntil: number | bigint;
  allowance: number | bigint;
};

export function getSetSessionInstructionDataEncoder(): FixedSizeEncoder<SetSessionInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["key", getAddressEncoder()],
      ["validUntil", getI64Encoder()],
      ["allowance", getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: SET_SESSION_DISCRIMINATOR }),
  );
}

export function getSetSessionInstructionDataDecoder(): FixedSizeDecoder<SetSessionInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["key", getAddressDecoder()],
    ["validUntil", getI64Decoder()],
    ["allowance", getU64Decoder()],
  ]);
}

export function getSetSessionInstructionDataCodec(): FixedSizeCodec<
  SetSessionInstructionDataArgs,
  SetSessionInstructionData
> {
  return combineCodec(
    getSetSessionInstructionDataEncoder(),
    getSetSessionInstructionDataDecoder(),
  );
}

export type SetSessionAsyncInput<
  TAccountPayer extends InstructionSignerInput = InstructionSignerInput,
  TAccountAuthority extends InstructionSignerInput = InstructionSignerInput,
  TAccountGame extends InstructionAccountInput = InstructionAccountInput,
  TAccountPlayer extends InstructionAccountInput = InstructionAccountInput,
  TAccountSystemProgram extends InstructionAccountInput =
    InstructionAccountInput,
> = {
  payer: TAccountPayer;
  authority: TAccountAuthority;
  game?: TAccountGame;
  player?: TAccountPlayer;
  systemProgram?: TAccountSystemProgram;
  key: SetSessionInstructionDataArgs["key"];
  validUntil: SetSessionInstructionDataArgs["validUntil"];
  allowance: SetSessionInstructionDataArgs["allowance"];
};

export async function getSetSessionInstructionAsync<
  TAccountPayer extends InstructionSignerInput,
  TAccountAuthority extends InstructionSignerInput,
  TAccountGame extends InstructionAccountInput,
  TAccountPlayer extends InstructionAccountInput,
  TAccountSystemProgram extends InstructionAccountInput,
  TProgramAddress extends Address = typeof SKECH_PROGRAM_ADDRESS,
>(
  input: SetSessionAsyncInput<
    TAccountPayer,
    TAccountAuthority,
    TAccountGame,
    TAccountPlayer,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  SetSessionInstruction<
    TProgramAddress,
    ResolvedInstructionAccountMeta<
      TAccountPayer,
      InstructionAccountInputAddress<TAccountPayer>
    >,
    ResolvedInstructionAccountMeta<
      TAccountAuthority,
      InstructionAccountInputAddress<TAccountAuthority>
    >,
    ResolvedInstructionAccountMeta<
      TAccountGame,
      InstructionAccountInputAddress<TAccountGame>
    >,
    ResolvedInstructionAccountMeta<
      TAccountPlayer,
      InstructionAccountInputAddress<TAccountPlayer>
    >,
    ResolvedInstructionAccountMeta<
      TAccountSystemProgram,
      InstructionAccountInputAddress<TAccountSystemProgram>
    >
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? SKECH_PROGRAM_ADDRESS;

  // Account meta helper.
  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");

  // Original accounts.
  const originalAccounts = {
    payer: { value: input.payer ?? null, isSigner: true, isWritable: true },
    authority: {
      value: input.authority ?? null,
      isSigner: true,
      isWritable: false,
    },
    game: { value: input.game ?? null, isSigner: false, isWritable: false },
    player: { value: input.player ?? null, isSigner: false, isWritable: true },
    systemProgram: {
      value: input.systemProgram ?? null,
      isSigner: false,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.game.value) {
    accounts.game.value = await findGamePda({ programAddress });
  }
  if (!accounts.player.value) {
    accounts.player.value = await findPlayerPda(
      {
        authority: getAddressFromResolvedInstructionAccount(
          "authority",
          accounts.authority.value,
        ),
      },
      { programAddress },
    );
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  return Object.freeze({
    accounts: [
      getAccountMeta("payer", accounts.payer),
      getAccountMeta("authority", accounts.authority),
      getAccountMeta("game", accounts.game),
      getAccountMeta("player", accounts.player),
      getAccountMeta("systemProgram", accounts.systemProgram),
    ],
    data: getSetSessionInstructionDataEncoder().encode(
      args as SetSessionInstructionDataArgs,
    ),
    programAddress,
  } as SetSessionInstruction<
    TProgramAddress,
    ResolvedInstructionAccountMeta<
      TAccountPayer,
      InstructionAccountInputAddress<TAccountPayer>
    >,
    ResolvedInstructionAccountMeta<
      TAccountAuthority,
      InstructionAccountInputAddress<TAccountAuthority>
    >,
    ResolvedInstructionAccountMeta<
      TAccountGame,
      InstructionAccountInputAddress<TAccountGame>
    >,
    ResolvedInstructionAccountMeta<
      TAccountPlayer,
      InstructionAccountInputAddress<TAccountPlayer>
    >,
    ResolvedInstructionAccountMeta<
      TAccountSystemProgram,
      InstructionAccountInputAddress<TAccountSystemProgram>
    >
  >);
}

export type SetSessionInput<
  TAccountPayer extends InstructionSignerInput = InstructionSignerInput,
  TAccountAuthority extends InstructionSignerInput = InstructionSignerInput,
  TAccountGame extends InstructionAccountInput = InstructionAccountInput,
  TAccountPlayer extends InstructionAccountInput = InstructionAccountInput,
  TAccountSystemProgram extends InstructionAccountInput =
    InstructionAccountInput,
> = {
  payer: TAccountPayer;
  authority: TAccountAuthority;
  game: TAccountGame;
  player: TAccountPlayer;
  systemProgram?: TAccountSystemProgram;
  key: SetSessionInstructionDataArgs["key"];
  validUntil: SetSessionInstructionDataArgs["validUntil"];
  allowance: SetSessionInstructionDataArgs["allowance"];
};

export function getSetSessionInstruction<
  TAccountPayer extends InstructionSignerInput,
  TAccountAuthority extends InstructionSignerInput,
  TAccountGame extends InstructionAccountInput,
  TAccountPlayer extends InstructionAccountInput,
  TAccountSystemProgram extends InstructionAccountInput,
  TProgramAddress extends Address = typeof SKECH_PROGRAM_ADDRESS,
>(
  input: SetSessionInput<
    TAccountPayer,
    TAccountAuthority,
    TAccountGame,
    TAccountPlayer,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): SetSessionInstruction<
  TProgramAddress,
  ResolvedInstructionAccountMeta<
    TAccountPayer,
    InstructionAccountInputAddress<TAccountPayer>
  >,
  ResolvedInstructionAccountMeta<
    TAccountAuthority,
    InstructionAccountInputAddress<TAccountAuthority>
  >,
  ResolvedInstructionAccountMeta<
    TAccountGame,
    InstructionAccountInputAddress<TAccountGame>
  >,
  ResolvedInstructionAccountMeta<
    TAccountPlayer,
    InstructionAccountInputAddress<TAccountPlayer>
  >,
  ResolvedInstructionAccountMeta<
    TAccountSystemProgram,
    InstructionAccountInputAddress<TAccountSystemProgram>
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? SKECH_PROGRAM_ADDRESS;

  // Account meta helper.
  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");

  // Original accounts.
  const originalAccounts = {
    payer: { value: input.payer ?? null, isSigner: true, isWritable: true },
    authority: {
      value: input.authority ?? null,
      isSigner: true,
      isWritable: false,
    },
    game: { value: input.game ?? null, isSigner: false, isWritable: false },
    player: { value: input.player ?? null, isSigner: false, isWritable: true },
    systemProgram: {
      value: input.systemProgram ?? null,
      isSigner: false,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  return Object.freeze({
    accounts: [
      getAccountMeta("payer", accounts.payer),
      getAccountMeta("authority", accounts.authority),
      getAccountMeta("game", accounts.game),
      getAccountMeta("player", accounts.player),
      getAccountMeta("systemProgram", accounts.systemProgram),
    ],
    data: getSetSessionInstructionDataEncoder().encode(
      args as SetSessionInstructionDataArgs,
    ),
    programAddress,
  } as SetSessionInstruction<
    TProgramAddress,
    ResolvedInstructionAccountMeta<
      TAccountPayer,
      InstructionAccountInputAddress<TAccountPayer>
    >,
    ResolvedInstructionAccountMeta<
      TAccountAuthority,
      InstructionAccountInputAddress<TAccountAuthority>
    >,
    ResolvedInstructionAccountMeta<
      TAccountGame,
      InstructionAccountInputAddress<TAccountGame>
    >,
    ResolvedInstructionAccountMeta<
      TAccountPlayer,
      InstructionAccountInputAddress<TAccountPlayer>
    >,
    ResolvedInstructionAccountMeta<
      TAccountSystemProgram,
      InstructionAccountInputAddress<TAccountSystemProgram>
    >
  >);
}

export type ParsedSetSessionInstruction<
  TProgram extends string = typeof SKECH_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    payer: TAccountMetas[0];
    authority: TAccountMetas[1];
    game: TAccountMetas[2];
    player: TAccountMetas[3];
    systemProgram: TAccountMetas[4];
  };
  data: SetSessionInstructionData;
};

export function parseSetSessionInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedSetSessionInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 5) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 5,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      payer: getNextAccount(),
      authority: getNextAccount(),
      game: getNextAccount(),
      player: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getSetSessionInstructionDataDecoder().decode(instruction.data),
  };
}
