/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type WritableAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  type InstructionAccountInput,
  type InstructionAccountInputAddress,
  type InstructionSignerInput,
  type ResolvedInstructionAccount,
  type ResolvedInstructionAccountMeta,
} from "@solana/kit/program-client-core";
import { findGamePda } from "../pdas";
import { SKECH_PROGRAM_ADDRESS } from "../programs";

export const SET_TREASURY_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([
  57, 97, 196, 95, 195, 206, 106, 136,
]);

export function getSetTreasuryDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    SET_TREASURY_DISCRIMINATOR,
  );
}

export type SetTreasuryInstruction<
  TProgram extends string = typeof SKECH_PROGRAM_ADDRESS,
  TAccountAdmin extends string | AccountMeta<string> = string,
  TAccountGame extends string | AccountMeta<string> = string,
  TAccountTreasury extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountAdmin extends string
        ? ReadonlySignerAccount<TAccountAdmin> &
            AccountSignerMeta<TAccountAdmin>
        : TAccountAdmin,
      TAccountGame extends string
        ? WritableAccount<TAccountGame>
        : TAccountGame,
      TAccountTreasury extends string
        ? ReadonlyAccount<TAccountTreasury>
        : TAccountTreasury,
      ...TRemainingAccounts,
    ]
  >;

export type SetTreasuryInstructionData = { discriminator: ReadonlyUint8Array };

export type SetTreasuryInstructionDataArgs = {};

export function getSetTreasuryInstructionDataEncoder(): FixedSizeEncoder<SetTreasuryInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([["discriminator", fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({ ...value, discriminator: SET_TREASURY_DISCRIMINATOR }),
  );
}

export function getSetTreasuryInstructionDataDecoder(): FixedSizeDecoder<SetTreasuryInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getSetTreasuryInstructionDataCodec(): FixedSizeCodec<
  SetTreasuryInstructionDataArgs,
  SetTreasuryInstructionData
> {
  return combineCodec(
    getSetTreasuryInstructionDataEncoder(),
    getSetTreasuryInstructionDataDecoder(),
  );
}

export type SetTreasuryAsyncInput<
  TAccountAdmin extends InstructionSignerInput = InstructionSignerInput,
  TAccountGame extends InstructionAccountInput = InstructionAccountInput,
  TAccountTreasury extends InstructionAccountInput = InstructionAccountInput,
> = {
  admin: TAccountAdmin;
  game?: TAccountGame;
  treasury: TAccountTreasury;
};

export async function getSetTreasuryInstructionAsync<
  TAccountAdmin extends InstructionSignerInput,
  TAccountGame extends InstructionAccountInput,
  TAccountTreasury extends InstructionAccountInput,
  TProgramAddress extends Address = typeof SKECH_PROGRAM_ADDRESS,
>(
  input: SetTreasuryAsyncInput<TAccountAdmin, TAccountGame, TAccountTreasury>,
  config?: { programAddress?: TProgramAddress },
): Promise<
  SetTreasuryInstruction<
    TProgramAddress,
    ResolvedInstructionAccountMeta<
      TAccountAdmin,
      InstructionAccountInputAddress<TAccountAdmin>
    >,
    ResolvedInstructionAccountMeta<
      TAccountGame,
      InstructionAccountInputAddress<TAccountGame>
    >,
    ResolvedInstructionAccountMeta<
      TAccountTreasury,
      InstructionAccountInputAddress<TAccountTreasury>
    >
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? SKECH_PROGRAM_ADDRESS;

  // Account meta helper.
  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");

  // Original accounts.
  const originalAccounts = {
    admin: { value: input.admin ?? null, isSigner: true, isWritable: false },
    game: { value: input.game ?? null, isSigner: false, isWritable: true },
    treasury: {
      value: input.treasury ?? null,
      isSigner: false,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Resolve default values.
  if (!accounts.game.value) {
    accounts.game.value = await findGamePda({ programAddress });
  }

  return Object.freeze({
    accounts: [
      getAccountMeta("admin", accounts.admin),
      getAccountMeta("game", accounts.game),
      getAccountMeta("treasury", accounts.treasury),
    ],
    data: getSetTreasuryInstructionDataEncoder().encode({}),
    programAddress,
  } as SetTreasuryInstruction<
    TProgramAddress,
    ResolvedInstructionAccountMeta<
      TAccountAdmin,
      InstructionAccountInputAddress<TAccountAdmin>
    >,
    ResolvedInstructionAccountMeta<
      TAccountGame,
      InstructionAccountInputAddress<TAccountGame>
    >,
    ResolvedInstructionAccountMeta<
      TAccountTreasury,
      InstructionAccountInputAddress<TAccountTreasury>
    >
  >);
}

export type SetTreasuryInput<
  TAccountAdmin extends InstructionSignerInput = InstructionSignerInput,
  TAccountGame extends InstructionAccountInput = InstructionAccountInput,
  TAccountTreasury extends InstructionAccountInput = InstructionAccountInput,
> = {
  admin: TAccountAdmin;
  game: TAccountGame;
  treasury: TAccountTreasury;
};

export function getSetTreasuryInstruction<
  TAccountAdmin extends InstructionSignerInput,
  TAccountGame extends InstructionAccountInput,
  TAccountTreasury extends InstructionAccountInput,
  TProgramAddress extends Address = typeof SKECH_PROGRAM_ADDRESS,
>(
  input: SetTreasuryInput<TAccountAdmin, TAccountGame, TAccountTreasury>,
  config?: { programAddress?: TProgramAddress },
): SetTreasuryInstruction<
  TProgramAddress,
  ResolvedInstructionAccountMeta<
    TAccountAdmin,
    InstructionAccountInputAddress<TAccountAdmin>
  >,
  ResolvedInstructionAccountMeta<
    TAccountGame,
    InstructionAccountInputAddress<TAccountGame>
  >,
  ResolvedInstructionAccountMeta<
    TAccountTreasury,
    InstructionAccountInputAddress<TAccountTreasury>
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? SKECH_PROGRAM_ADDRESS;

  // Account meta helper.
  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");

  // Original accounts.
  const originalAccounts = {
    admin: { value: input.admin ?? null, isSigner: true, isWritable: false },
    game: { value: input.game ?? null, isSigner: false, isWritable: true },
    treasury: {
      value: input.treasury ?? null,
      isSigner: false,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  return Object.freeze({
    accounts: [
      getAccountMeta("admin", accounts.admin),
      getAccountMeta("game", accounts.game),
      getAccountMeta("treasury", accounts.treasury),
    ],
    data: getSetTreasuryInstructionDataEncoder().encode({}),
    programAddress,
  } as SetTreasuryInstruction<
    TProgramAddress,
    ResolvedInstructionAccountMeta<
      TAccountAdmin,
      InstructionAccountInputAddress<TAccountAdmin>
    >,
    ResolvedInstructionAccountMeta<
      TAccountGame,
      InstructionAccountInputAddress<TAccountGame>
    >,
    ResolvedInstructionAccountMeta<
      TAccountTreasury,
      InstructionAccountInputAddress<TAccountTreasury>
    >
  >);
}

export type ParsedSetTreasuryInstruction<
  TProgram extends string = typeof SKECH_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    admin: TAccountMetas[0];
    game: TAccountMetas[1];
    treasury: TAccountMetas[2];
  };
  data: SetTreasuryInstructionData;
};

export function parseSetTreasuryInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedSetTreasuryInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 3) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 3,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      admin: getNextAccount(),
      game: getNextAccount(),
      treasury: getNextAccount(),
    },
    data: getSetTreasuryInstructionDataDecoder().decode(instruction.data),
  };
}
