/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type WritableAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  type InstructionAccountInput,
  type InstructionAccountInputAddress,
  type ResolvedInstructionAccount,
  type ResolvedInstructionAccountMeta,
} from "@solana/kit/program-client-core";
import { findGamePda } from "../pdas";
import { SKECH_PROGRAM_ADDRESS } from "../programs";

export const SWEEP_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([
  40, 23, 234, 175, 14, 61, 154, 177,
]);

export function getSweepDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(SWEEP_DISCRIMINATOR);
}

export type SweepInstruction<
  TProgram extends string = typeof SKECH_PROGRAM_ADDRESS,
  TAccountGame extends string | AccountMeta<string> = string,
  TAccountPlayer extends string | AccountMeta<string> = string,
  TAccountFrom extends string | AccountMeta<string> = string,
  TAccountVault extends string | AccountMeta<string> = string,
  TAccountUsdcMint extends string | AccountMeta<string> = string,
  TAccountTokenProgram extends string | AccountMeta<string> =
    "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountGame extends string
        ? ReadonlyAccount<TAccountGame>
        : TAccountGame,
      TAccountPlayer extends string
        ? WritableAccount<TAccountPlayer>
        : TAccountPlayer,
      TAccountFrom extends string
        ? WritableAccount<TAccountFrom>
        : TAccountFrom,
      TAccountVault extends string
        ? WritableAccount<TAccountVault>
        : TAccountVault,
      TAccountUsdcMint extends string
        ? ReadonlyAccount<TAccountUsdcMint>
        : TAccountUsdcMint,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      ...TRemainingAccounts,
    ]
  >;

export type SweepInstructionData = { discriminator: ReadonlyUint8Array };

export type SweepInstructionDataArgs = {};

export function getSweepInstructionDataEncoder(): FixedSizeEncoder<SweepInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([["discriminator", fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({ ...value, discriminator: SWEEP_DISCRIMINATOR }),
  );
}

export function getSweepInstructionDataDecoder(): FixedSizeDecoder<SweepInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getSweepInstructionDataCodec(): FixedSizeCodec<
  SweepInstructionDataArgs,
  SweepInstructionData
> {
  return combineCodec(
    getSweepInstructionDataEncoder(),
    getSweepInstructionDataDecoder(),
  );
}

export type SweepAsyncInput<
  TAccountGame extends InstructionAccountInput = InstructionAccountInput,
  TAccountPlayer extends InstructionAccountInput = InstructionAccountInput,
  TAccountFrom extends InstructionAccountInput = InstructionAccountInput,
  TAccountVault extends InstructionAccountInput = InstructionAccountInput,
  TAccountUsdcMint extends InstructionAccountInput = InstructionAccountInput,
  TAccountTokenProgram extends InstructionAccountInput =
    InstructionAccountInput,
> = {
  game?: TAccountGame;
  player: TAccountPlayer;
  /**
   * The player's own token account, on which they approved the game as delegate. Only their own tokens, into
   * their own balance: nothing else can be moved this way.
   */
  from: TAccountFrom;
  vault: TAccountVault;
  usdcMint: TAccountUsdcMint;
  tokenProgram?: TAccountTokenProgram;
};

export async function getSweepInstructionAsync<
  TAccountGame extends InstructionAccountInput,
  TAccountPlayer extends InstructionAccountInput,
  TAccountFrom extends InstructionAccountInput,
  TAccountVault extends InstructionAccountInput,
  TAccountUsdcMint extends InstructionAccountInput,
  TAccountTokenProgram extends InstructionAccountInput,
  TProgramAddress extends Address = typeof SKECH_PROGRAM_ADDRESS,
>(
  input: SweepAsyncInput<
    TAccountGame,
    TAccountPlayer,
    TAccountFrom,
    TAccountVault,
    TAccountUsdcMint,
    TAccountTokenProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  SweepInstruction<
    TProgramAddress,
    ResolvedInstructionAccountMeta<
      TAccountGame,
      InstructionAccountInputAddress<TAccountGame>
    >,
    ResolvedInstructionAccountMeta<
      TAccountPlayer,
      InstructionAccountInputAddress<TAccountPlayer>
    >,
    ResolvedInstructionAccountMeta<
      TAccountFrom,
      InstructionAccountInputAddress<TAccountFrom>
    >,
    ResolvedInstructionAccountMeta<
      TAccountVault,
      InstructionAccountInputAddress<TAccountVault>
    >,
    ResolvedInstructionAccountMeta<
      TAccountUsdcMint,
      InstructionAccountInputAddress<TAccountUsdcMint>
    >,
    ResolvedInstructionAccountMeta<
      TAccountTokenProgram,
      InstructionAccountInputAddress<TAccountTokenProgram>
    >
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? SKECH_PROGRAM_ADDRESS;

  // Account meta helper.
  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");

  // Original accounts.
  const originalAccounts = {
    game: { value: input.game ?? null, isSigner: false, isWritable: false },
    player: { value: input.player ?? null, isSigner: false, isWritable: true },
    from: { value: input.from ?? null, isSigner: false, isWritable: true },
    vault: { value: input.vault ?? null, isSigner: false, isWritable: true },
    usdcMint: {
      value: input.usdcMint ?? null,
      isSigner: false,
      isWritable: false,
    },
    tokenProgram: {
      value: input.tokenProgram ?? null,
      isSigner: false,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Resolve default values.
  if (!accounts.game.value) {
    accounts.game.value = await findGamePda({ programAddress });
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }

  return Object.freeze({
    accounts: [
      getAccountMeta("game", accounts.game),
      getAccountMeta("player", accounts.player),
      getAccountMeta("from", accounts.from),
      getAccountMeta("vault", accounts.vault),
      getAccountMeta("usdcMint", accounts.usdcMint),
      getAccountMeta("tokenProgram", accounts.tokenProgram),
    ],
    data: getSweepInstructionDataEncoder().encode({}),
    programAddress,
  } as SweepInstruction<
    TProgramAddress,
    ResolvedInstructionAccountMeta<
      TAccountGame,
      InstructionAccountInputAddress<TAccountGame>
    >,
    ResolvedInstructionAccountMeta<
      TAccountPlayer,
      InstructionAccountInputAddress<TAccountPlayer>
    >,
    ResolvedInstructionAccountMeta<
      TAccountFrom,
      InstructionAccountInputAddress<TAccountFrom>
    >,
    ResolvedInstructionAccountMeta<
      TAccountVault,
      InstructionAccountInputAddress<TAccountVault>
    >,
    ResolvedInstructionAccountMeta<
      TAccountUsdcMint,
      InstructionAccountInputAddress<TAccountUsdcMint>
    >,
    ResolvedInstructionAccountMeta<
      TAccountTokenProgram,
      InstructionAccountInputAddress<TAccountTokenProgram>
    >
  >);
}

export type SweepInput<
  TAccountGame extends InstructionAccountInput = InstructionAccountInput,
  TAccountPlayer extends InstructionAccountInput = InstructionAccountInput,
  TAccountFrom extends InstructionAccountInput = InstructionAccountInput,
  TAccountVault extends InstructionAccountInput = InstructionAccountInput,
  TAccountUsdcMint extends InstructionAccountInput = InstructionAccountInput,
  TAccountTokenProgram extends InstructionAccountInput =
    InstructionAccountInput,
> = {
  game: TAccountGame;
  player: TAccountPlayer;
  /**
   * The player's own token account, on which they approved the game as delegate. Only their own tokens, into
   * their own balance: nothing else can be moved this way.
   */
  from: TAccountFrom;
  vault: TAccountVault;
  usdcMint: TAccountUsdcMint;
  tokenProgram?: TAccountTokenProgram;
};

export function getSweepInstruction<
  TAccountGame extends InstructionAccountInput,
  TAccountPlayer extends InstructionAccountInput,
  TAccountFrom extends InstructionAccountInput,
  TAccountVault extends InstructionAccountInput,
  TAccountUsdcMint extends InstructionAccountInput,
  TAccountTokenProgram extends InstructionAccountInput,
  TProgramAddress extends Address = typeof SKECH_PROGRAM_ADDRESS,
>(
  input: SweepInput<
    TAccountGame,
    TAccountPlayer,
    TAccountFrom,
    TAccountVault,
    TAccountUsdcMint,
    TAccountTokenProgram
  >,
  config?: { programAddress?: TProgramAddress },
): SweepInstruction<
  TProgramAddress,
  ResolvedInstructionAccountMeta<
    TAccountGame,
    InstructionAccountInputAddress<TAccountGame>
  >,
  ResolvedInstructionAccountMeta<
    TAccountPlayer,
    InstructionAccountInputAddress<TAccountPlayer>
  >,
  ResolvedInstructionAccountMeta<
    TAccountFrom,
    InstructionAccountInputAddress<TAccountFrom>
  >,
  ResolvedInstructionAccountMeta<
    TAccountVault,
    InstructionAccountInputAddress<TAccountVault>
  >,
  ResolvedInstructionAccountMeta<
    TAccountUsdcMint,
    InstructionAccountInputAddress<TAccountUsdcMint>
  >,
  ResolvedInstructionAccountMeta<
    TAccountTokenProgram,
    InstructionAccountInputAddress<TAccountTokenProgram>
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? SKECH_PROGRAM_ADDRESS;

  // Account meta helper.
  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");

  // Original accounts.
  const originalAccounts = {
    game: { value: input.game ?? null, isSigner: false, isWritable: false },
    player: { value: input.player ?? null, isSigner: false, isWritable: true },
    from: { value: input.from ?? null, isSigner: false, isWritable: true },
    vault: { value: input.vault ?? null, isSigner: false, isWritable: true },
    usdcMint: {
      value: input.usdcMint ?? null,
      isSigner: false,
      isWritable: false,
    },
    tokenProgram: {
      value: input.tokenProgram ?? null,
      isSigner: false,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Resolve default values.
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }

  return Object.freeze({
    accounts: [
      getAccountMeta("game", accounts.game),
      getAccountMeta("player", accounts.player),
      getAccountMeta("from", accounts.from),
      getAccountMeta("vault", accounts.vault),
      getAccountMeta("usdcMint", accounts.usdcMint),
      getAccountMeta("tokenProgram", accounts.tokenProgram),
    ],
    data: getSweepInstructionDataEncoder().encode({}),
    programAddress,
  } as SweepInstruction<
    TProgramAddress,
    ResolvedInstructionAccountMeta<
      TAccountGame,
      InstructionAccountInputAddress<TAccountGame>
    >,
    ResolvedInstructionAccountMeta<
      TAccountPlayer,
      InstructionAccountInputAddress<TAccountPlayer>
    >,
    ResolvedInstructionAccountMeta<
      TAccountFrom,
      InstructionAccountInputAddress<TAccountFrom>
    >,
    ResolvedInstructionAccountMeta<
      TAccountVault,
      InstructionAccountInputAddress<TAccountVault>
    >,
    ResolvedInstructionAccountMeta<
      TAccountUsdcMint,
      InstructionAccountInputAddress<TAccountUsdcMint>
    >,
    ResolvedInstructionAccountMeta<
      TAccountTokenProgram,
      InstructionAccountInputAddress<TAccountTokenProgram>
    >
  >);
}

export type ParsedSweepInstruction<
  TProgram extends string = typeof SKECH_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    game: TAccountMetas[0];
    player: TAccountMetas[1];
    /**
     * The player's own token account, on which they approved the game as delegate. Only their own tokens, into
     * their own balance: nothing else can be moved this way.
     */
    from: TAccountMetas[2];
    vault: TAccountMetas[3];
    usdcMint: TAccountMetas[4];
    tokenProgram: TAccountMetas[5];
  };
  data: SweepInstructionData;
};

export function parseSweepInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedSweepInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 6) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 6,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      game: getNextAccount(),
      player: getNextAccount(),
      from: getNextAccount(),
      vault: getNextAccount(),
      usdcMint: getNextAccount(),
      tokenProgram: getNextAccount(),
    },
    data: getSweepInstructionDataDecoder().decode(instruction.data),
  };
}
