/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type WritableAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  getAddressFromResolvedInstructionAccount,
  type InstructionAccountInput,
  type InstructionAccountInputAddress,
  type InstructionSignerInput,
  type ResolvedInstructionAccount,
  type ResolvedInstructionAccountMeta,
} from "@solana/kit/program-client-core";
import { findGamePda, findPlayerPda } from "../pdas";
import { SKECH_PROGRAM_ADDRESS } from "../programs";

export const WITHDRAW_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([
  183, 18, 70, 156, 148, 109, 161, 34,
]);

export function getWithdrawDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(WITHDRAW_DISCRIMINATOR);
}

export type WithdrawInstruction<
  TProgram extends string = typeof SKECH_PROGRAM_ADDRESS,
  TAccountAuthority extends string | AccountMeta<string> = string,
  TAccountGame extends string | AccountMeta<string> = string,
  TAccountPlayer extends string | AccountMeta<string> = string,
  TAccountTo extends string | AccountMeta<string> = string,
  TAccountVault extends string | AccountMeta<string> = string,
  TAccountUsdcMint extends string | AccountMeta<string> = string,
  TAccountTokenProgram extends string | AccountMeta<string> =
    "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountAuthority extends string
        ? ReadonlySignerAccount<TAccountAuthority> &
            AccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      TAccountGame extends string
        ? ReadonlyAccount<TAccountGame>
        : TAccountGame,
      TAccountPlayer extends string
        ? WritableAccount<TAccountPlayer>
        : TAccountPlayer,
      TAccountTo extends string ? WritableAccount<TAccountTo> : TAccountTo,
      TAccountVault extends string
        ? WritableAccount<TAccountVault>
        : TAccountVault,
      TAccountUsdcMint extends string
        ? ReadonlyAccount<TAccountUsdcMint>
        : TAccountUsdcMint,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      ...TRemainingAccounts,
    ]
  >;

export type WithdrawInstructionData = {
  discriminator: ReadonlyUint8Array;
  amount: bigint;
};

export type WithdrawInstructionDataArgs = { amount: number | bigint };

export function getWithdrawInstructionDataEncoder(): FixedSizeEncoder<WithdrawInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["amount", getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: WITHDRAW_DISCRIMINATOR }),
  );
}

export function getWithdrawInstructionDataDecoder(): FixedSizeDecoder<WithdrawInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["amount", getU64Decoder()],
  ]);
}

export function getWithdrawInstructionDataCodec(): FixedSizeCodec<
  WithdrawInstructionDataArgs,
  WithdrawInstructionData
> {
  return combineCodec(
    getWithdrawInstructionDataEncoder(),
    getWithdrawInstructionDataDecoder(),
  );
}

export type WithdrawAsyncInput<
  TAccountAuthority extends InstructionSignerInput = InstructionSignerInput,
  TAccountGame extends InstructionAccountInput = InstructionAccountInput,
  TAccountPlayer extends InstructionAccountInput = InstructionAccountInput,
  TAccountTo extends InstructionAccountInput = InstructionAccountInput,
  TAccountVault extends InstructionAccountInput = InstructionAccountInput,
  TAccountUsdcMint extends InstructionAccountInput = InstructionAccountInput,
  TAccountTokenProgram extends InstructionAccountInput =
    InstructionAccountInput,
> = {
  authority: TAccountAuthority;
  game?: TAccountGame;
  player?: TAccountPlayer;
  to: TAccountTo;
  vault: TAccountVault;
  usdcMint: TAccountUsdcMint;
  tokenProgram?: TAccountTokenProgram;
  amount: WithdrawInstructionDataArgs["amount"];
};

export async function getWithdrawInstructionAsync<
  TAccountAuthority extends InstructionSignerInput,
  TAccountGame extends InstructionAccountInput,
  TAccountPlayer extends InstructionAccountInput,
  TAccountTo extends InstructionAccountInput,
  TAccountVault extends InstructionAccountInput,
  TAccountUsdcMint extends InstructionAccountInput,
  TAccountTokenProgram extends InstructionAccountInput,
  TProgramAddress extends Address = typeof SKECH_PROGRAM_ADDRESS,
>(
  input: WithdrawAsyncInput<
    TAccountAuthority,
    TAccountGame,
    TAccountPlayer,
    TAccountTo,
    TAccountVault,
    TAccountUsdcMint,
    TAccountTokenProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  WithdrawInstruction<
    TProgramAddress,
    ResolvedInstructionAccountMeta<
      TAccountAuthority,
      InstructionAccountInputAddress<TAccountAuthority>
    >,
    ResolvedInstructionAccountMeta<
      TAccountGame,
      InstructionAccountInputAddress<TAccountGame>
    >,
    ResolvedInstructionAccountMeta<
      TAccountPlayer,
      InstructionAccountInputAddress<TAccountPlayer>
    >,
    ResolvedInstructionAccountMeta<
      TAccountTo,
      InstructionAccountInputAddress<TAccountTo>
    >,
    ResolvedInstructionAccountMeta<
      TAccountVault,
      InstructionAccountInputAddress<TAccountVault>
    >,
    ResolvedInstructionAccountMeta<
      TAccountUsdcMint,
      InstructionAccountInputAddress<TAccountUsdcMint>
    >,
    ResolvedInstructionAccountMeta<
      TAccountTokenProgram,
      InstructionAccountInputAddress<TAccountTokenProgram>
    >
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? SKECH_PROGRAM_ADDRESS;

  // Account meta helper.
  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");

  // Original accounts.
  const originalAccounts = {
    authority: {
      value: input.authority ?? null,
      isSigner: true,
      isWritable: false,
    },
    game: { value: input.game ?? null, isSigner: false, isWritable: false },
    player: { value: input.player ?? null, isSigner: false, isWritable: true },
    to: { value: input.to ?? null, isSigner: false, isWritable: true },
    vault: { value: input.vault ?? null, isSigner: false, isWritable: true },
    usdcMint: {
      value: input.usdcMint ?? null,
      isSigner: false,
      isWritable: false,
    },
    tokenProgram: {
      value: input.tokenProgram ?? null,
      isSigner: false,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.game.value) {
    accounts.game.value = await findGamePda({ programAddress });
  }
  if (!accounts.player.value) {
    accounts.player.value = await findPlayerPda(
      {
        authority: getAddressFromResolvedInstructionAccount(
          "authority",
          accounts.authority.value,
        ),
      },
      { programAddress },
    );
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }

  return Object.freeze({
    accounts: [
      getAccountMeta("authority", accounts.authority),
      getAccountMeta("game", accounts.game),
      getAccountMeta("player", accounts.player),
      getAccountMeta("to", accounts.to),
      getAccountMeta("vault", accounts.vault),
      getAccountMeta("usdcMint", accounts.usdcMint),
      getAccountMeta("tokenProgram", accounts.tokenProgram),
    ],
    data: getWithdrawInstructionDataEncoder().encode(
      args as WithdrawInstructionDataArgs,
    ),
    programAddress,
  } as WithdrawInstruction<
    TProgramAddress,
    ResolvedInstructionAccountMeta<
      TAccountAuthority,
      InstructionAccountInputAddress<TAccountAuthority>
    >,
    ResolvedInstructionAccountMeta<
      TAccountGame,
      InstructionAccountInputAddress<TAccountGame>
    >,
    ResolvedInstructionAccountMeta<
      TAccountPlayer,
      InstructionAccountInputAddress<TAccountPlayer>
    >,
    ResolvedInstructionAccountMeta<
      TAccountTo,
      InstructionAccountInputAddress<TAccountTo>
    >,
    ResolvedInstructionAccountMeta<
      TAccountVault,
      InstructionAccountInputAddress<TAccountVault>
    >,
    ResolvedInstructionAccountMeta<
      TAccountUsdcMint,
      InstructionAccountInputAddress<TAccountUsdcMint>
    >,
    ResolvedInstructionAccountMeta<
      TAccountTokenProgram,
      InstructionAccountInputAddress<TAccountTokenProgram>
    >
  >);
}

export type WithdrawInput<
  TAccountAuthority extends InstructionSignerInput = InstructionSignerInput,
  TAccountGame extends InstructionAccountInput = InstructionAccountInput,
  TAccountPlayer extends InstructionAccountInput = InstructionAccountInput,
  TAccountTo extends InstructionAccountInput = InstructionAccountInput,
  TAccountVault extends InstructionAccountInput = InstructionAccountInput,
  TAccountUsdcMint extends InstructionAccountInput = InstructionAccountInput,
  TAccountTokenProgram extends InstructionAccountInput =
    InstructionAccountInput,
> = {
  authority: TAccountAuthority;
  game: TAccountGame;
  player: TAccountPlayer;
  to: TAccountTo;
  vault: TAccountVault;
  usdcMint: TAccountUsdcMint;
  tokenProgram?: TAccountTokenProgram;
  amount: WithdrawInstructionDataArgs["amount"];
};

export function getWithdrawInstruction<
  TAccountAuthority extends InstructionSignerInput,
  TAccountGame extends InstructionAccountInput,
  TAccountPlayer extends InstructionAccountInput,
  TAccountTo extends InstructionAccountInput,
  TAccountVault extends InstructionAccountInput,
  TAccountUsdcMint extends InstructionAccountInput,
  TAccountTokenProgram extends InstructionAccountInput,
  TProgramAddress extends Address = typeof SKECH_PROGRAM_ADDRESS,
>(
  input: WithdrawInput<
    TAccountAuthority,
    TAccountGame,
    TAccountPlayer,
    TAccountTo,
    TAccountVault,
    TAccountUsdcMint,
    TAccountTokenProgram
  >,
  config?: { programAddress?: TProgramAddress },
): WithdrawInstruction<
  TProgramAddress,
  ResolvedInstructionAccountMeta<
    TAccountAuthority,
    InstructionAccountInputAddress<TAccountAuthority>
  >,
  ResolvedInstructionAccountMeta<
    TAccountGame,
    InstructionAccountInputAddress<TAccountGame>
  >,
  ResolvedInstructionAccountMeta<
    TAccountPlayer,
    InstructionAccountInputAddress<TAccountPlayer>
  >,
  ResolvedInstructionAccountMeta<
    TAccountTo,
    InstructionAccountInputAddress<TAccountTo>
  >,
  ResolvedInstructionAccountMeta<
    TAccountVault,
    InstructionAccountInputAddress<TAccountVault>
  >,
  ResolvedInstructionAccountMeta<
    TAccountUsdcMint,
    InstructionAccountInputAddress<TAccountUsdcMint>
  >,
  ResolvedInstructionAccountMeta<
    TAccountTokenProgram,
    InstructionAccountInputAddress<TAccountTokenProgram>
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? SKECH_PROGRAM_ADDRESS;

  // Account meta helper.
  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");

  // Original accounts.
  const originalAccounts = {
    authority: {
      value: input.authority ?? null,
      isSigner: true,
      isWritable: false,
    },
    game: { value: input.game ?? null, isSigner: false, isWritable: false },
    player: { value: input.player ?? null, isSigner: false, isWritable: true },
    to: { value: input.to ?? null, isSigner: false, isWritable: true },
    vault: { value: input.vault ?? null, isSigner: false, isWritable: true },
    usdcMint: {
      value: input.usdcMint ?? null,
      isSigner: false,
      isWritable: false,
    },
    tokenProgram: {
      value: input.tokenProgram ?? null,
      isSigner: false,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }

  return Object.freeze({
    accounts: [
      getAccountMeta("authority", accounts.authority),
      getAccountMeta("game", accounts.game),
      getAccountMeta("player", accounts.player),
      getAccountMeta("to", accounts.to),
      getAccountMeta("vault", accounts.vault),
      getAccountMeta("usdcMint", accounts.usdcMint),
      getAccountMeta("tokenProgram", accounts.tokenProgram),
    ],
    data: getWithdrawInstructionDataEncoder().encode(
      args as WithdrawInstructionDataArgs,
    ),
    programAddress,
  } as WithdrawInstruction<
    TProgramAddress,
    ResolvedInstructionAccountMeta<
      TAccountAuthority,
      InstructionAccountInputAddress<TAccountAuthority>
    >,
    ResolvedInstructionAccountMeta<
      TAccountGame,
      InstructionAccountInputAddress<TAccountGame>
    >,
    ResolvedInstructionAccountMeta<
      TAccountPlayer,
      InstructionAccountInputAddress<TAccountPlayer>
    >,
    ResolvedInstructionAccountMeta<
      TAccountTo,
      InstructionAccountInputAddress<TAccountTo>
    >,
    ResolvedInstructionAccountMeta<
      TAccountVault,
      InstructionAccountInputAddress<TAccountVault>
    >,
    ResolvedInstructionAccountMeta<
      TAccountUsdcMint,
      InstructionAccountInputAddress<TAccountUsdcMint>
    >,
    ResolvedInstructionAccountMeta<
      TAccountTokenProgram,
      InstructionAccountInputAddress<TAccountTokenProgram>
    >
  >);
}

export type ParsedWithdrawInstruction<
  TProgram extends string = typeof SKECH_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    authority: TAccountMetas[0];
    game: TAccountMetas[1];
    player: TAccountMetas[2];
    to: TAccountMetas[3];
    vault: TAccountMetas[4];
    usdcMint: TAccountMetas[5];
    tokenProgram: TAccountMetas[6];
  };
  data: WithdrawInstructionData;
};

export function parseWithdrawInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedWithdrawInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 7) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 7,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      authority: getNextAccount(),
      game: getNextAccount(),
      player: getNextAccount(),
      to: getNextAccount(),
      vault: getNextAccount(),
      usdcMint: getNextAccount(),
      tokenProgram: getNextAccount(),
    },
    data: getWithdrawInstructionDataDecoder().decode(instruction.data),
  };
}
