/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export type BarInput = {
  second: bigint;
  prevClose: bigint;
  high: bigint;
  low: bigint;
  close: bigint;
};

export type BarInputArgs = {
  second: number | bigint;
  prevClose: number | bigint;
  high: number | bigint;
  low: number | bigint;
  close: number | bigint;
};

export function getBarInputEncoder(): FixedSizeEncoder<BarInputArgs> {
  return getStructEncoder([
    ["second", getI64Encoder()],
    ["prevClose", getU64Encoder()],
    ["high", getU64Encoder()],
    ["low", getU64Encoder()],
    ["close", getU64Encoder()],
  ]);
}

export function getBarInputDecoder(): FixedSizeDecoder<BarInput> {
  return getStructDecoder([
    ["second", getI64Decoder()],
    ["prevClose", getU64Decoder()],
    ["high", getU64Decoder()],
    ["low", getU64Decoder()],
    ["close", getU64Decoder()],
  ]);
}

export function getBarInputCodec(): FixedSizeCodec<BarInputArgs, BarInput> {
  return combineCodec(getBarInputEncoder(), getBarInputDecoder());
}
