/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

/**
 * A band of a bet as placed: `lo` to `hi` (8 decimals, on the grid), `second` seconds after it opens, staking
 * `stake` and paying `rung` (x100) if the price reaches it.
 */
export type BetSection = {
  second: number;
  lo: bigint;
  hi: bigint;
  stake: bigint;
  rung: number;
};

export type BetSectionArgs = {
  second: number;
  lo: number | bigint;
  hi: number | bigint;
  stake: number | bigint;
  rung: number;
};

export function getBetSectionEncoder(): FixedSizeEncoder<BetSectionArgs> {
  return getStructEncoder([
    ["second", getU8Encoder()],
    ["lo", getU64Encoder()],
    ["hi", getU64Encoder()],
    ["stake", getU64Encoder()],
    ["rung", getU16Encoder()],
  ]);
}

export function getBetSectionDecoder(): FixedSizeDecoder<BetSection> {
  return getStructDecoder([
    ["second", getU8Decoder()],
    ["lo", getU64Decoder()],
    ["hi", getU64Decoder()],
    ["stake", getU64Decoder()],
    ["rung", getU16Decoder()],
  ]);
}

export function getBetSectionCodec(): FixedSizeCodec<
  BetSectionArgs,
  BetSection
> {
  return combineCodec(getBetSectionEncoder(), getBetSectionDecoder());
}
