/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  getU32Decoder,
  getU32Encoder,
  getU64Decoder,
  getU64Encoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export type Config = {
  /** Of every stake, as it is placed, to the house. */
  feeBps: number;
  /** Of every hit's profit, to the house. */
  profitFeeBps: number;
  /** Of an IOU's growth, to whoever redeems it for someone else. */
  sweepBps: number;
  /** How late after its opening second the oracle may have received a piece, ms. */
  lateMs: number;
  /** How far from its opening second a placement may land, and how early a second may be posted, ms. */
  placeGraceMs: number;
  /** How old the price a player saw may be when the oracle received the piece, ms. */
  maxPriceAgeMs: number;
  /** What a dot may cost, USDC e6. */
  minPerDot: bigint;
  maxPerDot: bigint;
  /** The most one piece may stake, USDC e6. */
  maxPieceStake: bigint;
  /** The least a partial IOU redemption may be worth, USDC e6. */
  minRedeem: bigint;
  /** How far ahead a session may be set to expire, seconds. */
  maxSessionSecs: bigint;
};

export type ConfigArgs = {
  /** Of every stake, as it is placed, to the house. */
  feeBps: number;
  /** Of every hit's profit, to the house. */
  profitFeeBps: number;
  /** Of an IOU's growth, to whoever redeems it for someone else. */
  sweepBps: number;
  /** How late after its opening second the oracle may have received a piece, ms. */
  lateMs: number;
  /** How far from its opening second a placement may land, and how early a second may be posted, ms. */
  placeGraceMs: number;
  /** How old the price a player saw may be when the oracle received the piece, ms. */
  maxPriceAgeMs: number;
  /** What a dot may cost, USDC e6. */
  minPerDot: number | bigint;
  maxPerDot: number | bigint;
  /** The most one piece may stake, USDC e6. */
  maxPieceStake: number | bigint;
  /** The least a partial IOU redemption may be worth, USDC e6. */
  minRedeem: number | bigint;
  /** How far ahead a session may be set to expire, seconds. */
  maxSessionSecs: number | bigint;
};

export function getConfigEncoder(): FixedSizeEncoder<ConfigArgs> {
  return getStructEncoder([
    ["feeBps", getU16Encoder()],
    ["profitFeeBps", getU16Encoder()],
    ["sweepBps", getU16Encoder()],
    ["lateMs", getU32Encoder()],
    ["placeGraceMs", getU32Encoder()],
    ["maxPriceAgeMs", getU32Encoder()],
    ["minPerDot", getU64Encoder()],
    ["maxPerDot", getU64Encoder()],
    ["maxPieceStake", getU64Encoder()],
    ["minRedeem", getU64Encoder()],
    ["maxSessionSecs", getI64Encoder()],
  ]);
}

export function getConfigDecoder(): FixedSizeDecoder<Config> {
  return getStructDecoder([
    ["feeBps", getU16Decoder()],
    ["profitFeeBps", getU16Decoder()],
    ["sweepBps", getU16Decoder()],
    ["lateMs", getU32Decoder()],
    ["placeGraceMs", getU32Decoder()],
    ["maxPriceAgeMs", getU32Decoder()],
    ["minPerDot", getU64Decoder()],
    ["maxPerDot", getU64Decoder()],
    ["maxPieceStake", getU64Decoder()],
    ["minRedeem", getU64Decoder()],
    ["maxSessionSecs", getI64Decoder()],
  ]);
}

export function getConfigCodec(): FixedSizeCodec<ConfigArgs, Config> {
  return combineCodec(getConfigEncoder(), getConfigDecoder());
}
