/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  getU32Decoder,
  getU32Encoder,
  getU64Decoder,
  getU64Encoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

/** SKT's terms, set beside `Config`: `Config` lives in `Game`, whose layout stays as it is on chain. */
export type RewardsConfig = {
  /** Of every stake, to SKT holders: part of `Config::fee_bps`, never more. */
  holderFeeBps: number;
  /** Of every hit's profit, to SKT holders: part of `Config::profit_fee_bps`, never more. */
  holderProfitFeeBps: number;
  /**
   * `S` in the mint curve, USDC e6: at tracked gain G a dollar of basis mints 100 · (S / (S + G))² SKT. Fixed once
   * anything has minted.
   */
  mintScale: bigint;
  /** SKT's half-life, seconds: a balance halves every this long, so a player keeps their share only by playing on. */
  halfLifeSecs: number;
  /** No mint takes a wallet past this share of all shares, bps (10,000: no cap)… */
  walletCapBps: number;
  /** …or past that share of this much SKT (e6), whichever is more: so the first players mint while there is little. */
  capFloor: bigint;
  /** USDC e6 the pool keeps, over what every live bet could pay, before any of its surplus is shared with holders. */
  surplusReserve: bigint;
  /** Of the pool's surplus, to SKT holders, bps; the rest to the treasury. */
  surplusHolderBps: number;
};

export type RewardsConfigArgs = {
  /** Of every stake, to SKT holders: part of `Config::fee_bps`, never more. */
  holderFeeBps: number;
  /** Of every hit's profit, to SKT holders: part of `Config::profit_fee_bps`, never more. */
  holderProfitFeeBps: number;
  /**
   * `S` in the mint curve, USDC e6: at tracked gain G a dollar of basis mints 100 · (S / (S + G))² SKT. Fixed once
   * anything has minted.
   */
  mintScale: number | bigint;
  /** SKT's half-life, seconds: a balance halves every this long, so a player keeps their share only by playing on. */
  halfLifeSecs: number;
  /** No mint takes a wallet past this share of all shares, bps (10,000: no cap)… */
  walletCapBps: number;
  /** …or past that share of this much SKT (e6), whichever is more: so the first players mint while there is little. */
  capFloor: number | bigint;
  /** USDC e6 the pool keeps, over what every live bet could pay, before any of its surplus is shared with holders. */
  surplusReserve: number | bigint;
  /** Of the pool's surplus, to SKT holders, bps; the rest to the treasury. */
  surplusHolderBps: number;
};

export function getRewardsConfigEncoder(): FixedSizeEncoder<RewardsConfigArgs> {
  return getStructEncoder([
    ["holderFeeBps", getU16Encoder()],
    ["holderProfitFeeBps", getU16Encoder()],
    ["mintScale", getU64Encoder()],
    ["halfLifeSecs", getU32Encoder()],
    ["walletCapBps", getU16Encoder()],
    ["capFloor", getU64Encoder()],
    ["surplusReserve", getU64Encoder()],
    ["surplusHolderBps", getU16Encoder()],
  ]);
}

export function getRewardsConfigDecoder(): FixedSizeDecoder<RewardsConfig> {
  return getStructDecoder([
    ["holderFeeBps", getU16Decoder()],
    ["holderProfitFeeBps", getU16Decoder()],
    ["mintScale", getU64Decoder()],
    ["halfLifeSecs", getU32Decoder()],
    ["walletCapBps", getU16Decoder()],
    ["capFloor", getU64Decoder()],
    ["surplusReserve", getU64Decoder()],
    ["surplusHolderBps", getU16Decoder()],
  ]);
}

export function getRewardsConfigCodec(): FixedSizeCodec<
  RewardsConfigArgs,
  RewardsConfig
> {
  return combineCodec(getRewardsConfigEncoder(), getRewardsConfigDecoder());
}
