/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  getU64Decoder,
  getU64Encoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

/** SKT's terms, set beside `Config`: `Config` lives in `Game`, whose layout stays as it is on chain. */
export type RewardsConfig = {
  /** Of every stake, to SKT holders: part of `Config::fee_bps`, never more. */
  holderFeeBps: number;
  /** Of every hit's profit, to SKT holders: part of `Config::profit_fee_bps`, never more. */
  holderProfitFeeBps: number;
  /** `S` in the mint curve, USDC e6: at tracked gain G a dollar of new net loss mints 100 · (S / (S + G))² SKT. */
  mintScale: bigint;
};

export type RewardsConfigArgs = {
  /** Of every stake, to SKT holders: part of `Config::fee_bps`, never more. */
  holderFeeBps: number;
  /** Of every hit's profit, to SKT holders: part of `Config::profit_fee_bps`, never more. */
  holderProfitFeeBps: number;
  /** `S` in the mint curve, USDC e6: at tracked gain G a dollar of new net loss mints 100 · (S / (S + G))² SKT. */
  mintScale: number | bigint;
};

export function getRewardsConfigEncoder(): FixedSizeEncoder<RewardsConfigArgs> {
  return getStructEncoder([
    ["holderFeeBps", getU16Encoder()],
    ["holderProfitFeeBps", getU16Encoder()],
    ["mintScale", getU64Encoder()],
  ]);
}

export function getRewardsConfigDecoder(): FixedSizeDecoder<RewardsConfig> {
  return getStructDecoder([
    ["holderFeeBps", getU16Decoder()],
    ["holderProfitFeeBps", getU16Decoder()],
    ["mintScale", getU64Decoder()],
  ]);
}

export function getRewardsConfigCodec(): FixedSizeCodec<
  RewardsConfigArgs,
  RewardsConfig
> {
  return combineCodec(getRewardsConfigEncoder(), getRewardsConfigDecoder());
}
