/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  getU32Decoder,
  getU32Encoder,
  getU8Decoder,
  getU8Encoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

/**
 * A band, as signed: `lo` and `hi` are counted in grid units (so they sit on the grid by construction), `stake` in
 * USDC e6. 11 bytes.
 */
export type SectionArg = {
  /** Seconds after the piece opens, 1 to 30. */
  second: number;
  /** The band's bottom, in units of `unit` from zero. */
  lo: number;
  /** Its height, in units. */
  width: number;
  stake: number;
};

export type SectionArgArgs = SectionArg;

export function getSectionArgEncoder(): FixedSizeEncoder<SectionArgArgs> {
  return getStructEncoder([
    ["second", getU8Encoder()],
    ["lo", getU32Encoder()],
    ["width", getU16Encoder()],
    ["stake", getU32Encoder()],
  ]);
}

export function getSectionArgDecoder(): FixedSizeDecoder<SectionArg> {
  return getStructDecoder([
    ["second", getU8Decoder()],
    ["lo", getU32Decoder()],
    ["width", getU16Decoder()],
    ["stake", getU32Decoder()],
  ]);
}

export function getSectionArgCodec(): FixedSizeCodec<
  SectionArgArgs,
  SectionArg
> {
  return combineCodec(getSectionArgEncoder(), getSectionArgDecoder());
}
