/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

/**
 * A player's session key: an Ed25519 key their app keeps, which may place pieces for them, up to an allowance,
 * until it expires. It can never withdraw.
 */
export type Session = {
  key: Address;
  /** Unix seconds, by the chain's clock. */
  validUntil: bigint;
  /** USDC e6 the session may still stake. */
  allowance: bigint;
};

export type SessionArgs = {
  key: Address;
  /** Unix seconds, by the chain's clock. */
  validUntil: number | bigint;
  /** USDC e6 the session may still stake. */
  allowance: number | bigint;
};

export function getSessionEncoder(): FixedSizeEncoder<SessionArgs> {
  return getStructEncoder([
    ["key", getAddressEncoder()],
    ["validUntil", getI64Encoder()],
    ["allowance", getU64Encoder()],
  ]);
}

export function getSessionDecoder(): FixedSizeDecoder<Session> {
  return getStructDecoder([
    ["key", getAddressDecoder()],
    ["validUntil", getI64Decoder()],
    ["allowance", getU64Decoder()],
  ]);
}

export function getSessionCodec(): FixedSizeCodec<SessionArgs, Session> {
  return combineCodec(getSessionEncoder(), getSessionDecoder());
}
