/**
 * The ladder as `@skech/core` computes it, printed for both chains' tests to check their own against, row for row:
 * `solana/tests/src/ladder.rs` and `evm/test/LadderVectors.t.sol`. So core, Solana and the EVM contracts are held to one table.
 *
 *   bun packages/contracts/solana/tests/vectors/ladder.ts          (writes ladder.json)
 *   bun packages/contracts/solana/tests/vectors/ladder.ts --check  (fails if ladder.json is out of date)
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { rungE2 } from "@skech/core/chain";

const chances = [1, 999, 1_000_000, 5_000_000, 7_812_500, 10_000_000, 20_000_000, 33_333_333, 50_000_000, 83_000_000, 100_000_000, 124_999_999, 125_000_000, 200_000_000, 333_333_333, 500_000_000, 664_000_000, 750_000_000, 850_000_000, 905_454_545, 950_000_000, 990_000_000, 999_999_999, 1_000_000_000];
const momenta = [0, 1, 250_000, -500_000, 1_000_000, -1_999_999, 2_000_000, 5_000_000, -40_000_000];
// Every third difficulty from 0, and 49, 50 and 51 around the least: under it is priced as it.
const difficulties = [...new Set([...Array.from({ length: 34 }, (_, i) => i * 3), 49, 50, 51])].sort((a, b) => a - b);
// By column, one entry a row: Foundry reads a JSON array only when every entry is one type.
const rows = { chance: [] as number[], difficulty: [] as number[], withIt: [] as boolean[], momentum: [] as number[], rung: [] as number[] };
for (const c of chances) {
  for (const d of difficulties) {
    for (const w of [false, true]) {
      for (const m of momenta) {
        rows.chance.push(c);
        rows.difficulty.push(d);
        rows.withIt.push(w);
        rows.momentum.push(m);
        rows.rung.push(rungE2(c, d, w, m));
      }
    }
  }
}
const json = JSON.stringify({ about: "Generated by packages/contracts/solana/tests/vectors/ladder.ts from @skech/core. Do not edit.", ...rows }) + "\n";

const path = join(import.meta.dir, "ladder.json");
if (process.argv.includes("--check")) {
  let committed = "";
  try {
    committed = readFileSync(path, "utf8");
  } catch {}
  if (committed !== json) {
    console.error(`out of date: ${path}; run bun packages/contracts/solana/tests/vectors/ladder.ts`);
    process.exit(1);
  }
  console.log("ladder vectors are up to date");
} else {
  writeFileSync(path, json);
  console.log(`${rows.rung.length} rows`);
}
