/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertIsInstructionWithAccounts,
  containsBytes,
  extendClient,
  fixEncoderSize,
  getBytesEncoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__FAILED_TO_IDENTIFY_ACCOUNT,
  SOLANA_ERROR__PROGRAM_CLIENTS__FAILED_TO_IDENTIFY_INSTRUCTION,
  SOLANA_ERROR__PROGRAM_CLIENTS__UNRECOGNIZED_INSTRUCTION_TYPE,
  SolanaError,
  type Address,
  type ClientWithPayer,
  type ClientWithRpc,
  type ClientWithTransactionPlanning,
  type ClientWithTransactionSending,
  type ExtendedClient,
  type GetAccountInfoApi,
  type GetMultipleAccountsApi,
  type Instruction,
  type InstructionWithData,
  type ReadonlyUint8Array,
} from "@solana/kit";
import {
  addSelfFetchFunctions,
  addSelfPlanAndSendFunctions,
  type SelfFetchFunctions,
  type SelfPlanAndSendFunctions,
} from "@solana/kit/program-client-core";
import {
  getBarsCodec,
  getGameCodec,
  getMarketCodec,
  getPlayerCodec,
  getPoolCodec,
  type Bars,
  type BarsArgs,
  type Game,
  type GameArgs,
  type Market,
  type MarketArgs,
  type Player,
  type PlayerArgs,
  type Pool,
  type PoolArgs,
} from "../accounts";
import {
  getAcceptAdminInstructionAsync,
  getCollectFeesInstructionAsync,
  getDepositInstructionAsync,
  getExpireInstructionAsync,
  getInitializeInstructionAsync,
  getInitMarketInstructionAsync,
  getPlaceInstructionAsync,
  getPostBarAndSettleInstructionAsync,
  getPostBarInstructionAsync,
  getProposeAdminInstructionAsync,
  getRedeemHouseInstructionAsync,
  getRedeemInstructionAsync,
  getRevokeSessionInstructionAsync,
  getSetConfigInstructionAsync,
  getSetIouRateInstructionAsync,
  getSetMarketInstructionAsync,
  getSetOracleInstructionAsync,
  getSetPausedInstructionAsync,
  getSetSessionInstructionAsync,
  getSettleInstructionAsync,
  getSetTreasuryInstructionAsync,
  getSweepInstructionAsync,
  getWithdrawInstructionAsync,
  parseAcceptAdminInstruction,
  parseCollectFeesInstruction,
  parseDepositInstruction,
  parseExpireInstruction,
  parseInitializeInstruction,
  parseInitMarketInstruction,
  parsePlaceInstruction,
  parsePostBarAndSettleInstruction,
  parsePostBarInstruction,
  parseProposeAdminInstruction,
  parseRedeemHouseInstruction,
  parseRedeemInstruction,
  parseRevokeSessionInstruction,
  parseSetConfigInstruction,
  parseSetIouRateInstruction,
  parseSetMarketInstruction,
  parseSetOracleInstruction,
  parseSetPausedInstruction,
  parseSetSessionInstruction,
  parseSettleInstruction,
  parseSetTreasuryInstruction,
  parseSweepInstruction,
  parseWithdrawInstruction,
  type AcceptAdminAsyncInput,
  type CollectFeesAsyncInput,
  type DepositAsyncInput,
  type ExpireAsyncInput,
  type InitializeAsyncInput,
  type InitMarketAsyncInput,
  type ParsedAcceptAdminInstruction,
  type ParsedCollectFeesInstruction,
  type ParsedDepositInstruction,
  type ParsedExpireInstruction,
  type ParsedInitializeInstruction,
  type ParsedInitMarketInstruction,
  type ParsedPlaceInstruction,
  type ParsedPostBarAndSettleInstruction,
  type ParsedPostBarInstruction,
  type ParsedProposeAdminInstruction,
  type ParsedRedeemHouseInstruction,
  type ParsedRedeemInstruction,
  type ParsedRevokeSessionInstruction,
  type ParsedSetConfigInstruction,
  type ParsedSetIouRateInstruction,
  type ParsedSetMarketInstruction,
  type ParsedSetOracleInstruction,
  type ParsedSetPausedInstruction,
  type ParsedSetSessionInstruction,
  type ParsedSettleInstruction,
  type ParsedSetTreasuryInstruction,
  type ParsedSweepInstruction,
  type ParsedWithdrawInstruction,
  type PlaceAsyncInput,
  type PostBarAndSettleAsyncInput,
  type PostBarAsyncInput,
  type ProposeAdminAsyncInput,
  type RedeemAsyncInput,
  type RedeemHouseAsyncInput,
  type RevokeSessionAsyncInput,
  type SetConfigAsyncInput,
  type SetIouRateAsyncInput,
  type SetMarketAsyncInput,
  type SetOracleAsyncInput,
  type SetPausedAsyncInput,
  type SetSessionAsyncInput,
  type SettleAsyncInput,
  type SetTreasuryAsyncInput,
  type SweepAsyncInput,
  type WithdrawAsyncInput,
} from "../instructions";
import {
  findCallerPlayerPda,
  findGamePda,
  findPlayerPda,
  findPoolPda,
} from "../pdas";

export const SKECH_PROGRAM_ADDRESS =
  "2k9WY5YR357AGVVoBW6ouFHijEypTj8953fzSdD7HfRV" as Address<"2k9WY5YR357AGVVoBW6ouFHijEypTj8953fzSdD7HfRV">;

export enum SkechAccount {
  Bars,
  Game,
  Market,
  Player,
  Pool,
}

export function identifySkechAccount(
  account: { data: ReadonlyUint8Array } | ReadonlyUint8Array,
): SkechAccount {
  const data = "data" in account ? account.data : account;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([35, 183, 0, 217, 23, 243, 155, 5]),
      ),
      0,
    )
  ) {
    return SkechAccount.Bars;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([27, 90, 166, 125, 74, 100, 121, 18]),
      ),
      0,
    )
  ) {
    return SkechAccount.Game;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([219, 190, 213, 55, 0, 227, 198, 154]),
      ),
      0,
    )
  ) {
    return SkechAccount.Market;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([205, 222, 112, 7, 165, 155, 206, 218]),
      ),
      0,
    )
  ) {
    return SkechAccount.Player;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([241, 154, 109, 4, 17, 177, 109, 188]),
      ),
      0,
    )
  ) {
    return SkechAccount.Pool;
  }
  throw new SolanaError(
    SOLANA_ERROR__PROGRAM_CLIENTS__FAILED_TO_IDENTIFY_ACCOUNT,
    { accountData: data, programName: "skech" },
  );
}

export enum SkechEvent {
  AdminProposed,
  AdminSet,
  BarPosted,
  ConfigSet,
  Deposited,
  FeesCollected,
  IouRateSet,
  MarketSet,
  OracleSet,
  Owed,
  PausedSet,
  Placed,
  Redeemed,
  SessionRevoked,
  SessionSet,
  Settled,
  TreasurySet,
  Withdrawn,
}

export function identifySkechEvent(
  event: { data: ReadonlyUint8Array } | ReadonlyUint8Array,
): SkechEvent {
  const data = "data" in event ? event.data : event;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([129, 249, 226, 227, 199, 82, 110, 243]),
      ),
      0,
    )
  ) {
    return SkechEvent.AdminProposed;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([157, 245, 205, 226, 118, 125, 183, 97]),
      ),
      0,
    )
  ) {
    return SkechEvent.AdminSet;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([205, 222, 196, 244, 85, 62, 55, 66]),
      ),
      0,
    )
  ) {
    return SkechEvent.BarPosted;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([15, 104, 59, 16, 236, 241, 8, 6]),
      ),
      0,
    )
  ) {
    return SkechEvent.ConfigSet;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([111, 141, 26, 45, 161, 35, 100, 57]),
      ),
      0,
    )
  ) {
    return SkechEvent.Deposited;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([233, 23, 117, 225, 107, 178, 254, 8]),
      ),
      0,
    )
  ) {
    return SkechEvent.FeesCollected;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([252, 90, 54, 68, 6, 233, 252, 130]),
      ),
      0,
    )
  ) {
    return SkechEvent.IouRateSet;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([64, 19, 78, 233, 226, 142, 234, 83]),
      ),
      0,
    )
  ) {
    return SkechEvent.MarketSet;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([115, 135, 7, 243, 213, 60, 174, 119]),
      ),
      0,
    )
  ) {
    return SkechEvent.OracleSet;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([156, 166, 181, 196, 145, 101, 94, 71]),
      ),
      0,
    )
  ) {
    return SkechEvent.Owed;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([171, 125, 127, 156, 233, 81, 68, 66]),
      ),
      0,
    )
  ) {
    return SkechEvent.PausedSet;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([182, 12, 15, 19, 155, 29, 175, 156]),
      ),
      0,
    )
  ) {
    return SkechEvent.Placed;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([14, 29, 183, 71, 31, 165, 107, 38]),
      ),
      0,
    )
  ) {
    return SkechEvent.Redeemed;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([90, 48, 35, 234, 203, 192, 126, 211]),
      ),
      0,
    )
  ) {
    return SkechEvent.SessionRevoked;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([217, 40, 191, 250, 153, 135, 184, 144]),
      ),
      0,
    )
  ) {
    return SkechEvent.SessionSet;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([232, 210, 40, 17, 142, 124, 145, 238]),
      ),
      0,
    )
  ) {
    return SkechEvent.Settled;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([69, 231, 163, 135, 254, 194, 109, 166]),
      ),
      0,
    )
  ) {
    return SkechEvent.TreasurySet;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([20, 89, 223, 198, 194, 124, 219, 13]),
      ),
      0,
    )
  ) {
    return SkechEvent.Withdrawn;
  }
  throw new Error(
    "The provided event could not be identified as a skech event.",
  );
}

export enum SkechInstruction {
  AcceptAdmin,
  CollectFees,
  Deposit,
  Expire,
  InitMarket,
  Initialize,
  Place,
  PostBar,
  PostBarAndSettle,
  ProposeAdmin,
  Redeem,
  RedeemHouse,
  RevokeSession,
  SetConfig,
  SetIouRate,
  SetMarket,
  SetOracle,
  SetPaused,
  SetSession,
  SetTreasury,
  Settle,
  Sweep,
  Withdraw,
}

export function identifySkechInstruction(
  instruction: { data: ReadonlyUint8Array } | ReadonlyUint8Array,
): SkechInstruction {
  const data = "data" in instruction ? instruction.data : instruction;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([112, 42, 45, 90, 116, 181, 13, 170]),
      ),
      0,
    )
  ) {
    return SkechInstruction.AcceptAdmin;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([164, 152, 207, 99, 30, 186, 19, 182]),
      ),
      0,
    )
  ) {
    return SkechInstruction.CollectFees;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([242, 35, 198, 137, 82, 225, 242, 182]),
      ),
      0,
    )
  ) {
    return SkechInstruction.Deposit;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([243, 83, 205, 58, 57, 201, 247, 146]),
      ),
      0,
    )
  ) {
    return SkechInstruction.Expire;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([33, 253, 15, 116, 89, 25, 127, 236]),
      ),
      0,
    )
  ) {
    return SkechInstruction.InitMarket;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([175, 175, 109, 31, 13, 152, 155, 237]),
      ),
      0,
    )
  ) {
    return SkechInstruction.Initialize;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([143, 53, 56, 40, 41, 16, 5, 75]),
      ),
      0,
    )
  ) {
    return SkechInstruction.Place;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([126, 226, 63, 169, 86, 216, 167, 210]),
      ),
      0,
    )
  ) {
    return SkechInstruction.PostBar;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([124, 167, 27, 224, 168, 50, 162, 170]),
      ),
      0,
    )
  ) {
    return SkechInstruction.PostBarAndSettle;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([121, 214, 199, 212, 87, 39, 117, 234]),
      ),
      0,
    )
  ) {
    return SkechInstruction.ProposeAdmin;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([184, 12, 86, 149, 70, 196, 97, 225]),
      ),
      0,
    )
  ) {
    return SkechInstruction.Redeem;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([143, 146, 67, 5, 57, 3, 254, 31]),
      ),
      0,
    )
  ) {
    return SkechInstruction.RedeemHouse;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([86, 92, 198, 120, 144, 2, 7, 194]),
      ),
      0,
    )
  ) {
    return SkechInstruction.RevokeSession;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([108, 158, 154, 175, 212, 98, 52, 66]),
      ),
      0,
    )
  ) {
    return SkechInstruction.SetConfig;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([180, 95, 213, 183, 110, 69, 85, 189]),
      ),
      0,
    )
  ) {
    return SkechInstruction.SetIouRate;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([24, 133, 119, 187, 28, 115, 163, 81]),
      ),
      0,
    )
  ) {
    return SkechInstruction.SetMarket;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([186, 128, 81, 104, 74, 79, 18, 224]),
      ),
      0,
    )
  ) {
    return SkechInstruction.SetOracle;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([91, 60, 125, 192, 176, 225, 166, 218]),
      ),
      0,
    )
  ) {
    return SkechInstruction.SetPaused;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([156, 135, 126, 111, 184, 206, 194, 141]),
      ),
      0,
    )
  ) {
    return SkechInstruction.SetSession;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([57, 97, 196, 95, 195, 206, 106, 136]),
      ),
      0,
    )
  ) {
    return SkechInstruction.SetTreasury;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([175, 42, 185, 87, 144, 131, 102, 212]),
      ),
      0,
    )
  ) {
    return SkechInstruction.Settle;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([40, 23, 234, 175, 14, 61, 154, 177]),
      ),
      0,
    )
  ) {
    return SkechInstruction.Sweep;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([183, 18, 70, 156, 148, 109, 161, 34]),
      ),
      0,
    )
  ) {
    return SkechInstruction.Withdraw;
  }
  throw new SolanaError(
    SOLANA_ERROR__PROGRAM_CLIENTS__FAILED_TO_IDENTIFY_INSTRUCTION,
    { instructionData: data, programName: "skech" },
  );
}

export type ParsedSkechInstruction<
  TProgram extends string = "2k9WY5YR357AGVVoBW6ouFHijEypTj8953fzSdD7HfRV",
> =
  | ({
      instructionType: SkechInstruction.AcceptAdmin;
    } & ParsedAcceptAdminInstruction<TProgram>)
  | ({
      instructionType: SkechInstruction.CollectFees;
    } & ParsedCollectFeesInstruction<TProgram>)
  | ({
      instructionType: SkechInstruction.Deposit;
    } & ParsedDepositInstruction<TProgram>)
  | ({
      instructionType: SkechInstruction.Expire;
    } & ParsedExpireInstruction<TProgram>)
  | ({
      instructionType: SkechInstruction.InitMarket;
    } & ParsedInitMarketInstruction<TProgram>)
  | ({
      instructionType: SkechInstruction.Initialize;
    } & ParsedInitializeInstruction<TProgram>)
  | ({
      instructionType: SkechInstruction.Place;
    } & ParsedPlaceInstruction<TProgram>)
  | ({
      instructionType: SkechInstruction.PostBar;
    } & ParsedPostBarInstruction<TProgram>)
  | ({
      instructionType: SkechInstruction.PostBarAndSettle;
    } & ParsedPostBarAndSettleInstruction<TProgram>)
  | ({
      instructionType: SkechInstruction.ProposeAdmin;
    } & ParsedProposeAdminInstruction<TProgram>)
  | ({
      instructionType: SkechInstruction.Redeem;
    } & ParsedRedeemInstruction<TProgram>)
  | ({
      instructionType: SkechInstruction.RedeemHouse;
    } & ParsedRedeemHouseInstruction<TProgram>)
  | ({
      instructionType: SkechInstruction.RevokeSession;
    } & ParsedRevokeSessionInstruction<TProgram>)
  | ({
      instructionType: SkechInstruction.SetConfig;
    } & ParsedSetConfigInstruction<TProgram>)
  | ({
      instructionType: SkechInstruction.SetIouRate;
    } & ParsedSetIouRateInstruction<TProgram>)
  | ({
      instructionType: SkechInstruction.SetMarket;
    } & ParsedSetMarketInstruction<TProgram>)
  | ({
      instructionType: SkechInstruction.SetOracle;
    } & ParsedSetOracleInstruction<TProgram>)
  | ({
      instructionType: SkechInstruction.SetPaused;
    } & ParsedSetPausedInstruction<TProgram>)
  | ({
      instructionType: SkechInstruction.SetSession;
    } & ParsedSetSessionInstruction<TProgram>)
  | ({
      instructionType: SkechInstruction.SetTreasury;
    } & ParsedSetTreasuryInstruction<TProgram>)
  | ({
      instructionType: SkechInstruction.Settle;
    } & ParsedSettleInstruction<TProgram>)
  | ({
      instructionType: SkechInstruction.Sweep;
    } & ParsedSweepInstruction<TProgram>)
  | ({
      instructionType: SkechInstruction.Withdraw;
    } & ParsedWithdrawInstruction<TProgram>);

export function parseSkechInstruction<TProgram extends string>(
  instruction: Instruction<TProgram> & InstructionWithData<ReadonlyUint8Array>,
): ParsedSkechInstruction<TProgram> {
  const instructionType = identifySkechInstruction(instruction);
  switch (instructionType) {
    case SkechInstruction.AcceptAdmin: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: SkechInstruction.AcceptAdmin,
        ...parseAcceptAdminInstruction(instruction),
      };
    }
    case SkechInstruction.CollectFees: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: SkechInstruction.CollectFees,
        ...parseCollectFeesInstruction(instruction),
      };
    }
    case SkechInstruction.Deposit: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: SkechInstruction.Deposit,
        ...parseDepositInstruction(instruction),
      };
    }
    case SkechInstruction.Expire: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: SkechInstruction.Expire,
        ...parseExpireInstruction(instruction),
      };
    }
    case SkechInstruction.InitMarket: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: SkechInstruction.InitMarket,
        ...parseInitMarketInstruction(instruction),
      };
    }
    case SkechInstruction.Initialize: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: SkechInstruction.Initialize,
        ...parseInitializeInstruction(instruction),
      };
    }
    case SkechInstruction.Place: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: SkechInstruction.Place,
        ...parsePlaceInstruction(instruction),
      };
    }
    case SkechInstruction.PostBar: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: SkechInstruction.PostBar,
        ...parsePostBarInstruction(instruction),
      };
    }
    case SkechInstruction.PostBarAndSettle: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: SkechInstruction.PostBarAndSettle,
        ...parsePostBarAndSettleInstruction(instruction),
      };
    }
    case SkechInstruction.ProposeAdmin: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: SkechInstruction.ProposeAdmin,
        ...parseProposeAdminInstruction(instruction),
      };
    }
    case SkechInstruction.Redeem: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: SkechInstruction.Redeem,
        ...parseRedeemInstruction(instruction),
      };
    }
    case SkechInstruction.RedeemHouse: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: SkechInstruction.RedeemHouse,
        ...parseRedeemHouseInstruction(instruction),
      };
    }
    case SkechInstruction.RevokeSession: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: SkechInstruction.RevokeSession,
        ...parseRevokeSessionInstruction(instruction),
      };
    }
    case SkechInstruction.SetConfig: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: SkechInstruction.SetConfig,
        ...parseSetConfigInstruction(instruction),
      };
    }
    case SkechInstruction.SetIouRate: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: SkechInstruction.SetIouRate,
        ...parseSetIouRateInstruction(instruction),
      };
    }
    case SkechInstruction.SetMarket: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: SkechInstruction.SetMarket,
        ...parseSetMarketInstruction(instruction),
      };
    }
    case SkechInstruction.SetOracle: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: SkechInstruction.SetOracle,
        ...parseSetOracleInstruction(instruction),
      };
    }
    case SkechInstruction.SetPaused: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: SkechInstruction.SetPaused,
        ...parseSetPausedInstruction(instruction),
      };
    }
    case SkechInstruction.SetSession: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: SkechInstruction.SetSession,
        ...parseSetSessionInstruction(instruction),
      };
    }
    case SkechInstruction.SetTreasury: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: SkechInstruction.SetTreasury,
        ...parseSetTreasuryInstruction(instruction),
      };
    }
    case SkechInstruction.Settle: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: SkechInstruction.Settle,
        ...parseSettleInstruction(instruction),
      };
    }
    case SkechInstruction.Sweep: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: SkechInstruction.Sweep,
        ...parseSweepInstruction(instruction),
      };
    }
    case SkechInstruction.Withdraw: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: SkechInstruction.Withdraw,
        ...parseWithdrawInstruction(instruction),
      };
    }
    default:
      throw new SolanaError(
        SOLANA_ERROR__PROGRAM_CLIENTS__UNRECOGNIZED_INSTRUCTION_TYPE,
        { instructionType: instructionType as string, programName: "skech" },
      );
  }
}

export type SkechPlugin = {
  accounts: SkechPluginAccounts;
  instructions: SkechPluginInstructions;
  pdas: SkechPluginPdas;
  identifyAccount: typeof identifySkechAccount;
  identifyInstruction: typeof identifySkechInstruction;
  parseInstruction: typeof parseSkechInstruction;
};

export type SkechPluginAccounts = {
  bars: ReturnType<typeof getBarsCodec> & SelfFetchFunctions<BarsArgs, Bars>;
  game: ReturnType<typeof getGameCodec> & SelfFetchFunctions<GameArgs, Game>;
  market: ReturnType<typeof getMarketCodec> &
    SelfFetchFunctions<MarketArgs, Market>;
  player: ReturnType<typeof getPlayerCodec> &
    SelfFetchFunctions<PlayerArgs, Player>;
  pool: ReturnType<typeof getPoolCodec> & SelfFetchFunctions<PoolArgs, Pool>;
};

export type SkechPluginInstructions = {
  acceptAdmin: (
    input: AcceptAdminAsyncInput,
  ) => ReturnType<typeof getAcceptAdminInstructionAsync> &
    SelfPlanAndSendFunctions;
  collectFees: (
    input: CollectFeesAsyncInput,
  ) => ReturnType<typeof getCollectFeesInstructionAsync> &
    SelfPlanAndSendFunctions;
  deposit: (
    input: MakeOptional<DepositAsyncInput, "payer">,
  ) => ReturnType<typeof getDepositInstructionAsync> & SelfPlanAndSendFunctions;
  expire: (
    input: ExpireAsyncInput,
  ) => ReturnType<typeof getExpireInstructionAsync> & SelfPlanAndSendFunctions;
  initMarket: (
    input: InitMarketAsyncInput,
  ) => ReturnType<typeof getInitMarketInstructionAsync> &
    SelfPlanAndSendFunctions;
  initialize: (
    input: InitializeAsyncInput,
  ) => ReturnType<typeof getInitializeInstructionAsync> &
    SelfPlanAndSendFunctions;
  place: (
    input: MakeOptional<PlaceAsyncInput, "payer">,
  ) => ReturnType<typeof getPlaceInstructionAsync> & SelfPlanAndSendFunctions;
  postBar: (
    input: PostBarAsyncInput,
  ) => ReturnType<typeof getPostBarInstructionAsync> & SelfPlanAndSendFunctions;
  postBarAndSettle: (
    input: PostBarAndSettleAsyncInput,
  ) => ReturnType<typeof getPostBarAndSettleInstructionAsync> &
    SelfPlanAndSendFunctions;
  proposeAdmin: (
    input: ProposeAdminAsyncInput,
  ) => ReturnType<typeof getProposeAdminInstructionAsync> &
    SelfPlanAndSendFunctions;
  redeem: (
    input: RedeemAsyncInput,
  ) => ReturnType<typeof getRedeemInstructionAsync> & SelfPlanAndSendFunctions;
  redeemHouse: (
    input: RedeemHouseAsyncInput,
  ) => ReturnType<typeof getRedeemHouseInstructionAsync> &
    SelfPlanAndSendFunctions;
  revokeSession: (
    input: RevokeSessionAsyncInput,
  ) => ReturnType<typeof getRevokeSessionInstructionAsync> &
    SelfPlanAndSendFunctions;
  setConfig: (
    input: SetConfigAsyncInput,
  ) => ReturnType<typeof getSetConfigInstructionAsync> &
    SelfPlanAndSendFunctions;
  setIouRate: (
    input: SetIouRateAsyncInput,
  ) => ReturnType<typeof getSetIouRateInstructionAsync> &
    SelfPlanAndSendFunctions;
  setMarket: (
    input: SetMarketAsyncInput,
  ) => ReturnType<typeof getSetMarketInstructionAsync> &
    SelfPlanAndSendFunctions;
  setOracle: (
    input: SetOracleAsyncInput,
  ) => ReturnType<typeof getSetOracleInstructionAsync> &
    SelfPlanAndSendFunctions;
  setPaused: (
    input: SetPausedAsyncInput,
  ) => ReturnType<typeof getSetPausedInstructionAsync> &
    SelfPlanAndSendFunctions;
  setSession: (
    input: MakeOptional<SetSessionAsyncInput, "payer">,
  ) => ReturnType<typeof getSetSessionInstructionAsync> &
    SelfPlanAndSendFunctions;
  setTreasury: (
    input: SetTreasuryAsyncInput,
  ) => ReturnType<typeof getSetTreasuryInstructionAsync> &
    SelfPlanAndSendFunctions;
  settle: (
    input: SettleAsyncInput,
  ) => ReturnType<typeof getSettleInstructionAsync> & SelfPlanAndSendFunctions;
  sweep: (
    input: SweepAsyncInput,
  ) => ReturnType<typeof getSweepInstructionAsync> & SelfPlanAndSendFunctions;
  withdraw: (
    input: WithdrawAsyncInput,
  ) => ReturnType<typeof getWithdrawInstructionAsync> &
    SelfPlanAndSendFunctions;
};

export type SkechPluginPdas = {
  game: typeof findGamePda;
  pool: typeof findPoolPda;
  player: typeof findPlayerPda;
  callerPlayer: typeof findCallerPlayerPda;
};

export type SkechPluginRequirements = ClientWithRpc<
  GetAccountInfoApi & GetMultipleAccountsApi
> &
  ClientWithPayer &
  ClientWithTransactionPlanning &
  ClientWithTransactionSending;

export function skechProgram() {
  return <T extends SkechPluginRequirements>(
    client: T,
  ): ExtendedClient<T, { skech: SkechPlugin }> => {
    return extendClient(client, {
      skech: <SkechPlugin>{
        accounts: {
          bars: addSelfFetchFunctions(client, getBarsCodec()),
          game: addSelfFetchFunctions(client, getGameCodec()),
          market: addSelfFetchFunctions(client, getMarketCodec()),
          player: addSelfFetchFunctions(client, getPlayerCodec()),
          pool: addSelfFetchFunctions(client, getPoolCodec()),
        },
        instructions: {
          acceptAdmin: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getAcceptAdminInstructionAsync(input),
            ),
          collectFees: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getCollectFeesInstructionAsync(input),
            ),
          deposit: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getDepositInstructionAsync({
                ...input,
                payer: input.payer ?? client.payer,
              }),
            ),
          expire: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getExpireInstructionAsync(input),
            ),
          initMarket: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getInitMarketInstructionAsync(input),
            ),
          initialize: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getInitializeInstructionAsync(input),
            ),
          place: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getPlaceInstructionAsync({
                ...input,
                payer: input.payer ?? client.payer,
              }),
            ),
          postBar: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getPostBarInstructionAsync(input),
            ),
          postBarAndSettle: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getPostBarAndSettleInstructionAsync(input),
            ),
          proposeAdmin: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getProposeAdminInstructionAsync(input),
            ),
          redeem: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getRedeemInstructionAsync(input),
            ),
          redeemHouse: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getRedeemHouseInstructionAsync(input),
            ),
          revokeSession: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getRevokeSessionInstructionAsync(input),
            ),
          setConfig: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getSetConfigInstructionAsync(input),
            ),
          setIouRate: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getSetIouRateInstructionAsync(input),
            ),
          setMarket: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getSetMarketInstructionAsync(input),
            ),
          setOracle: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getSetOracleInstructionAsync(input),
            ),
          setPaused: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getSetPausedInstructionAsync(input),
            ),
          setSession: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getSetSessionInstructionAsync({
                ...input,
                payer: input.payer ?? client.payer,
              }),
            ),
          setTreasury: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getSetTreasuryInstructionAsync(input),
            ),
          settle: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getSettleInstructionAsync(input),
            ),
          sweep: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getSweepInstructionAsync(input),
            ),
          withdraw: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getWithdrawInstructionAsync(input),
            ),
        },
        pdas: {
          game: findGamePda,
          pool: findPoolPda,
          player: findPlayerPda,
          callerPlayer: findCallerPlayerPda,
        },
        identifyAccount: identifySkechAccount,
        identifyInstruction: identifySkechInstruction,
        parseInstruction: parseSkechInstruction,
      },
    });
  };
}

type MakeOptional<T, K extends keyof T> = Omit<T, K> & Partial<Pick<T, K>>;
