/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  isProgramError,
  type Address,
  type SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM,
  type SolanaError,
} from "@solana/kit";
import { SKECH_PROGRAM_ADDRESS } from "../programs";

/** Mismatch: Mismatch */
export const SKECH_ERROR__MISMATCH = 0x1770; // 6000
/** Replay: Replay */
export const SKECH_ERROR__REPLAY = 0x1771; // 6001
/** Difficulty: Difficulty */
export const SKECH_ERROR__DIFFICULTY = 0x1772; // 6002
/** Late: Late */
export const SKECH_ERROR__LATE = 0x1773; // 6003
/** StalePrice: StalePrice */
export const SKECH_ERROR__STALE_PRICE = 0x1774; // 6004
/** PerDot: PerDot */
export const SKECH_ERROR__PER_DOT = 0x1775; // 6005
/** Sections: Sections */
export const SKECH_ERROR__SECTIONS = 0x1776; // 6006
/** Session: Session */
export const SKECH_ERROR__SESSION = 0x1777; // 6007
/** SessionSig: SessionSig */
export const SKECH_ERROR__SESSION_SIG = 0x1778; // 6008
/** NotOffered: NotOffered */
export const SKECH_ERROR__NOT_OFFERED = 0x1779; // 6009
/** Allowance: Allowance */
export const SKECH_ERROR__ALLOWANCE = 0x177a; // 6010
/** Balance: Balance */
export const SKECH_ERROR__BALANCE = 0x177b; // 6011
/** Paused: The game is paused */
export const SKECH_ERROR__PAUSED = 0x177c; // 6012
/** MarketInactive: The market is not active */
export const SKECH_ERROR__MARKET_INACTIVE = 0x177d; // 6013
/** BadQuote: The quote is malformed */
export const SKECH_ERROR__BAD_QUOTE = 0x177e; // 6014
/** Window: Outside the placing window */
export const SKECH_ERROR__WINDOW = 0x177f; // 6015
/** NotOracle: Not the oracle */
export const SKECH_ERROR__NOT_ORACLE = 0x1780; // 6016
/** NotAdmin: Not the admin */
export const SKECH_ERROR__NOT_ADMIN = 0x1781; // 6017
/** BadBar: The bar is malformed or early */
export const SKECH_ERROR__BAD_BAR = 0x1782; // 6018
/** BarConflict: A different bar is already posted for that second */
export const SKECH_ERROR__BAR_CONFLICT = 0x1783; // 6019
/** BarDiscontinuous: The bar does not follow on from the second before */
export const SKECH_ERROR__BAR_DISCONTINUOUS = 0x1784; // 6020
/** Insufficient: Not enough */
export const SKECH_ERROR__INSUFFICIENT = 0x1785; // 6021
/** NothingToRedeem: Nothing to redeem */
export const SKECH_ERROR__NOTHING_TO_REDEEM = 0x1786; // 6022
/** BadConfig: Bad config */
export const SKECH_ERROR__BAD_CONFIG = 0x1787; // 6023
/** BadDifficulty: Bad difficulty */
export const SKECH_ERROR__BAD_DIFFICULTY = 0x1788; // 6024
/** ZeroAmount: Zero amount */
export const SKECH_ERROR__ZERO_AMOUNT = 0x1789; // 6025
/** BadSession: Bad session */
export const SKECH_ERROR__BAD_SESSION = 0x178a; // 6026
/** BadTokenAccount: Wrong token account */
export const SKECH_ERROR__BAD_TOKEN_ACCOUNT = 0x178b; // 6027
/** BadSettleAccounts: Settle accounts must come in (bet, player) pairs */
export const SKECH_ERROR__BAD_SETTLE_ACCOUNTS = 0x178c; // 6028
/** NotUpgradeAuthority: Only the program's upgrade authority may initialize */
export const SKECH_ERROR__NOT_UPGRADE_AUTHORITY = 0x178d; // 6029
/** Overflow: Arithmetic overflow */
export const SKECH_ERROR__OVERFLOW = 0x178e; // 6030
/** BarLate: The bar is too late to post */
export const SKECH_ERROR__BAR_LATE = 0x178f; // 6031
/** NotSplToken: USDC must be an SPL Token mint */
export const SKECH_ERROR__NOT_SPL_TOKEN = 0x1790; // 6032
/** OwnRedeem: A holder redeeming their own takes no cut: send no caller_player */
export const SKECH_ERROR__OWN_REDEEM = 0x1791; // 6033
/** NotPendingAdmin: Not the proposed admin */
export const SKECH_ERROR__NOT_PENDING_ADMIN = 0x1792; // 6034

export type SkechError =
  | typeof SKECH_ERROR__ALLOWANCE
  | typeof SKECH_ERROR__BAD_BAR
  | typeof SKECH_ERROR__BAD_CONFIG
  | typeof SKECH_ERROR__BAD_DIFFICULTY
  | typeof SKECH_ERROR__BAD_QUOTE
  | typeof SKECH_ERROR__BAD_SESSION
  | typeof SKECH_ERROR__BAD_SETTLE_ACCOUNTS
  | typeof SKECH_ERROR__BAD_TOKEN_ACCOUNT
  | typeof SKECH_ERROR__BALANCE
  | typeof SKECH_ERROR__BAR_CONFLICT
  | typeof SKECH_ERROR__BAR_DISCONTINUOUS
  | typeof SKECH_ERROR__BAR_LATE
  | typeof SKECH_ERROR__DIFFICULTY
  | typeof SKECH_ERROR__INSUFFICIENT
  | typeof SKECH_ERROR__LATE
  | typeof SKECH_ERROR__MARKET_INACTIVE
  | typeof SKECH_ERROR__MISMATCH
  | typeof SKECH_ERROR__NOT_ADMIN
  | typeof SKECH_ERROR__NOTHING_TO_REDEEM
  | typeof SKECH_ERROR__NOT_OFFERED
  | typeof SKECH_ERROR__NOT_ORACLE
  | typeof SKECH_ERROR__NOT_PENDING_ADMIN
  | typeof SKECH_ERROR__NOT_SPL_TOKEN
  | typeof SKECH_ERROR__NOT_UPGRADE_AUTHORITY
  | typeof SKECH_ERROR__OVERFLOW
  | typeof SKECH_ERROR__OWN_REDEEM
  | typeof SKECH_ERROR__PAUSED
  | typeof SKECH_ERROR__PER_DOT
  | typeof SKECH_ERROR__REPLAY
  | typeof SKECH_ERROR__SECTIONS
  | typeof SKECH_ERROR__SESSION
  | typeof SKECH_ERROR__SESSION_SIG
  | typeof SKECH_ERROR__STALE_PRICE
  | typeof SKECH_ERROR__WINDOW
  | typeof SKECH_ERROR__ZERO_AMOUNT;

let skechErrorMessages: Record<SkechError, string> | undefined;
if (process.env["NODE_ENV"] !== "production") {
  skechErrorMessages = {
    [SKECH_ERROR__ALLOWANCE]: `Allowance`,
    [SKECH_ERROR__BAD_BAR]: `The bar is malformed or early`,
    [SKECH_ERROR__BAD_CONFIG]: `Bad config`,
    [SKECH_ERROR__BAD_DIFFICULTY]: `Bad difficulty`,
    [SKECH_ERROR__BAD_QUOTE]: `The quote is malformed`,
    [SKECH_ERROR__BAD_SESSION]: `Bad session`,
    [SKECH_ERROR__BAD_SETTLE_ACCOUNTS]: `Settle accounts must come in (bet, player) pairs`,
    [SKECH_ERROR__BAD_TOKEN_ACCOUNT]: `Wrong token account`,
    [SKECH_ERROR__BALANCE]: `Balance`,
    [SKECH_ERROR__BAR_CONFLICT]: `A different bar is already posted for that second`,
    [SKECH_ERROR__BAR_DISCONTINUOUS]: `The bar does not follow on from the second before`,
    [SKECH_ERROR__BAR_LATE]: `The bar is too late to post`,
    [SKECH_ERROR__DIFFICULTY]: `Difficulty`,
    [SKECH_ERROR__INSUFFICIENT]: `Not enough`,
    [SKECH_ERROR__LATE]: `Late`,
    [SKECH_ERROR__MARKET_INACTIVE]: `The market is not active`,
    [SKECH_ERROR__MISMATCH]: `Mismatch`,
    [SKECH_ERROR__NOT_ADMIN]: `Not the admin`,
    [SKECH_ERROR__NOTHING_TO_REDEEM]: `Nothing to redeem`,
    [SKECH_ERROR__NOT_OFFERED]: `NotOffered`,
    [SKECH_ERROR__NOT_ORACLE]: `Not the oracle`,
    [SKECH_ERROR__NOT_PENDING_ADMIN]: `Not the proposed admin`,
    [SKECH_ERROR__NOT_SPL_TOKEN]: `USDC must be an SPL Token mint`,
    [SKECH_ERROR__NOT_UPGRADE_AUTHORITY]: `Only the program's upgrade authority may initialize`,
    [SKECH_ERROR__OVERFLOW]: `Arithmetic overflow`,
    [SKECH_ERROR__OWN_REDEEM]: `A holder redeeming their own takes no cut: send no caller_player`,
    [SKECH_ERROR__PAUSED]: `The game is paused`,
    [SKECH_ERROR__PER_DOT]: `PerDot`,
    [SKECH_ERROR__REPLAY]: `Replay`,
    [SKECH_ERROR__SECTIONS]: `Sections`,
    [SKECH_ERROR__SESSION]: `Session`,
    [SKECH_ERROR__SESSION_SIG]: `SessionSig`,
    [SKECH_ERROR__STALE_PRICE]: `StalePrice`,
    [SKECH_ERROR__WINDOW]: `Outside the placing window`,
    [SKECH_ERROR__ZERO_AMOUNT]: `Zero amount`,
  };
}

export function getSkechErrorMessage(code: SkechError): string {
  if (process.env["NODE_ENV"] !== "production") {
    return (skechErrorMessages as Record<SkechError, string>)[code];
  }

  return "Error message not available in production bundles.";
}

export function isSkechError<TProgramErrorCode extends SkechError>(
  error: unknown,
  transactionMessage: {
    instructions: Record<number, { programAddress: Address }>;
  },
  code?: TProgramErrorCode,
): error is SolanaError<typeof SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM> &
  Readonly<{ context: Readonly<{ code: TProgramErrorCode }> }> {
  return isProgramError<TProgramErrorCode>(
    error,
    transactionMessage,
    SKECH_PROGRAM_ADDRESS,
    code,
  );
}
