/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  containsBytes,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesEncoder,
  getConstantDecoder,
  getConstantEncoder,
  getHiddenPrefixDecoder,
  getHiddenPrefixEncoder,
  getStructDecoder,
  getStructEncoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type ReadonlyUint8Array,
} from "@solana/kit";

export const ADMIN_PROPOSED_EVENT_DISCRIMINATOR: ReadonlyUint8Array =
  new Uint8Array([129, 249, 226, 227, 199, 82, 110, 243]);

export function getAdminProposedEventDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    ADMIN_PROPOSED_EVENT_DISCRIMINATOR,
  );
}

export type AdminProposedEvent = { admin: Address };

export type AdminProposedEventArgs = AdminProposedEvent;

/** Gets the encoder for {@link AdminProposedEventArgs} event data. */
export function getAdminProposedEventEncoder(): FixedSizeEncoder<AdminProposedEventArgs> {
  return getHiddenPrefixEncoder(
    getStructEncoder([["admin", getAddressEncoder()]]),
    [getConstantEncoder(ADMIN_PROPOSED_EVENT_DISCRIMINATOR)],
  );
}

/** Gets the decoder for {@link AdminProposedEvent} event data. */
export function getAdminProposedEventDecoder(): FixedSizeDecoder<AdminProposedEvent> {
  return getHiddenPrefixDecoder(
    getStructDecoder([["admin", getAddressDecoder()]]),
    [getConstantDecoder(ADMIN_PROPOSED_EVENT_DISCRIMINATOR)],
  );
}

/** Gets the codec for {@link AdminProposedEvent} event data. */
export function getAdminProposedEventCodec(): FixedSizeCodec<
  AdminProposedEventArgs,
  AdminProposedEvent
> {
  return combineCodec(
    getAdminProposedEventEncoder(),
    getAdminProposedEventDecoder(),
  );
}

/** Parses the provided bytes into {@link AdminProposedEvent} event data. */
export function parseAdminProposedEvent(
  data: ReadonlyUint8Array | Uint8Array,
): AdminProposedEvent {
  if (containsBytes(data, ADMIN_PROPOSED_EVENT_DISCRIMINATOR, 0)) {
    return getAdminProposedEventDecoder().decode(data);
  }
  throw new Error(
    'The provided data does not match the "AdminProposedEvent" event discriminators.',
  );
}
