/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  containsBytes,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesEncoder,
  getConstantDecoder,
  getConstantEncoder,
  getHiddenPrefixDecoder,
  getHiddenPrefixEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type ReadonlyUint8Array,
} from "@solana/kit";

export const CLAIMED_EVENT_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([
  217, 192, 123, 72, 108, 150, 248, 33,
]);

export function getClaimedEventDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    CLAIMED_EVENT_DISCRIMINATOR,
  );
}

export type ClaimedEvent = { player: Address; amount: bigint };

export type ClaimedEventArgs = { player: Address; amount: number | bigint };

/** Gets the encoder for {@link ClaimedEventArgs} event data. */
export function getClaimedEventEncoder(): FixedSizeEncoder<ClaimedEventArgs> {
  return getHiddenPrefixEncoder(
    getStructEncoder([
      ["player", getAddressEncoder()],
      ["amount", getU64Encoder()],
    ]),
    [getConstantEncoder(CLAIMED_EVENT_DISCRIMINATOR)],
  );
}

/** Gets the decoder for {@link ClaimedEvent} event data. */
export function getClaimedEventDecoder(): FixedSizeDecoder<ClaimedEvent> {
  return getHiddenPrefixDecoder(
    getStructDecoder([
      ["player", getAddressDecoder()],
      ["amount", getU64Decoder()],
    ]),
    [getConstantDecoder(CLAIMED_EVENT_DISCRIMINATOR)],
  );
}

/** Gets the codec for {@link ClaimedEvent} event data. */
export function getClaimedEventCodec(): FixedSizeCodec<
  ClaimedEventArgs,
  ClaimedEvent
> {
  return combineCodec(getClaimedEventEncoder(), getClaimedEventDecoder());
}

/** Parses the provided bytes into {@link ClaimedEvent} event data. */
export function parseClaimedEvent(
  data: ReadonlyUint8Array | Uint8Array,
): ClaimedEvent {
  if (containsBytes(data, CLAIMED_EVENT_DISCRIMINATOR, 0)) {
    return getClaimedEventDecoder().decode(data);
  }
  throw new Error(
    'The provided data does not match the "ClaimedEvent" event discriminators.',
  );
}
