/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  containsBytes,
  fixEncoderSize,
  getBytesEncoder,
  getConstantDecoder,
  getConstantEncoder,
  getHiddenPrefixDecoder,
  getHiddenPrefixEncoder,
  getStructDecoder,
  getStructEncoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type ReadonlyUint8Array,
} from "@solana/kit";
import {
  getConfigDecoder,
  getConfigEncoder,
  type Config,
  type ConfigArgs,
} from "../types";

export const CONFIG_SET_EVENT_DISCRIMINATOR: ReadonlyUint8Array =
  new Uint8Array([15, 104, 59, 16, 236, 241, 8, 6]);

export function getConfigSetEventDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    CONFIG_SET_EVENT_DISCRIMINATOR,
  );
}

export type ConfigSetEvent = { config: Config };

export type ConfigSetEventArgs = { config: ConfigArgs };

/** Gets the encoder for {@link ConfigSetEventArgs} event data. */
export function getConfigSetEventEncoder(): FixedSizeEncoder<ConfigSetEventArgs> {
  return getHiddenPrefixEncoder(
    getStructEncoder([["config", getConfigEncoder()]]),
    [getConstantEncoder(CONFIG_SET_EVENT_DISCRIMINATOR)],
  );
}

/** Gets the decoder for {@link ConfigSetEvent} event data. */
export function getConfigSetEventDecoder(): FixedSizeDecoder<ConfigSetEvent> {
  return getHiddenPrefixDecoder(
    getStructDecoder([["config", getConfigDecoder()]]),
    [getConstantDecoder(CONFIG_SET_EVENT_DISCRIMINATOR)],
  );
}

/** Gets the codec for {@link ConfigSetEvent} event data. */
export function getConfigSetEventCodec(): FixedSizeCodec<
  ConfigSetEventArgs,
  ConfigSetEvent
> {
  return combineCodec(getConfigSetEventEncoder(), getConfigSetEventDecoder());
}

/** Parses the provided bytes into {@link ConfigSetEvent} event data. */
export function parseConfigSetEvent(
  data: ReadonlyUint8Array | Uint8Array,
): ConfigSetEvent {
  if (containsBytes(data, CONFIG_SET_EVENT_DISCRIMINATOR, 0)) {
    return getConfigSetEventDecoder().decode(data);
  }
  throw new Error(
    'The provided data does not match the "ConfigSetEvent" event discriminators.',
  );
}
