/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  containsBytes,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBooleanDecoder,
  getBooleanEncoder,
  getBytesEncoder,
  getConstantDecoder,
  getConstantEncoder,
  getHiddenPrefixDecoder,
  getHiddenPrefixEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type ReadonlyUint8Array,
} from "@solana/kit";

export const DEPOSITED_EVENT_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array(
  [111, 141, 26, 45, 161, 35, 100, 57],
);

export function getDepositedEventDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    DEPOSITED_EVENT_DISCRIMINATOR,
  );
}

export type DepositedEvent = {
  player: Address;
  amount: bigint;
  /** Swept from the wallet on its standing approval, rather than sent by it. */
  swept: boolean;
};

export type DepositedEventArgs = {
  player: Address;
  amount: number | bigint;
  /** Swept from the wallet on its standing approval, rather than sent by it. */
  swept: boolean;
};

/** Gets the encoder for {@link DepositedEventArgs} event data. */
export function getDepositedEventEncoder(): FixedSizeEncoder<DepositedEventArgs> {
  return getHiddenPrefixEncoder(
    getStructEncoder([
      ["player", getAddressEncoder()],
      ["amount", getU64Encoder()],
      ["swept", getBooleanEncoder()],
    ]),
    [getConstantEncoder(DEPOSITED_EVENT_DISCRIMINATOR)],
  );
}

/** Gets the decoder for {@link DepositedEvent} event data. */
export function getDepositedEventDecoder(): FixedSizeDecoder<DepositedEvent> {
  return getHiddenPrefixDecoder(
    getStructDecoder([
      ["player", getAddressDecoder()],
      ["amount", getU64Decoder()],
      ["swept", getBooleanDecoder()],
    ]),
    [getConstantDecoder(DEPOSITED_EVENT_DISCRIMINATOR)],
  );
}

/** Gets the codec for {@link DepositedEvent} event data. */
export function getDepositedEventCodec(): FixedSizeCodec<
  DepositedEventArgs,
  DepositedEvent
> {
  return combineCodec(getDepositedEventEncoder(), getDepositedEventDecoder());
}

/** Parses the provided bytes into {@link DepositedEvent} event data. */
export function parseDepositedEvent(
  data: ReadonlyUint8Array | Uint8Array,
): DepositedEvent {
  if (containsBytes(data, DEPOSITED_EVENT_DISCRIMINATOR, 0)) {
    return getDepositedEventDecoder().decode(data);
  }
  throw new Error(
    'The provided data does not match the "DepositedEvent" event discriminators.',
  );
}
