/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  containsBytes,
  fixEncoderSize,
  getBytesEncoder,
  getConstantDecoder,
  getConstantEncoder,
  getHiddenPrefixDecoder,
  getHiddenPrefixEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type ReadonlyUint8Array,
} from "@solana/kit";

export const FEES_COLLECTED_EVENT_DISCRIMINATOR: ReadonlyUint8Array =
  new Uint8Array([233, 23, 117, 225, 107, 178, 254, 8]);

export function getFeesCollectedEventDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    FEES_COLLECTED_EVENT_DISCRIMINATOR,
  );
}

export type FeesCollectedEvent = { amount: bigint };

export type FeesCollectedEventArgs = { amount: number | bigint };

/** Gets the encoder for {@link FeesCollectedEventArgs} event data. */
export function getFeesCollectedEventEncoder(): FixedSizeEncoder<FeesCollectedEventArgs> {
  return getHiddenPrefixEncoder(
    getStructEncoder([["amount", getU64Encoder()]]),
    [getConstantEncoder(FEES_COLLECTED_EVENT_DISCRIMINATOR)],
  );
}

/** Gets the decoder for {@link FeesCollectedEvent} event data. */
export function getFeesCollectedEventDecoder(): FixedSizeDecoder<FeesCollectedEvent> {
  return getHiddenPrefixDecoder(
    getStructDecoder([["amount", getU64Decoder()]]),
    [getConstantDecoder(FEES_COLLECTED_EVENT_DISCRIMINATOR)],
  );
}

/** Gets the codec for {@link FeesCollectedEvent} event data. */
export function getFeesCollectedEventCodec(): FixedSizeCodec<
  FeesCollectedEventArgs,
  FeesCollectedEvent
> {
  return combineCodec(
    getFeesCollectedEventEncoder(),
    getFeesCollectedEventDecoder(),
  );
}

/** Parses the provided bytes into {@link FeesCollectedEvent} event data. */
export function parseFeesCollectedEvent(
  data: ReadonlyUint8Array | Uint8Array,
): FeesCollectedEvent {
  if (containsBytes(data, FEES_COLLECTED_EVENT_DISCRIMINATOR, 0)) {
    return getFeesCollectedEventDecoder().decode(data);
  }
  throw new Error(
    'The provided data does not match the "FeesCollectedEvent" event discriminators.',
  );
}
