/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  containsBytes,
  fixEncoderSize,
  getBytesEncoder,
  getConstantDecoder,
  getConstantEncoder,
  getHiddenPrefixDecoder,
  getHiddenPrefixEncoder,
  getStructDecoder,
  getStructEncoder,
  getU128Decoder,
  getU128Encoder,
  getU64Decoder,
  getU64Encoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type ReadonlyUint8Array,
} from "@solana/kit";

export const HOLDER_ACCRUED_EVENT_DISCRIMINATOR: ReadonlyUint8Array =
  new Uint8Array([137, 231, 250, 101, 27, 104, 206, 187]);

export function getHolderAccruedEventDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    HOLDER_ACCRUED_EVENT_DISCRIMINATOR,
  );
}

export type HolderAccruedEvent = {
  amount: bigint;
  acc: bigint;
  supply: bigint;
};

export type HolderAccruedEventArgs = {
  amount: number | bigint;
  acc: number | bigint;
  supply: number | bigint;
};

/** Gets the encoder for {@link HolderAccruedEventArgs} event data. */
export function getHolderAccruedEventEncoder(): FixedSizeEncoder<HolderAccruedEventArgs> {
  return getHiddenPrefixEncoder(
    getStructEncoder([
      ["amount", getU64Encoder()],
      ["acc", getU128Encoder()],
      ["supply", getU64Encoder()],
    ]),
    [getConstantEncoder(HOLDER_ACCRUED_EVENT_DISCRIMINATOR)],
  );
}

/** Gets the decoder for {@link HolderAccruedEvent} event data. */
export function getHolderAccruedEventDecoder(): FixedSizeDecoder<HolderAccruedEvent> {
  return getHiddenPrefixDecoder(
    getStructDecoder([
      ["amount", getU64Decoder()],
      ["acc", getU128Decoder()],
      ["supply", getU64Decoder()],
    ]),
    [getConstantDecoder(HOLDER_ACCRUED_EVENT_DISCRIMINATOR)],
  );
}

/** Gets the codec for {@link HolderAccruedEvent} event data. */
export function getHolderAccruedEventCodec(): FixedSizeCodec<
  HolderAccruedEventArgs,
  HolderAccruedEvent
> {
  return combineCodec(
    getHolderAccruedEventEncoder(),
    getHolderAccruedEventDecoder(),
  );
}

/** Parses the provided bytes into {@link HolderAccruedEvent} event data. */
export function parseHolderAccruedEvent(
  data: ReadonlyUint8Array | Uint8Array,
): HolderAccruedEvent {
  if (containsBytes(data, HOLDER_ACCRUED_EVENT_DISCRIMINATOR, 0)) {
    return getHolderAccruedEventDecoder().decode(data);
  }
  throw new Error(
    'The provided data does not match the "HolderAccruedEvent" event discriminators.',
  );
}
