/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  containsBytes,
  fixEncoderSize,
  getBytesEncoder,
  getConstantDecoder,
  getConstantEncoder,
  getHiddenPrefixDecoder,
  getHiddenPrefixEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type ReadonlyUint8Array,
} from "@solana/kit";

export const IOU_RATE_SET_EVENT_DISCRIMINATOR: ReadonlyUint8Array =
  new Uint8Array([252, 90, 54, 68, 6, 233, 252, 130]);

export function getIouRateSetEventDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    IOU_RATE_SET_EVENT_DISCRIMINATOR,
  );
}

export type IouRateSetEvent = { rate: bigint };

export type IouRateSetEventArgs = { rate: number | bigint };

/** Gets the encoder for {@link IouRateSetEventArgs} event data. */
export function getIouRateSetEventEncoder(): FixedSizeEncoder<IouRateSetEventArgs> {
  return getHiddenPrefixEncoder(getStructEncoder([["rate", getU64Encoder()]]), [
    getConstantEncoder(IOU_RATE_SET_EVENT_DISCRIMINATOR),
  ]);
}

/** Gets the decoder for {@link IouRateSetEvent} event data. */
export function getIouRateSetEventDecoder(): FixedSizeDecoder<IouRateSetEvent> {
  return getHiddenPrefixDecoder(getStructDecoder([["rate", getU64Decoder()]]), [
    getConstantDecoder(IOU_RATE_SET_EVENT_DISCRIMINATOR),
  ]);
}

/** Gets the codec for {@link IouRateSetEvent} event data. */
export function getIouRateSetEventCodec(): FixedSizeCodec<
  IouRateSetEventArgs,
  IouRateSetEvent
> {
  return combineCodec(getIouRateSetEventEncoder(), getIouRateSetEventDecoder());
}

/** Parses the provided bytes into {@link IouRateSetEvent} event data. */
export function parseIouRateSetEvent(
  data: ReadonlyUint8Array | Uint8Array,
): IouRateSetEvent {
  if (containsBytes(data, IOU_RATE_SET_EVENT_DISCRIMINATOR, 0)) {
    return getIouRateSetEventDecoder().decode(data);
  }
  throw new Error(
    'The provided data does not match the "IouRateSetEvent" event discriminators.',
  );
}
