/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  addDecoderSizePrefix,
  addEncoderSizePrefix,
  combineCodec,
  containsBytes,
  fixEncoderSize,
  getBooleanDecoder,
  getBooleanEncoder,
  getBytesEncoder,
  getConstantDecoder,
  getConstantEncoder,
  getHiddenPrefixDecoder,
  getHiddenPrefixEncoder,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  getU8Decoder,
  getU8Encoder,
  getUtf8Decoder,
  getUtf8Encoder,
  type Codec,
  type Decoder,
  type Encoder,
  type ReadonlyUint8Array,
} from "@solana/kit";

export const MARKET_SET_EVENT_DISCRIMINATOR: ReadonlyUint8Array =
  new Uint8Array([64, 19, 78, 233, 226, 142, 234, 83]);

export function getMarketSetEventDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    MARKET_SET_EVENT_DISCRIMINATOR,
  );
}

export type MarketSetEvent = {
  market: number;
  name: string;
  active: boolean;
  difficulty: number;
};

export type MarketSetEventArgs = MarketSetEvent;

/** Gets the encoder for {@link MarketSetEventArgs} event data. */
export function getMarketSetEventEncoder(): Encoder<MarketSetEventArgs> {
  return getHiddenPrefixEncoder(
    getStructEncoder([
      ["market", getU8Encoder()],
      ["name", addEncoderSizePrefix(getUtf8Encoder(), getU32Encoder())],
      ["active", getBooleanEncoder()],
      ["difficulty", getU8Encoder()],
    ]),
    [getConstantEncoder(MARKET_SET_EVENT_DISCRIMINATOR)],
  );
}

/** Gets the decoder for {@link MarketSetEvent} event data. */
export function getMarketSetEventDecoder(): Decoder<MarketSetEvent> {
  return getHiddenPrefixDecoder(
    getStructDecoder([
      ["market", getU8Decoder()],
      ["name", addDecoderSizePrefix(getUtf8Decoder(), getU32Decoder())],
      ["active", getBooleanDecoder()],
      ["difficulty", getU8Decoder()],
    ]),
    [getConstantDecoder(MARKET_SET_EVENT_DISCRIMINATOR)],
  );
}

/** Gets the codec for {@link MarketSetEvent} event data. */
export function getMarketSetEventCodec(): Codec<
  MarketSetEventArgs,
  MarketSetEvent
> {
  return combineCodec(getMarketSetEventEncoder(), getMarketSetEventDecoder());
}

/** Parses the provided bytes into {@link MarketSetEvent} event data. */
export function parseMarketSetEvent(
  data: ReadonlyUint8Array | Uint8Array,
): MarketSetEvent {
  if (containsBytes(data, MARKET_SET_EVENT_DISCRIMINATOR, 0)) {
    return getMarketSetEventDecoder().decode(data);
  }
  throw new Error(
    'The provided data does not match the "MarketSetEvent" event discriminators.',
  );
}
