/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  containsBytes,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesEncoder,
  getConstantDecoder,
  getConstantEncoder,
  getHiddenPrefixDecoder,
  getHiddenPrefixEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type ReadonlyUint8Array,
} from "@solana/kit";

export const MINTED_EVENT_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([
  174, 131, 21, 57, 88, 117, 114, 121,
]);

export function getMintedEventDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    MINTED_EVENT_DISCRIMINATOR,
  );
}

export type MintedEvent = {
  player: Address;
  skt: bigint;
  rate: bigint;
  netLossNewLow: bigint;
};

export type MintedEventArgs = {
  player: Address;
  skt: number | bigint;
  rate: number | bigint;
  netLossNewLow: number | bigint;
};

/** Gets the encoder for {@link MintedEventArgs} event data. */
export function getMintedEventEncoder(): FixedSizeEncoder<MintedEventArgs> {
  return getHiddenPrefixEncoder(
    getStructEncoder([
      ["player", getAddressEncoder()],
      ["skt", getU64Encoder()],
      ["rate", getU64Encoder()],
      ["netLossNewLow", getU64Encoder()],
    ]),
    [getConstantEncoder(MINTED_EVENT_DISCRIMINATOR)],
  );
}

/** Gets the decoder for {@link MintedEvent} event data. */
export function getMintedEventDecoder(): FixedSizeDecoder<MintedEvent> {
  return getHiddenPrefixDecoder(
    getStructDecoder([
      ["player", getAddressDecoder()],
      ["skt", getU64Decoder()],
      ["rate", getU64Decoder()],
      ["netLossNewLow", getU64Decoder()],
    ]),
    [getConstantDecoder(MINTED_EVENT_DISCRIMINATOR)],
  );
}

/** Gets the codec for {@link MintedEvent} event data. */
export function getMintedEventCodec(): FixedSizeCodec<
  MintedEventArgs,
  MintedEvent
> {
  return combineCodec(getMintedEventEncoder(), getMintedEventDecoder());
}

/** Parses the provided bytes into {@link MintedEvent} event data. */
export function parseMintedEvent(
  data: ReadonlyUint8Array | Uint8Array,
): MintedEvent {
  if (containsBytes(data, MINTED_EVENT_DISCRIMINATOR, 0)) {
    return getMintedEventDecoder().decode(data);
  }
  throw new Error(
    'The provided data does not match the "MintedEvent" event discriminators.',
  );
}
