/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  containsBytes,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesEncoder,
  getConstantDecoder,
  getConstantEncoder,
  getHiddenPrefixDecoder,
  getHiddenPrefixEncoder,
  getStructDecoder,
  getStructEncoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type ReadonlyUint8Array,
} from "@solana/kit";

export const ORACLE_SET_EVENT_DISCRIMINATOR: ReadonlyUint8Array =
  new Uint8Array([115, 135, 7, 243, 213, 60, 174, 119]);

export function getOracleSetEventDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    ORACLE_SET_EVENT_DISCRIMINATOR,
  );
}

export type OracleSetEvent = { oracle: Address };

export type OracleSetEventArgs = OracleSetEvent;

/** Gets the encoder for {@link OracleSetEventArgs} event data. */
export function getOracleSetEventEncoder(): FixedSizeEncoder<OracleSetEventArgs> {
  return getHiddenPrefixEncoder(
    getStructEncoder([["oracle", getAddressEncoder()]]),
    [getConstantEncoder(ORACLE_SET_EVENT_DISCRIMINATOR)],
  );
}

/** Gets the decoder for {@link OracleSetEvent} event data. */
export function getOracleSetEventDecoder(): FixedSizeDecoder<OracleSetEvent> {
  return getHiddenPrefixDecoder(
    getStructDecoder([["oracle", getAddressDecoder()]]),
    [getConstantDecoder(ORACLE_SET_EVENT_DISCRIMINATOR)],
  );
}

/** Gets the codec for {@link OracleSetEvent} event data. */
export function getOracleSetEventCodec(): FixedSizeCodec<
  OracleSetEventArgs,
  OracleSetEvent
> {
  return combineCodec(getOracleSetEventEncoder(), getOracleSetEventDecoder());
}

/** Parses the provided bytes into {@link OracleSetEvent} event data. */
export function parseOracleSetEvent(
  data: ReadonlyUint8Array | Uint8Array,
): OracleSetEvent {
  if (containsBytes(data, ORACLE_SET_EVENT_DISCRIMINATOR, 0)) {
    return getOracleSetEventDecoder().decode(data);
  }
  throw new Error(
    'The provided data does not match the "OracleSetEvent" event discriminators.',
  );
}
