/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  containsBytes,
  fixEncoderSize,
  getBooleanDecoder,
  getBooleanEncoder,
  getBytesEncoder,
  getConstantDecoder,
  getConstantEncoder,
  getHiddenPrefixDecoder,
  getHiddenPrefixEncoder,
  getStructDecoder,
  getStructEncoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type ReadonlyUint8Array,
} from "@solana/kit";

export const PAUSED_SET_EVENT_DISCRIMINATOR: ReadonlyUint8Array =
  new Uint8Array([171, 125, 127, 156, 233, 81, 68, 66]);

export function getPausedSetEventDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    PAUSED_SET_EVENT_DISCRIMINATOR,
  );
}

export type PausedSetEvent = { paused: boolean };

export type PausedSetEventArgs = PausedSetEvent;

/** Gets the encoder for {@link PausedSetEventArgs} event data. */
export function getPausedSetEventEncoder(): FixedSizeEncoder<PausedSetEventArgs> {
  return getHiddenPrefixEncoder(
    getStructEncoder([["paused", getBooleanEncoder()]]),
    [getConstantEncoder(PAUSED_SET_EVENT_DISCRIMINATOR)],
  );
}

/** Gets the decoder for {@link PausedSetEvent} event data. */
export function getPausedSetEventDecoder(): FixedSizeDecoder<PausedSetEvent> {
  return getHiddenPrefixDecoder(
    getStructDecoder([["paused", getBooleanDecoder()]]),
    [getConstantDecoder(PAUSED_SET_EVENT_DISCRIMINATOR)],
  );
}

/** Gets the codec for {@link PausedSetEvent} event data. */
export function getPausedSetEventCodec(): FixedSizeCodec<
  PausedSetEventArgs,
  PausedSetEvent
> {
  return combineCodec(getPausedSetEventEncoder(), getPausedSetEventDecoder());
}

/** Parses the provided bytes into {@link PausedSetEvent} event data. */
export function parsePausedSetEvent(
  data: ReadonlyUint8Array | Uint8Array,
): PausedSetEvent {
  if (containsBytes(data, PAUSED_SET_EVENT_DISCRIMINATOR, 0)) {
    return getPausedSetEventDecoder().decode(data);
  }
  throw new Error(
    'The provided data does not match the "PausedSetEvent" event discriminators.',
  );
}
