/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  containsBytes,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getArrayDecoder,
  getArrayEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getConstantDecoder,
  getConstantEncoder,
  getHiddenPrefixDecoder,
  getHiddenPrefixEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type ReadonlyUint8Array,
} from "@solana/kit";
import {
  getBetSectionDecoder,
  getBetSectionEncoder,
  type BetSection,
  type BetSectionArgs,
} from "../types";

export const PLACED_EVENT_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([
  182, 12, 15, 19, 155, 29, 175, 156,
]);

export function getPlacedEventDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    PLACED_EVENT_DISCRIMINATOR,
  );
}

export type PlacedEvent = {
  bet: Address;
  player: Address;
  drawing: bigint;
  index: number;
  market: number;
  openAt: bigint;
  perDot: bigint;
  unit: bigint;
  staked: bigint;
  fee: bigint;
  refunded: bigint;
  priceSeen: bigint;
  priceTime: bigint;
  strokeHash: ReadonlyUint8Array;
  sections: Array<BetSection>;
};

export type PlacedEventArgs = {
  bet: Address;
  player: Address;
  drawing: number | bigint;
  index: number;
  market: number;
  openAt: number | bigint;
  perDot: number | bigint;
  unit: number | bigint;
  staked: number | bigint;
  fee: number | bigint;
  refunded: number | bigint;
  priceSeen: number | bigint;
  priceTime: number | bigint;
  strokeHash: ReadonlyUint8Array;
  sections: Array<BetSectionArgs>;
};

/** Gets the encoder for {@link PlacedEventArgs} event data. */
export function getPlacedEventEncoder(): Encoder<PlacedEventArgs> {
  return getHiddenPrefixEncoder(
    getStructEncoder([
      ["bet", getAddressEncoder()],
      ["player", getAddressEncoder()],
      ["drawing", getU64Encoder()],
      ["index", getU32Encoder()],
      ["market", getU8Encoder()],
      ["openAt", getI64Encoder()],
      ["perDot", getU64Encoder()],
      ["unit", getU64Encoder()],
      ["staked", getU64Encoder()],
      ["fee", getU64Encoder()],
      ["refunded", getU64Encoder()],
      ["priceSeen", getU64Encoder()],
      ["priceTime", getI64Encoder()],
      ["strokeHash", fixEncoderSize(getBytesEncoder(), 32)],
      ["sections", getArrayEncoder(getBetSectionEncoder())],
    ]),
    [getConstantEncoder(PLACED_EVENT_DISCRIMINATOR)],
  );
}

/** Gets the decoder for {@link PlacedEvent} event data. */
export function getPlacedEventDecoder(): Decoder<PlacedEvent> {
  return getHiddenPrefixDecoder(
    getStructDecoder([
      ["bet", getAddressDecoder()],
      ["player", getAddressDecoder()],
      ["drawing", getU64Decoder()],
      ["index", getU32Decoder()],
      ["market", getU8Decoder()],
      ["openAt", getI64Decoder()],
      ["perDot", getU64Decoder()],
      ["unit", getU64Decoder()],
      ["staked", getU64Decoder()],
      ["fee", getU64Decoder()],
      ["refunded", getU64Decoder()],
      ["priceSeen", getU64Decoder()],
      ["priceTime", getI64Decoder()],
      ["strokeHash", fixDecoderSize(getBytesDecoder(), 32)],
      ["sections", getArrayDecoder(getBetSectionDecoder())],
    ]),
    [getConstantDecoder(PLACED_EVENT_DISCRIMINATOR)],
  );
}

/** Gets the codec for {@link PlacedEvent} event data. */
export function getPlacedEventCodec(): Codec<PlacedEventArgs, PlacedEvent> {
  return combineCodec(getPlacedEventEncoder(), getPlacedEventDecoder());
}

/** Parses the provided bytes into {@link PlacedEvent} event data. */
export function parsePlacedEvent(
  data: ReadonlyUint8Array | Uint8Array,
): PlacedEvent {
  if (containsBytes(data, PLACED_EVENT_DISCRIMINATOR, 0)) {
    return getPlacedEventDecoder().decode(data);
  }
  throw new Error(
    'The provided data does not match the "PlacedEvent" event discriminators.',
  );
}
