/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  containsBytes,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesEncoder,
  getConstantDecoder,
  getConstantEncoder,
  getHiddenPrefixDecoder,
  getHiddenPrefixEncoder,
  getStructDecoder,
  getStructEncoder,
  getU128Decoder,
  getU128Encoder,
  getU64Decoder,
  getU64Encoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type ReadonlyUint8Array,
} from "@solana/kit";

export const REDEEMED_EVENT_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([
  14, 29, 183, 71, 31, 165, 107, 38,
]);

export function getRedeemedEventDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    REDEEMED_EVENT_DISCRIMINATOR,
  );
}

export type RedeemedEvent = {
  holder: Address;
  by: Address;
  shares: bigint;
  value: bigint;
  cut: bigint;
};

export type RedeemedEventArgs = {
  holder: Address;
  by: Address;
  shares: number | bigint;
  value: number | bigint;
  cut: number | bigint;
};

/** Gets the encoder for {@link RedeemedEventArgs} event data. */
export function getRedeemedEventEncoder(): FixedSizeEncoder<RedeemedEventArgs> {
  return getHiddenPrefixEncoder(
    getStructEncoder([
      ["holder", getAddressEncoder()],
      ["by", getAddressEncoder()],
      ["shares", getU128Encoder()],
      ["value", getU64Encoder()],
      ["cut", getU64Encoder()],
    ]),
    [getConstantEncoder(REDEEMED_EVENT_DISCRIMINATOR)],
  );
}

/** Gets the decoder for {@link RedeemedEvent} event data. */
export function getRedeemedEventDecoder(): FixedSizeDecoder<RedeemedEvent> {
  return getHiddenPrefixDecoder(
    getStructDecoder([
      ["holder", getAddressDecoder()],
      ["by", getAddressDecoder()],
      ["shares", getU128Decoder()],
      ["value", getU64Decoder()],
      ["cut", getU64Decoder()],
    ]),
    [getConstantDecoder(REDEEMED_EVENT_DISCRIMINATOR)],
  );
}

/** Gets the codec for {@link RedeemedEvent} event data. */
export function getRedeemedEventCodec(): FixedSizeCodec<
  RedeemedEventArgs,
  RedeemedEvent
> {
  return combineCodec(getRedeemedEventEncoder(), getRedeemedEventDecoder());
}

/** Parses the provided bytes into {@link RedeemedEvent} event data. */
export function parseRedeemedEvent(
  data: ReadonlyUint8Array | Uint8Array,
): RedeemedEvent {
  if (containsBytes(data, REDEEMED_EVENT_DISCRIMINATOR, 0)) {
    return getRedeemedEventDecoder().decode(data);
  }
  throw new Error(
    'The provided data does not match the "RedeemedEvent" event discriminators.',
  );
}
