/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  containsBytes,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesEncoder,
  getConstantDecoder,
  getConstantEncoder,
  getHiddenPrefixDecoder,
  getHiddenPrefixEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type ReadonlyUint8Array,
} from "@solana/kit";

export const SESSION_SET_EVENT_DISCRIMINATOR: ReadonlyUint8Array =
  new Uint8Array([217, 40, 191, 250, 153, 135, 184, 144]);

export function getSessionSetEventDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    SESSION_SET_EVENT_DISCRIMINATOR,
  );
}

export type SessionSetEvent = {
  player: Address;
  key: Address;
  validUntil: bigint;
  allowance: bigint;
};

export type SessionSetEventArgs = {
  player: Address;
  key: Address;
  validUntil: number | bigint;
  allowance: number | bigint;
};

/** Gets the encoder for {@link SessionSetEventArgs} event data. */
export function getSessionSetEventEncoder(): FixedSizeEncoder<SessionSetEventArgs> {
  return getHiddenPrefixEncoder(
    getStructEncoder([
      ["player", getAddressEncoder()],
      ["key", getAddressEncoder()],
      ["validUntil", getI64Encoder()],
      ["allowance", getU64Encoder()],
    ]),
    [getConstantEncoder(SESSION_SET_EVENT_DISCRIMINATOR)],
  );
}

/** Gets the decoder for {@link SessionSetEvent} event data. */
export function getSessionSetEventDecoder(): FixedSizeDecoder<SessionSetEvent> {
  return getHiddenPrefixDecoder(
    getStructDecoder([
      ["player", getAddressDecoder()],
      ["key", getAddressDecoder()],
      ["validUntil", getI64Decoder()],
      ["allowance", getU64Decoder()],
    ]),
    [getConstantDecoder(SESSION_SET_EVENT_DISCRIMINATOR)],
  );
}

/** Gets the codec for {@link SessionSetEvent} event data. */
export function getSessionSetEventCodec(): FixedSizeCodec<
  SessionSetEventArgs,
  SessionSetEvent
> {
  return combineCodec(getSessionSetEventEncoder(), getSessionSetEventDecoder());
}

/** Parses the provided bytes into {@link SessionSetEvent} event data. */
export function parseSessionSetEvent(
  data: ReadonlyUint8Array | Uint8Array,
): SessionSetEvent {
  if (containsBytes(data, SESSION_SET_EVENT_DISCRIMINATOR, 0)) {
    return getSessionSetEventDecoder().decode(data);
  }
  throw new Error(
    'The provided data does not match the "SessionSetEvent" event discriminators.',
  );
}
