/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  containsBytes,
  fixEncoderSize,
  getBytesEncoder,
  getConstantDecoder,
  getConstantEncoder,
  getHiddenPrefixDecoder,
  getHiddenPrefixEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type ReadonlyUint8Array,
} from "@solana/kit";

export const SURPLUS_SHARED_EVENT_DISCRIMINATOR: ReadonlyUint8Array =
  new Uint8Array([62, 121, 185, 91, 27, 30, 76, 124]);

export function getSurplusSharedEventDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    SURPLUS_SHARED_EVENT_DISCRIMINATOR,
  );
}

export type SurplusSharedEvent = { amount: bigint; kept: bigint };

export type SurplusSharedEventArgs = {
  amount: number | bigint;
  kept: number | bigint;
};

/** Gets the encoder for {@link SurplusSharedEventArgs} event data. */
export function getSurplusSharedEventEncoder(): FixedSizeEncoder<SurplusSharedEventArgs> {
  return getHiddenPrefixEncoder(
    getStructEncoder([
      ["amount", getU64Encoder()],
      ["kept", getU64Encoder()],
    ]),
    [getConstantEncoder(SURPLUS_SHARED_EVENT_DISCRIMINATOR)],
  );
}

/** Gets the decoder for {@link SurplusSharedEvent} event data. */
export function getSurplusSharedEventDecoder(): FixedSizeDecoder<SurplusSharedEvent> {
  return getHiddenPrefixDecoder(
    getStructDecoder([
      ["amount", getU64Decoder()],
      ["kept", getU64Decoder()],
    ]),
    [getConstantDecoder(SURPLUS_SHARED_EVENT_DISCRIMINATOR)],
  );
}

/** Gets the codec for {@link SurplusSharedEvent} event data. */
export function getSurplusSharedEventCodec(): FixedSizeCodec<
  SurplusSharedEventArgs,
  SurplusSharedEvent
> {
  return combineCodec(
    getSurplusSharedEventEncoder(),
    getSurplusSharedEventDecoder(),
  );
}

/** Parses the provided bytes into {@link SurplusSharedEvent} event data. */
export function parseSurplusSharedEvent(
  data: ReadonlyUint8Array | Uint8Array,
): SurplusSharedEvent {
  if (containsBytes(data, SURPLUS_SHARED_EVENT_DISCRIMINATOR, 0)) {
    return getSurplusSharedEventDecoder().decode(data);
  }
  throw new Error(
    'The provided data does not match the "SurplusSharedEvent" event discriminators.',
  );
}
