/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  containsBytes,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesEncoder,
  getConstantDecoder,
  getConstantEncoder,
  getHiddenPrefixDecoder,
  getHiddenPrefixEncoder,
  getStructDecoder,
  getStructEncoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type ReadonlyUint8Array,
} from "@solana/kit";

export const TREASURY_SET_EVENT_DISCRIMINATOR: ReadonlyUint8Array =
  new Uint8Array([69, 231, 163, 135, 254, 194, 109, 166]);

export function getTreasurySetEventDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    TREASURY_SET_EVENT_DISCRIMINATOR,
  );
}

export type TreasurySetEvent = { treasury: Address };

export type TreasurySetEventArgs = TreasurySetEvent;

/** Gets the encoder for {@link TreasurySetEventArgs} event data. */
export function getTreasurySetEventEncoder(): FixedSizeEncoder<TreasurySetEventArgs> {
  return getHiddenPrefixEncoder(
    getStructEncoder([["treasury", getAddressEncoder()]]),
    [getConstantEncoder(TREASURY_SET_EVENT_DISCRIMINATOR)],
  );
}

/** Gets the decoder for {@link TreasurySetEvent} event data. */
export function getTreasurySetEventDecoder(): FixedSizeDecoder<TreasurySetEvent> {
  return getHiddenPrefixDecoder(
    getStructDecoder([["treasury", getAddressDecoder()]]),
    [getConstantDecoder(TREASURY_SET_EVENT_DISCRIMINATOR)],
  );
}

/** Gets the codec for {@link TreasurySetEvent} event data. */
export function getTreasurySetEventCodec(): FixedSizeCodec<
  TreasurySetEventArgs,
  TreasurySetEvent
> {
  return combineCodec(
    getTreasurySetEventEncoder(),
    getTreasurySetEventDecoder(),
  );
}

/** Parses the provided bytes into {@link TreasurySetEvent} event data. */
export function parseTreasurySetEvent(
  data: ReadonlyUint8Array | Uint8Array,
): TreasurySetEvent {
  if (containsBytes(data, TREASURY_SET_EVENT_DISCRIMINATOR, 0)) {
    return getTreasurySetEventDecoder().decode(data);
  }
  throw new Error(
    'The provided data does not match the "TreasurySetEvent" event discriminators.',
  );
}
