/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  containsBytes,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesEncoder,
  getConstantDecoder,
  getConstantEncoder,
  getHiddenPrefixDecoder,
  getHiddenPrefixEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type ReadonlyUint8Array,
} from "@solana/kit";

export const WITHDRAWN_EVENT_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array(
  [20, 89, 223, 198, 194, 124, 219, 13],
);

export function getWithdrawnEventDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    WITHDRAWN_EVENT_DISCRIMINATOR,
  );
}

export type WithdrawnEvent = { player: Address; to: Address; amount: bigint };

export type WithdrawnEventArgs = {
  player: Address;
  to: Address;
  amount: number | bigint;
};

/** Gets the encoder for {@link WithdrawnEventArgs} event data. */
export function getWithdrawnEventEncoder(): FixedSizeEncoder<WithdrawnEventArgs> {
  return getHiddenPrefixEncoder(
    getStructEncoder([
      ["player", getAddressEncoder()],
      ["to", getAddressEncoder()],
      ["amount", getU64Encoder()],
    ]),
    [getConstantEncoder(WITHDRAWN_EVENT_DISCRIMINATOR)],
  );
}

/** Gets the decoder for {@link WithdrawnEvent} event data. */
export function getWithdrawnEventDecoder(): FixedSizeDecoder<WithdrawnEvent> {
  return getHiddenPrefixDecoder(
    getStructDecoder([
      ["player", getAddressDecoder()],
      ["to", getAddressDecoder()],
      ["amount", getU64Decoder()],
    ]),
    [getConstantDecoder(WITHDRAWN_EVENT_DISCRIMINATOR)],
  );
}

/** Gets the codec for {@link WithdrawnEvent} event data. */
export function getWithdrawnEventCodec(): FixedSizeCodec<
  WithdrawnEventArgs,
  WithdrawnEvent
> {
  return combineCodec(getWithdrawnEventEncoder(), getWithdrawnEventDecoder());
}

/** Parses the provided bytes into {@link WithdrawnEvent} event data. */
export function parseWithdrawnEvent(
  data: ReadonlyUint8Array | Uint8Array,
): WithdrawnEvent {
  if (containsBytes(data, WITHDRAWN_EVENT_DISCRIMINATOR, 0)) {
    return getWithdrawnEventDecoder().decode(data);
  }
  throw new Error(
    'The provided data does not match the "WithdrawnEvent" event discriminators.',
  );
}
