/**
 * The storage layout of the upgradeable contracts, held to `snapshots/StorageLayout.json`. SkechGame and SkechIOU are
 * live behind UUPS proxies: an upgrade that moves a field reads another field's bytes as its own. Both keep their
 * state in one ERC-7201 struct each, which the compiler's layout of the contracts does not show, so this reads the
 * structs laid out from slot 0 in `test/StorageLayout.t.sol:StorageLayoutProbe`.
 *
 *   bun packages/contracts/evm/layout.ts           records the layout; refuses one an upgrade could not keep
 *   bun packages/contracts/evm/layout.ts --check   fails if the layout differs from the snapshot at all
 *
 * The rule: never reorder, retype or insert fields in a stored struct. New state goes at the end of a namespace's
 * struct (or of a struct that is only ever a mapping's value), or in a new namespace. A struct kept inline inside
 * another (Config) may not grow.
 */
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

type Member = [label: string, slot: number, offset: number, type: string];
type Struct = { bytes: number; members: Member[] };
type Layout = Record<string, Struct>;
type ForgeType = { label: string; numberOfBytes: string; encoding: string; members?: { label: string; slot: string; offset: number; type: string }[]; value?: string };

const here = import.meta.dir;
const path = join(here, "snapshots", "StorageLayout.json");
/** The namespaces' own structs: the roots, which may grow at the end. */
const ROOTS = ["struct SkechGame.GameStorage", "struct SkechIOU.IOUStorage"];

function current(): { layout: Layout; inline: Set<string> } {
  const out = execFileSync("forge", ["inspect", "test/StorageLayout.t.sol:StorageLayoutProbe", "storageLayout", "--json"], { cwd: here, encoding: "utf8" });
  const types = (JSON.parse(out) as { types: Record<string, ForgeType> }).types;
  const layout: Layout = {};
  const inline = new Set<string>();
  for (const t of Object.values(types)) {
    if (!t.members) continue;
    layout[t.label] = { bytes: Number(t.numberOfBytes), members: t.members.map((m) => [m.label, Number(m.slot), m.offset, types[m.type].label]) };
    // A struct that is a field of another, not a mapping's value, sits inline: it cannot grow.
    for (const m of t.members) if (types[m.type].members) inline.add(types[m.type].label);
  }
  return { layout: Object.fromEntries(Object.entries(layout).sort(([a], [b]) => a.localeCompare(b))), inline };
}

/** What an upgrade from `was` to `now` would break: every field of `was` must be where it was, with its type. */
function breaks(was: Layout, now: Layout, inline: Set<string>): string[] {
  const out: string[] = [];
  for (const [name, s] of Object.entries(was)) {
    const n = now[name];
    if (!n) {
      if (ROOTS.includes(name)) out.push(`${name} is gone`);
      continue;
    }
    s.members.forEach((m, i) => {
      const got = n.members[i];
      if (!got || got.join() !== m.join()) out.push(`${name}.${m[0]} was slot ${m[1]} offset ${m[2]} ${m[3]}, is ${got ? `${got[0]} at slot ${got[1]} offset ${got[2]} ${got[3]}` : "gone"}`);
    });
    if (n.bytes !== s.bytes && inline.has(name)) out.push(`${name} sits inline in another struct and grew from ${s.bytes} to ${n.bytes} bytes`);
  }
  return out;
}

const now = current();
let was: Layout | null = null;
try {
  was = (JSON.parse(readFileSync(path, "utf8")) as { structs: Layout }).structs;
} catch {}
const broken = was ? breaks(was, now.layout, now.inline) : [];
const body =
  JSON.stringify({ about: "Generated by packages/contracts/evm/layout.ts. Every field of a stored struct stays where it is: add at the end.", structs: now.layout }, null, 2)
    // One field a line: [label, slot, offset, type].
    .replace(/\[\s+("[^"]*"),\s+(\d+),\s+(\d+),\s+("[^"]*")\s+\]/g, "[$1, $2, $3, $4]") + "\n";

if (process.argv.includes("--check")) {
  if (broken.length) {
    console.error(`storage layout breaks the live proxies:\n  ${broken.join("\n  ")}`);
    process.exit(1);
  }
  if (!was || readFileSync(path, "utf8") !== body) {
    console.error("storage layout changed, compatibly: run bun packages/contracts/evm/layout.ts to record it");
    process.exit(1);
  }
  console.log("storage layout is unchanged");
} else {
  if (broken.length && !process.argv.includes("--force")) {
    console.error(`refusing to record a layout that breaks the live proxies:\n  ${broken.join("\n  ")}`);
    process.exit(1);
  }
  writeFileSync(path, body);
  console.log(`${Object.keys(now.layout).length} structs`);
}
