/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  getAddressEncoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  type Address,
  type ProgramDerivedAddress,
} from "@solana/kit";

export type CallerPlayerSeeds = {
  caller: Address;
};

export async function findCallerPlayerPda(
  seeds: CallerPlayerSeeds,
  config: { programAddress?: Address | undefined } = {},
): Promise<ProgramDerivedAddress> {
  const {
    programAddress = "2k9WY5YR357AGVVoBW6ouFHijEypTj8953fzSdD7HfRV" as Address<"2k9WY5YR357AGVVoBW6ouFHijEypTj8953fzSdD7HfRV">,
  } = config;
  return await getProgramDerivedAddress({
    programAddress,
    seeds: [
      getBytesEncoder().encode(new Uint8Array([112, 108, 97, 121, 101, 114])),
      getAddressEncoder().encode(seeds.caller),
    ],
  });
}
