/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  getBytesEncoder,
  getProgramDerivedAddress,
  type Address,
  type ProgramDerivedAddress,
} from "@solana/kit";

export async function findRewardsPda(
  config: { programAddress?: Address | undefined } = {},
): Promise<ProgramDerivedAddress> {
  const {
    programAddress = "2k9WY5YR357AGVVoBW6ouFHijEypTj8953fzSdD7HfRV" as Address<"2k9WY5YR357AGVVoBW6ouFHijEypTj8953fzSdD7HfRV">,
  } = config;
  return await getProgramDerivedAddress({
    programAddress,
    seeds: [
      getBytesEncoder().encode(
        new Uint8Array([114, 101, 119, 97, 114, 100, 115]),
      ),
    ],
  });
}
